// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package gateway_target

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/bedrockagentcorecontrol-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.GatewayTarget{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetGatewayTargetOutput
	resp, err = rm.sdkapi.GetGatewayTarget(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetGatewayTarget", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CredentialProviderConfigurations != nil {
		f1 := []*svcapitypes.CredentialProviderConfiguration{}
		for _, f1iter := range resp.CredentialProviderConfigurations {
			f1elem := &svcapitypes.CredentialProviderConfiguration{}
			if f1iter.CredentialProvider != nil {
				f1elemf0 := &svcapitypes.CredentialProvider{}
				switch f1iter.CredentialProvider.(type) {
				case *svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider:
					f1elemf0f0 := f1iter.CredentialProvider.(*svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider)
					if f1elemf0f0 != nil {
						f1elemf0f0f0 := &svcapitypes.GatewayAPIKeyCredentialProvider{}
						if f1elemf0f0.Value.CredentialLocation != "" {
							f1elemf0f0f0.CredentialLocation = aws.String(string(f1elemf0f0.Value.CredentialLocation))
						}
						if f1elemf0f0.Value.CredentialParameterName != nil {
							f1elemf0f0f0.CredentialParameterName = f1elemf0f0.Value.CredentialParameterName
						}
						if f1elemf0f0.Value.CredentialPrefix != nil {
							f1elemf0f0f0.CredentialPrefix = f1elemf0f0.Value.CredentialPrefix
						}
						if f1elemf0f0.Value.ProviderArn != nil {
							f1elemf0f0f0.ProviderARN = f1elemf0f0.Value.ProviderArn
						}
						f1elemf0.APIKeyCredentialProvider = f1elemf0f0f0
					}
				case *svcsdktypes.CredentialProviderMemberOauthCredentialProvider:
					f1elemf0f1 := f1iter.CredentialProvider.(*svcsdktypes.CredentialProviderMemberOauthCredentialProvider)
					if f1elemf0f1 != nil {
						f1elemf0f1f1 := &svcapitypes.OAuthCredentialProvider{}
						if f1elemf0f1.Value.CustomParameters != nil {
							f1elemf0f1f1.CustomParameters = aws.StringMap(f1elemf0f1.Value.CustomParameters)
						}
						if f1elemf0f1.Value.DefaultReturnUrl != nil {
							f1elemf0f1f1.DefaultReturnURL = f1elemf0f1.Value.DefaultReturnUrl
						}
						if f1elemf0f1.Value.GrantType != "" {
							f1elemf0f1f1.GrantType = aws.String(string(f1elemf0f1.Value.GrantType))
						}
						if f1elemf0f1.Value.ProviderArn != nil {
							f1elemf0f1f1.ProviderARN = f1elemf0f1.Value.ProviderArn
						}
						if f1elemf0f1.Value.Scopes != nil {
							f1elemf0f1f1.Scopes = aws.StringSlice(f1elemf0f1.Value.Scopes)
						}
						f1elemf0.OauthCredentialProvider = f1elemf0f1f1
					}
				}
				f1elem.CredentialProvider = f1elemf0
			}
			if f1iter.CredentialProviderType != "" {
				f1elem.CredentialProviderType = aws.String(string(f1iter.CredentialProviderType))
			}
			f1 = append(f1, f1elem)
		}
		ko.Spec.CredentialProviderConfigurations = f1
	} else {
		ko.Spec.CredentialProviderConfigurations = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.GatewayArn != nil {
		ko.Status.GatewayARN = resp.GatewayArn
	} else {
		ko.Status.GatewayARN = nil
	}
	if resp.LastSynchronizedAt != nil {
		ko.Status.LastSynchronizedAt = &metav1.Time{*resp.LastSynchronizedAt}
	} else {
		ko.Status.LastSynchronizedAt = nil
	}
	if resp.MetadataConfiguration != nil {
		f5 := &svcapitypes.MetadataConfiguration{}
		if resp.MetadataConfiguration.AllowedQueryParameters != nil {
			f5.AllowedQueryParameters = aws.StringSlice(resp.MetadataConfiguration.AllowedQueryParameters)
		}
		if resp.MetadataConfiguration.AllowedRequestHeaders != nil {
			f5.AllowedRequestHeaders = aws.StringSlice(resp.MetadataConfiguration.AllowedRequestHeaders)
		}
		if resp.MetadataConfiguration.AllowedResponseHeaders != nil {
			f5.AllowedResponseHeaders = aws.StringSlice(resp.MetadataConfiguration.AllowedResponseHeaders)
		}
		ko.Spec.MetadataConfiguration = f5
	} else {
		ko.Spec.MetadataConfiguration = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.PrivateEndpoint != nil {
		f7 := &svcapitypes.PrivateEndpoint{}
		switch resp.PrivateEndpoint.(type) {
		case *svcsdktypes.PrivateEndpointMemberManagedVpcResource:
			f7f0 := resp.PrivateEndpoint.(*svcsdktypes.PrivateEndpointMemberManagedVpcResource)
			if f7f0 != nil {
				f7f0f0 := &svcapitypes.ManagedVPCResource{}
				if f7f0.Value.EndpointIpAddressType != "" {
					f7f0f0.EndpointIPAddressType = aws.String(string(f7f0.Value.EndpointIpAddressType))
				}
				if f7f0.Value.RoutingDomain != nil {
					f7f0f0.RoutingDomain = f7f0.Value.RoutingDomain
				}
				if f7f0.Value.SecurityGroupIds != nil {
					f7f0f0.SecurityGroupIDs = aws.StringSlice(f7f0.Value.SecurityGroupIds)
				}
				if f7f0.Value.SubnetIds != nil {
					f7f0f0.SubnetIDs = aws.StringSlice(f7f0.Value.SubnetIds)
				}
				if f7f0.Value.Tags != nil {
					f7f0f0.Tags = aws.StringMap(f7f0.Value.Tags)
				}
				if f7f0.Value.VpcIdentifier != nil {
					f7f0f0.VPCIdentifier = f7f0.Value.VpcIdentifier
				}
				f7.ManagedVPCResource = f7f0f0
			}
		case *svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource:
			f7f1 := resp.PrivateEndpoint.(*svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource)
			if f7f1 != nil {
				f7f1f1 := &svcapitypes.SelfManagedLatticeResource{}
				switch f7f1.Value.(type) {
				case *svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier:
					f7f1f1f0 := f7f1.Value.(*svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier)
					if f7f1f1f0 != nil {
						f7f1f1.ResourceConfigurationIdentifier = &f7f1f1f0.Value
					}
				}
				f7.SelfManagedLatticeResource = f7f1f1
			}
		}
		ko.Spec.PrivateEndpoint = f7
	} else {
		ko.Spec.PrivateEndpoint = nil
	}
	if resp.PrivateEndpointManagedResources != nil {
		f8 := []*svcapitypes.ManagedResourceDetails{}
		for _, f8iter := range resp.PrivateEndpointManagedResources {
			f8elem := &svcapitypes.ManagedResourceDetails{}
			if f8iter.Domain != nil {
				f8elem.Domain = f8iter.Domain
			}
			if f8iter.ResourceAssociationArn != nil {
				f8elem.ResourceAssociationARN = f8iter.ResourceAssociationArn
			}
			if f8iter.ResourceGatewayArn != nil {
				f8elem.ResourceGatewayARN = f8iter.ResourceGatewayArn
			}
			f8 = append(f8, f8elem)
		}
		ko.Status.PrivateEndpointManagedResources = f8
	} else {
		ko.Status.PrivateEndpointManagedResources = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.StatusReasons != nil {
		ko.Status.StatusReasons = aws.StringSlice(resp.StatusReasons)
	} else {
		ko.Status.StatusReasons = nil
	}
	if resp.TargetConfiguration != nil {
		f11 := &svcapitypes.TargetConfiguration{}
		switch resp.TargetConfiguration.(type) {
		case *svcsdktypes.TargetConfigurationMemberMcp:
			f11f0 := resp.TargetConfiguration.(*svcsdktypes.TargetConfigurationMemberMcp)
			if f11f0 != nil {
				f11f0f0 := &svcapitypes.McpTargetConfiguration{}
				switch f11f0.Value.(type) {
				case *svcsdktypes.McpTargetConfigurationMemberApiGateway:
					f11f0f0f0 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberApiGateway)
					if f11f0f0f0 != nil {
						f11f0f0f0f0 := &svcapitypes.APIGatewayTargetConfiguration{}
						if f11f0f0f0.Value.ApiGatewayToolConfiguration != nil {
							f11f0f0f0f0f0 := &svcapitypes.APIGatewayToolConfiguration{}
							if f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolFilters != nil {
								f11f0f0f0f0f0f0 := []*svcapitypes.APIGatewayToolFilter{}
								for _, f11f0f0f0f0f0f0iter := range f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolFilters {
									f11f0f0f0f0f0f0elem := &svcapitypes.APIGatewayToolFilter{}
									if f11f0f0f0f0f0f0iter.FilterPath != nil {
										f11f0f0f0f0f0f0elem.FilterPath = f11f0f0f0f0f0f0iter.FilterPath
									}
									if f11f0f0f0f0f0f0iter.Methods != nil {
										f11f0f0f0f0f0f0elemf1 := []*string{}
										for _, f11f0f0f0f0f0f0elemf1iter := range f11f0f0f0f0f0f0iter.Methods {
											var f11f0f0f0f0f0f0elemf1elem *string
											f11f0f0f0f0f0f0elemf1elem = aws.String(string(f11f0f0f0f0f0f0elemf1iter))
											f11f0f0f0f0f0f0elemf1 = append(f11f0f0f0f0f0f0elemf1, f11f0f0f0f0f0f0elemf1elem)
										}
										f11f0f0f0f0f0f0elem.Methods = f11f0f0f0f0f0f0elemf1
									}
									f11f0f0f0f0f0f0 = append(f11f0f0f0f0f0f0, f11f0f0f0f0f0f0elem)
								}
								f11f0f0f0f0f0.ToolFilters = f11f0f0f0f0f0f0
							}
							if f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolOverrides != nil {
								f11f0f0f0f0f0f1 := []*svcapitypes.APIGatewayToolOverride{}
								for _, f11f0f0f0f0f0f1iter := range f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolOverrides {
									f11f0f0f0f0f0f1elem := &svcapitypes.APIGatewayToolOverride{}
									if f11f0f0f0f0f0f1iter.Description != nil {
										f11f0f0f0f0f0f1elem.Description = f11f0f0f0f0f0f1iter.Description
									}
									if f11f0f0f0f0f0f1iter.Method != "" {
										f11f0f0f0f0f0f1elem.Method = aws.String(string(f11f0f0f0f0f0f1iter.Method))
									}
									if f11f0f0f0f0f0f1iter.Name != nil {
										f11f0f0f0f0f0f1elem.Name = f11f0f0f0f0f0f1iter.Name
									}
									if f11f0f0f0f0f0f1iter.Path != nil {
										f11f0f0f0f0f0f1elem.Path = f11f0f0f0f0f0f1iter.Path
									}
									f11f0f0f0f0f0f1 = append(f11f0f0f0f0f0f1, f11f0f0f0f0f0f1elem)
								}
								f11f0f0f0f0f0.ToolOverrides = f11f0f0f0f0f0f1
							}
							f11f0f0f0f0.APIGatewayToolConfiguration = f11f0f0f0f0f0
						}
						if f11f0f0f0.Value.RestApiId != nil {
							f11f0f0f0f0.RestAPIID = f11f0f0f0.Value.RestApiId
						}
						if f11f0f0f0.Value.Stage != nil {
							f11f0f0f0f0.Stage = f11f0f0f0.Value.Stage
						}
						f11f0f0.APIGateway = f11f0f0f0f0
					}
				case *svcsdktypes.McpTargetConfigurationMemberLambda:
					f11f0f0f1 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberLambda)
					if f11f0f0f1 != nil {
						f11f0f0f1f1 := &svcapitypes.McpLambdaTargetConfiguration{}
						if f11f0f0f1.Value.LambdaArn != nil {
							f11f0f0f1f1.LambdaARN = f11f0f0f1.Value.LambdaArn
						}
						if f11f0f0f1.Value.ToolSchema != nil {
							f11f0f0f1f1f1 := &svcapitypes.ToolSchema{}
							switch f11f0f0f1.Value.ToolSchema.(type) {
							case *svcsdktypes.ToolSchemaMemberInlinePayload:
								f11f0f0f1f1f1f0 := f11f0f0f1.Value.ToolSchema.(*svcsdktypes.ToolSchemaMemberInlinePayload)
								if f11f0f0f1f1f1f0 != nil {
									f11f0f0f1f1f1f0f0 := []*svcapitypes.ToolDefinition{}
									for _, f11f0f0f1f1f1f0f0iter := range f11f0f0f1f1f1f0.Value {
										f11f0f0f1f1f1f0f0elem := &svcapitypes.ToolDefinition{}
										if f11f0f0f1f1f1f0f0iter.Description != nil {
											f11f0f0f1f1f1f0f0elem.Description = f11f0f0f1f1f1f0f0iter.Description
										}
										if f11f0f0f1f1f1f0f0iter.Name != nil {
											f11f0f0f1f1f1f0f0elem.Name = f11f0f0f1f1f1f0f0iter.Name
										}
										f11f0f0f1f1f1f0f0 = append(f11f0f0f1f1f1f0f0, f11f0f0f1f1f1f0f0elem)
									}
									f11f0f0f1f1f1.InlinePayload = f11f0f0f1f1f1f0f0
								}
							case *svcsdktypes.ToolSchemaMemberS3:
								f11f0f0f1f1f1f1 := f11f0f0f1.Value.ToolSchema.(*svcsdktypes.ToolSchemaMemberS3)
								if f11f0f0f1f1f1f1 != nil {
									f11f0f0f1f1f1f1f1 := &svcapitypes.S3Configuration{}
									if f11f0f0f1f1f1f1.Value.BucketOwnerAccountId != nil {
										f11f0f0f1f1f1f1f1.BucketOwnerAccountID = f11f0f0f1f1f1f1.Value.BucketOwnerAccountId
									}
									if f11f0f0f1f1f1f1.Value.Uri != nil {
										f11f0f0f1f1f1f1f1.URI = f11f0f0f1f1f1f1.Value.Uri
									}
									f11f0f0f1f1f1.S3 = f11f0f0f1f1f1f1f1
								}
							}
							f11f0f0f1f1.ToolSchema = f11f0f0f1f1f1
						}
						f11f0f0.Lambda = f11f0f0f1f1
					}
				case *svcsdktypes.McpTargetConfigurationMemberMcpServer:
					f11f0f0f2 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberMcpServer)
					if f11f0f0f2 != nil {
						f11f0f0f2f2 := &svcapitypes.McpServerTargetConfiguration{}
						if f11f0f0f2.Value.Endpoint != nil {
							f11f0f0f2f2.Endpoint = f11f0f0f2.Value.Endpoint
						}
						f11f0f0.McpServer = f11f0f0f2f2
					}
				case *svcsdktypes.McpTargetConfigurationMemberOpenApiSchema:
					f11f0f0f3 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberOpenApiSchema)
					if f11f0f0f3 != nil {
						f11f0f0f3f3 := &svcapitypes.APISchemaConfiguration{}
						switch f11f0f0f3.Value.(type) {
						case *svcsdktypes.ApiSchemaConfigurationMemberInlinePayload:
							f11f0f0f3f3f0 := f11f0f0f3.Value.(*svcsdktypes.ApiSchemaConfigurationMemberInlinePayload)
							if f11f0f0f3f3f0 != nil {
								f11f0f0f3f3.InlinePayload = &f11f0f0f3f3f0.Value
							}
						case *svcsdktypes.ApiSchemaConfigurationMemberS3:
							f11f0f0f3f3f1 := f11f0f0f3.Value.(*svcsdktypes.ApiSchemaConfigurationMemberS3)
							if f11f0f0f3f3f1 != nil {
								f11f0f0f3f3f1f1 := &svcapitypes.S3Configuration{}
								if f11f0f0f3f3f1.Value.BucketOwnerAccountId != nil {
									f11f0f0f3f3f1f1.BucketOwnerAccountID = f11f0f0f3f3f1.Value.BucketOwnerAccountId
								}
								if f11f0f0f3f3f1.Value.Uri != nil {
									f11f0f0f3f3f1f1.URI = f11f0f0f3f3f1.Value.Uri
								}
								f11f0f0f3f3.S3 = f11f0f0f3f3f1f1
							}
						}
						f11f0f0.OpenAPISchema = f11f0f0f3f3
					}
				case *svcsdktypes.McpTargetConfigurationMemberSmithyModel:
					f11f0f0f4 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberSmithyModel)
					if f11f0f0f4 != nil {
						f11f0f0f4f4 := &svcapitypes.APISchemaConfiguration{}
						switch f11f0f0f4.Value.(type) {
						case *svcsdktypes.ApiSchemaConfigurationMemberInlinePayload:
							f11f0f0f4f4f0 := f11f0f0f4.Value.(*svcsdktypes.ApiSchemaConfigurationMemberInlinePayload)
							if f11f0f0f4f4f0 != nil {
								f11f0f0f4f4.InlinePayload = &f11f0f0f4f4f0.Value
							}
						case *svcsdktypes.ApiSchemaConfigurationMemberS3:
							f11f0f0f4f4f1 := f11f0f0f4.Value.(*svcsdktypes.ApiSchemaConfigurationMemberS3)
							if f11f0f0f4f4f1 != nil {
								f11f0f0f4f4f1f1 := &svcapitypes.S3Configuration{}
								if f11f0f0f4f4f1.Value.BucketOwnerAccountId != nil {
									f11f0f0f4f4f1f1.BucketOwnerAccountID = f11f0f0f4f4f1.Value.BucketOwnerAccountId
								}
								if f11f0f0f4f4f1.Value.Uri != nil {
									f11f0f0f4f4f1f1.URI = f11f0f0f4f4f1.Value.Uri
								}
								f11f0f0f4f4.S3 = f11f0f0f4f4f1f1
							}
						}
						f11f0f0.SmithyModel = f11f0f0f4f4
					}
				}
				f11.Mcp = f11f0f0
			}
		}
		ko.Spec.TargetConfiguration = f11
	} else {
		ko.Spec.TargetConfiguration = nil
	}
	if resp.TargetId != nil {
		ko.Status.TargetID = resp.TargetId
	} else {
		ko.Status.TargetID = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	if err := setSchemaDefinitionsFromSDKResponse(ko, resp); err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.GatewayIdentifier == nil || r.ko.Status.TargetID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetGatewayTargetInput, error) {
	res := &svcsdk.GetGatewayTargetInput{}

	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Status.TargetID != nil {
		res.TargetId = r.ko.Status.TargetID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	if err := setSchemaDefinitionsOnCreateInput(desired, input); err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateGatewayTargetOutput
	_ = resp
	resp, err = rm.sdkapi.CreateGatewayTarget(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateGatewayTarget", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CredentialProviderConfigurations != nil {
		f1 := []*svcapitypes.CredentialProviderConfiguration{}
		for _, f1iter := range resp.CredentialProviderConfigurations {
			f1elem := &svcapitypes.CredentialProviderConfiguration{}
			if f1iter.CredentialProvider != nil {
				f1elemf0 := &svcapitypes.CredentialProvider{}
				switch f1iter.CredentialProvider.(type) {
				case *svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider:
					f1elemf0f0 := f1iter.CredentialProvider.(*svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider)
					if f1elemf0f0 != nil {
						f1elemf0f0f0 := &svcapitypes.GatewayAPIKeyCredentialProvider{}
						if f1elemf0f0.Value.CredentialLocation != "" {
							f1elemf0f0f0.CredentialLocation = aws.String(string(f1elemf0f0.Value.CredentialLocation))
						}
						if f1elemf0f0.Value.CredentialParameterName != nil {
							f1elemf0f0f0.CredentialParameterName = f1elemf0f0.Value.CredentialParameterName
						}
						if f1elemf0f0.Value.CredentialPrefix != nil {
							f1elemf0f0f0.CredentialPrefix = f1elemf0f0.Value.CredentialPrefix
						}
						if f1elemf0f0.Value.ProviderArn != nil {
							f1elemf0f0f0.ProviderARN = f1elemf0f0.Value.ProviderArn
						}
						f1elemf0.APIKeyCredentialProvider = f1elemf0f0f0
					}
				case *svcsdktypes.CredentialProviderMemberOauthCredentialProvider:
					f1elemf0f1 := f1iter.CredentialProvider.(*svcsdktypes.CredentialProviderMemberOauthCredentialProvider)
					if f1elemf0f1 != nil {
						f1elemf0f1f1 := &svcapitypes.OAuthCredentialProvider{}
						if f1elemf0f1.Value.CustomParameters != nil {
							f1elemf0f1f1.CustomParameters = aws.StringMap(f1elemf0f1.Value.CustomParameters)
						}
						if f1elemf0f1.Value.DefaultReturnUrl != nil {
							f1elemf0f1f1.DefaultReturnURL = f1elemf0f1.Value.DefaultReturnUrl
						}
						if f1elemf0f1.Value.GrantType != "" {
							f1elemf0f1f1.GrantType = aws.String(string(f1elemf0f1.Value.GrantType))
						}
						if f1elemf0f1.Value.ProviderArn != nil {
							f1elemf0f1f1.ProviderARN = f1elemf0f1.Value.ProviderArn
						}
						if f1elemf0f1.Value.Scopes != nil {
							f1elemf0f1f1.Scopes = aws.StringSlice(f1elemf0f1.Value.Scopes)
						}
						f1elemf0.OauthCredentialProvider = f1elemf0f1f1
					}
				}
				f1elem.CredentialProvider = f1elemf0
			}
			if f1iter.CredentialProviderType != "" {
				f1elem.CredentialProviderType = aws.String(string(f1iter.CredentialProviderType))
			}
			f1 = append(f1, f1elem)
		}
		ko.Spec.CredentialProviderConfigurations = f1
	} else {
		ko.Spec.CredentialProviderConfigurations = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.GatewayArn != nil {
		ko.Status.GatewayARN = resp.GatewayArn
	} else {
		ko.Status.GatewayARN = nil
	}
	if resp.LastSynchronizedAt != nil {
		ko.Status.LastSynchronizedAt = &metav1.Time{*resp.LastSynchronizedAt}
	} else {
		ko.Status.LastSynchronizedAt = nil
	}
	if resp.MetadataConfiguration != nil {
		f5 := &svcapitypes.MetadataConfiguration{}
		if resp.MetadataConfiguration.AllowedQueryParameters != nil {
			f5.AllowedQueryParameters = aws.StringSlice(resp.MetadataConfiguration.AllowedQueryParameters)
		}
		if resp.MetadataConfiguration.AllowedRequestHeaders != nil {
			f5.AllowedRequestHeaders = aws.StringSlice(resp.MetadataConfiguration.AllowedRequestHeaders)
		}
		if resp.MetadataConfiguration.AllowedResponseHeaders != nil {
			f5.AllowedResponseHeaders = aws.StringSlice(resp.MetadataConfiguration.AllowedResponseHeaders)
		}
		ko.Spec.MetadataConfiguration = f5
	} else {
		ko.Spec.MetadataConfiguration = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.PrivateEndpoint != nil {
		f7 := &svcapitypes.PrivateEndpoint{}
		switch resp.PrivateEndpoint.(type) {
		case *svcsdktypes.PrivateEndpointMemberManagedVpcResource:
			f7f0 := resp.PrivateEndpoint.(*svcsdktypes.PrivateEndpointMemberManagedVpcResource)
			if f7f0 != nil {
				f7f0f0 := &svcapitypes.ManagedVPCResource{}
				if f7f0.Value.EndpointIpAddressType != "" {
					f7f0f0.EndpointIPAddressType = aws.String(string(f7f0.Value.EndpointIpAddressType))
				}
				if f7f0.Value.RoutingDomain != nil {
					f7f0f0.RoutingDomain = f7f0.Value.RoutingDomain
				}
				if f7f0.Value.SecurityGroupIds != nil {
					f7f0f0.SecurityGroupIDs = aws.StringSlice(f7f0.Value.SecurityGroupIds)
				}
				if f7f0.Value.SubnetIds != nil {
					f7f0f0.SubnetIDs = aws.StringSlice(f7f0.Value.SubnetIds)
				}
				if f7f0.Value.Tags != nil {
					f7f0f0.Tags = aws.StringMap(f7f0.Value.Tags)
				}
				if f7f0.Value.VpcIdentifier != nil {
					f7f0f0.VPCIdentifier = f7f0.Value.VpcIdentifier
				}
				f7.ManagedVPCResource = f7f0f0
			}
		case *svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource:
			f7f1 := resp.PrivateEndpoint.(*svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource)
			if f7f1 != nil {
				f7f1f1 := &svcapitypes.SelfManagedLatticeResource{}
				switch f7f1.Value.(type) {
				case *svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier:
					f7f1f1f0 := f7f1.Value.(*svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier)
					if f7f1f1f0 != nil {
						f7f1f1.ResourceConfigurationIdentifier = &f7f1f1f0.Value
					}
				}
				f7.SelfManagedLatticeResource = f7f1f1
			}
		}
		ko.Spec.PrivateEndpoint = f7
	} else {
		ko.Spec.PrivateEndpoint = nil
	}
	if resp.PrivateEndpointManagedResources != nil {
		f8 := []*svcapitypes.ManagedResourceDetails{}
		for _, f8iter := range resp.PrivateEndpointManagedResources {
			f8elem := &svcapitypes.ManagedResourceDetails{}
			if f8iter.Domain != nil {
				f8elem.Domain = f8iter.Domain
			}
			if f8iter.ResourceAssociationArn != nil {
				f8elem.ResourceAssociationARN = f8iter.ResourceAssociationArn
			}
			if f8iter.ResourceGatewayArn != nil {
				f8elem.ResourceGatewayARN = f8iter.ResourceGatewayArn
			}
			f8 = append(f8, f8elem)
		}
		ko.Status.PrivateEndpointManagedResources = f8
	} else {
		ko.Status.PrivateEndpointManagedResources = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.StatusReasons != nil {
		ko.Status.StatusReasons = aws.StringSlice(resp.StatusReasons)
	} else {
		ko.Status.StatusReasons = nil
	}
	if resp.TargetConfiguration != nil {
		f11 := &svcapitypes.TargetConfiguration{}
		switch resp.TargetConfiguration.(type) {
		case *svcsdktypes.TargetConfigurationMemberMcp:
			f11f0 := resp.TargetConfiguration.(*svcsdktypes.TargetConfigurationMemberMcp)
			if f11f0 != nil {
				f11f0f0 := &svcapitypes.McpTargetConfiguration{}
				switch f11f0.Value.(type) {
				case *svcsdktypes.McpTargetConfigurationMemberApiGateway:
					f11f0f0f0 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberApiGateway)
					if f11f0f0f0 != nil {
						f11f0f0f0f0 := &svcapitypes.APIGatewayTargetConfiguration{}
						if f11f0f0f0.Value.ApiGatewayToolConfiguration != nil {
							f11f0f0f0f0f0 := &svcapitypes.APIGatewayToolConfiguration{}
							if f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolFilters != nil {
								f11f0f0f0f0f0f0 := []*svcapitypes.APIGatewayToolFilter{}
								for _, f11f0f0f0f0f0f0iter := range f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolFilters {
									f11f0f0f0f0f0f0elem := &svcapitypes.APIGatewayToolFilter{}
									if f11f0f0f0f0f0f0iter.FilterPath != nil {
										f11f0f0f0f0f0f0elem.FilterPath = f11f0f0f0f0f0f0iter.FilterPath
									}
									if f11f0f0f0f0f0f0iter.Methods != nil {
										f11f0f0f0f0f0f0elemf1 := []*string{}
										for _, f11f0f0f0f0f0f0elemf1iter := range f11f0f0f0f0f0f0iter.Methods {
											var f11f0f0f0f0f0f0elemf1elem *string
											f11f0f0f0f0f0f0elemf1elem = aws.String(string(f11f0f0f0f0f0f0elemf1iter))
											f11f0f0f0f0f0f0elemf1 = append(f11f0f0f0f0f0f0elemf1, f11f0f0f0f0f0f0elemf1elem)
										}
										f11f0f0f0f0f0f0elem.Methods = f11f0f0f0f0f0f0elemf1
									}
									f11f0f0f0f0f0f0 = append(f11f0f0f0f0f0f0, f11f0f0f0f0f0f0elem)
								}
								f11f0f0f0f0f0.ToolFilters = f11f0f0f0f0f0f0
							}
							if f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolOverrides != nil {
								f11f0f0f0f0f0f1 := []*svcapitypes.APIGatewayToolOverride{}
								for _, f11f0f0f0f0f0f1iter := range f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolOverrides {
									f11f0f0f0f0f0f1elem := &svcapitypes.APIGatewayToolOverride{}
									if f11f0f0f0f0f0f1iter.Description != nil {
										f11f0f0f0f0f0f1elem.Description = f11f0f0f0f0f0f1iter.Description
									}
									if f11f0f0f0f0f0f1iter.Method != "" {
										f11f0f0f0f0f0f1elem.Method = aws.String(string(f11f0f0f0f0f0f1iter.Method))
									}
									if f11f0f0f0f0f0f1iter.Name != nil {
										f11f0f0f0f0f0f1elem.Name = f11f0f0f0f0f0f1iter.Name
									}
									if f11f0f0f0f0f0f1iter.Path != nil {
										f11f0f0f0f0f0f1elem.Path = f11f0f0f0f0f0f1iter.Path
									}
									f11f0f0f0f0f0f1 = append(f11f0f0f0f0f0f1, f11f0f0f0f0f0f1elem)
								}
								f11f0f0f0f0f0.ToolOverrides = f11f0f0f0f0f0f1
							}
							f11f0f0f0f0.APIGatewayToolConfiguration = f11f0f0f0f0f0
						}
						if f11f0f0f0.Value.RestApiId != nil {
							f11f0f0f0f0.RestAPIID = f11f0f0f0.Value.RestApiId
						}
						if f11f0f0f0.Value.Stage != nil {
							f11f0f0f0f0.Stage = f11f0f0f0.Value.Stage
						}
						f11f0f0.APIGateway = f11f0f0f0f0
					}
				case *svcsdktypes.McpTargetConfigurationMemberLambda:
					f11f0f0f1 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberLambda)
					if f11f0f0f1 != nil {
						f11f0f0f1f1 := &svcapitypes.McpLambdaTargetConfiguration{}
						if f11f0f0f1.Value.LambdaArn != nil {
							f11f0f0f1f1.LambdaARN = f11f0f0f1.Value.LambdaArn
						}
						if f11f0f0f1.Value.ToolSchema != nil {
							f11f0f0f1f1f1 := &svcapitypes.ToolSchema{}
							switch f11f0f0f1.Value.ToolSchema.(type) {
							case *svcsdktypes.ToolSchemaMemberS3:
								f11f0f0f1f1f1f1 := f11f0f0f1.Value.ToolSchema.(*svcsdktypes.ToolSchemaMemberS3)
								if f11f0f0f1f1f1f1 != nil {
									f11f0f0f1f1f1f1f1 := &svcapitypes.S3Configuration{}
									if f11f0f0f1f1f1f1.Value.BucketOwnerAccountId != nil {
										f11f0f0f1f1f1f1f1.BucketOwnerAccountID = f11f0f0f1f1f1f1.Value.BucketOwnerAccountId
									}
									if f11f0f0f1f1f1f1.Value.Uri != nil {
										f11f0f0f1f1f1f1f1.URI = f11f0f0f1f1f1f1.Value.Uri
									}
									f11f0f0f1f1f1.S3 = f11f0f0f1f1f1f1f1
								}
							}
							f11f0f0f1f1.ToolSchema = f11f0f0f1f1f1
						}
						f11f0f0.Lambda = f11f0f0f1f1
					}
				case *svcsdktypes.McpTargetConfigurationMemberMcpServer:
					f11f0f0f2 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberMcpServer)
					if f11f0f0f2 != nil {
						f11f0f0f2f2 := &svcapitypes.McpServerTargetConfiguration{}
						if f11f0f0f2.Value.Endpoint != nil {
							f11f0f0f2f2.Endpoint = f11f0f0f2.Value.Endpoint
						}
						f11f0f0.McpServer = f11f0f0f2f2
					}
				case *svcsdktypes.McpTargetConfigurationMemberOpenApiSchema:
					f11f0f0f3 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberOpenApiSchema)
					if f11f0f0f3 != nil {
						f11f0f0f3f3 := &svcapitypes.APISchemaConfiguration{}
						switch f11f0f0f3.Value.(type) {
						case *svcsdktypes.ApiSchemaConfigurationMemberInlinePayload:
							f11f0f0f3f3f0 := f11f0f0f3.Value.(*svcsdktypes.ApiSchemaConfigurationMemberInlinePayload)
							if f11f0f0f3f3f0 != nil {
								f11f0f0f3f3.InlinePayload = &f11f0f0f3f3f0.Value
							}
						case *svcsdktypes.ApiSchemaConfigurationMemberS3:
							f11f0f0f3f3f1 := f11f0f0f3.Value.(*svcsdktypes.ApiSchemaConfigurationMemberS3)
							if f11f0f0f3f3f1 != nil {
								f11f0f0f3f3f1f1 := &svcapitypes.S3Configuration{}
								if f11f0f0f3f3f1.Value.BucketOwnerAccountId != nil {
									f11f0f0f3f3f1f1.BucketOwnerAccountID = f11f0f0f3f3f1.Value.BucketOwnerAccountId
								}
								if f11f0f0f3f3f1.Value.Uri != nil {
									f11f0f0f3f3f1f1.URI = f11f0f0f3f3f1.Value.Uri
								}
								f11f0f0f3f3.S3 = f11f0f0f3f3f1f1
							}
						}
						f11f0f0.OpenAPISchema = f11f0f0f3f3
					}
				case *svcsdktypes.McpTargetConfigurationMemberSmithyModel:
					f11f0f0f4 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberSmithyModel)
					if f11f0f0f4 != nil {
						f11f0f0f4f4 := &svcapitypes.APISchemaConfiguration{}
						switch f11f0f0f4.Value.(type) {
						case *svcsdktypes.ApiSchemaConfigurationMemberInlinePayload:
							f11f0f0f4f4f0 := f11f0f0f4.Value.(*svcsdktypes.ApiSchemaConfigurationMemberInlinePayload)
							if f11f0f0f4f4f0 != nil {
								f11f0f0f4f4.InlinePayload = &f11f0f0f4f4f0.Value
							}
						case *svcsdktypes.ApiSchemaConfigurationMemberS3:
							f11f0f0f4f4f1 := f11f0f0f4.Value.(*svcsdktypes.ApiSchemaConfigurationMemberS3)
							if f11f0f0f4f4f1 != nil {
								f11f0f0f4f4f1f1 := &svcapitypes.S3Configuration{}
								if f11f0f0f4f4f1.Value.BucketOwnerAccountId != nil {
									f11f0f0f4f4f1f1.BucketOwnerAccountID = f11f0f0f4f4f1.Value.BucketOwnerAccountId
								}
								if f11f0f0f4f4f1.Value.Uri != nil {
									f11f0f0f4f4f1f1.URI = f11f0f0f4f4f1.Value.Uri
								}
								f11f0f0f4f4.S3 = f11f0f0f4f4f1f1
							}
						}
						f11f0f0.SmithyModel = f11f0f0f4f4
					}
				}
				f11.Mcp = f11f0f0
			}
		}
		ko.Spec.TargetConfiguration = f11
	} else {
		ko.Spec.TargetConfiguration = nil
	}
	if resp.TargetId != nil {
		ko.Status.TargetID = resp.TargetId
	} else {
		ko.Status.TargetID = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	if desired.ko.Spec.TargetConfiguration != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp.Lambda != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload != nil {
		ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload = desired.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateGatewayTargetInput, error) {
	res := &svcsdk.CreateGatewayTargetInput{}

	if r.ko.Spec.CredentialProviderConfigurations != nil {
		f1 := []svcsdktypes.CredentialProviderConfiguration{}
		for _, f1iter := range r.ko.Spec.CredentialProviderConfigurations {
			f1elem := &svcsdktypes.CredentialProviderConfiguration{}
			if f1iter.CredentialProvider != nil {
				var f1elemf0 svcsdktypes.CredentialProvider
				isInterfaceSet := false
				if f1iter.CredentialProvider.APIKeyCredentialProvider != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ApiKeyCredentialProvider"))
					}
					f1elemf0f0Parent := &svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider{}
					f1elemf0f0 := &svcsdktypes.GatewayApiKeyCredentialProvider{}
					if f1iter.CredentialProvider.APIKeyCredentialProvider.CredentialLocation != nil {
						f1elemf0f0.CredentialLocation = svcsdktypes.ApiKeyCredentialLocation(*f1iter.CredentialProvider.APIKeyCredentialProvider.CredentialLocation)
					}
					if f1iter.CredentialProvider.APIKeyCredentialProvider.CredentialParameterName != nil {
						f1elemf0f0.CredentialParameterName = f1iter.CredentialProvider.APIKeyCredentialProvider.CredentialParameterName
					}
					if f1iter.CredentialProvider.APIKeyCredentialProvider.CredentialPrefix != nil {
						f1elemf0f0.CredentialPrefix = f1iter.CredentialProvider.APIKeyCredentialProvider.CredentialPrefix
					}
					if f1iter.CredentialProvider.APIKeyCredentialProvider.ProviderARN != nil {
						f1elemf0f0.ProviderArn = f1iter.CredentialProvider.APIKeyCredentialProvider.ProviderARN
					}
					f1elemf0f0Parent.Value = *f1elemf0f0
					f1elemf0 = f1elemf0f0Parent
					isInterfaceSet = true
				}
				if f1iter.CredentialProvider.OauthCredentialProvider != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for OauthCredentialProvider"))
					}
					f1elemf0f1Parent := &svcsdktypes.CredentialProviderMemberOauthCredentialProvider{}
					f1elemf0f1 := &svcsdktypes.OAuthCredentialProvider{}
					if f1iter.CredentialProvider.OauthCredentialProvider.CustomParameters != nil {
						f1elemf0f1.CustomParameters = aws.ToStringMap(f1iter.CredentialProvider.OauthCredentialProvider.CustomParameters)
					}
					if f1iter.CredentialProvider.OauthCredentialProvider.DefaultReturnURL != nil {
						f1elemf0f1.DefaultReturnUrl = f1iter.CredentialProvider.OauthCredentialProvider.DefaultReturnURL
					}
					if f1iter.CredentialProvider.OauthCredentialProvider.GrantType != nil {
						f1elemf0f1.GrantType = svcsdktypes.OAuthGrantType(*f1iter.CredentialProvider.OauthCredentialProvider.GrantType)
					}
					if f1iter.CredentialProvider.OauthCredentialProvider.ProviderARN != nil {
						f1elemf0f1.ProviderArn = f1iter.CredentialProvider.OauthCredentialProvider.ProviderARN
					}
					if f1iter.CredentialProvider.OauthCredentialProvider.Scopes != nil {
						f1elemf0f1.Scopes = aws.ToStringSlice(f1iter.CredentialProvider.OauthCredentialProvider.Scopes)
					}
					f1elemf0f1Parent.Value = *f1elemf0f1
					f1elemf0 = f1elemf0f1Parent
					isInterfaceSet = true
				}
				f1elem.CredentialProvider = f1elemf0
			}
			if f1iter.CredentialProviderType != nil {
				f1elem.CredentialProviderType = svcsdktypes.CredentialProviderType(*f1iter.CredentialProviderType)
			}
			f1 = append(f1, *f1elem)
		}
		res.CredentialProviderConfigurations = f1
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Spec.MetadataConfiguration != nil {
		f4 := &svcsdktypes.MetadataConfiguration{}
		if r.ko.Spec.MetadataConfiguration.AllowedQueryParameters != nil {
			f4.AllowedQueryParameters = aws.ToStringSlice(r.ko.Spec.MetadataConfiguration.AllowedQueryParameters)
		}
		if r.ko.Spec.MetadataConfiguration.AllowedRequestHeaders != nil {
			f4.AllowedRequestHeaders = aws.ToStringSlice(r.ko.Spec.MetadataConfiguration.AllowedRequestHeaders)
		}
		if r.ko.Spec.MetadataConfiguration.AllowedResponseHeaders != nil {
			f4.AllowedResponseHeaders = aws.ToStringSlice(r.ko.Spec.MetadataConfiguration.AllowedResponseHeaders)
		}
		res.MetadataConfiguration = f4
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.PrivateEndpoint != nil {
		var f6 svcsdktypes.PrivateEndpoint
		isInterfaceSet := false
		if r.ko.Spec.PrivateEndpoint.ManagedVPCResource != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ManagedVpcResource"))
			}
			f6f0Parent := &svcsdktypes.PrivateEndpointMemberManagedVpcResource{}
			f6f0 := &svcsdktypes.ManagedVpcResource{}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.EndpointIPAddressType != nil {
				f6f0.EndpointIpAddressType = svcsdktypes.EndpointIpAddressType(*r.ko.Spec.PrivateEndpoint.ManagedVPCResource.EndpointIPAddressType)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.RoutingDomain != nil {
				f6f0.RoutingDomain = r.ko.Spec.PrivateEndpoint.ManagedVPCResource.RoutingDomain
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SecurityGroupIDs != nil {
				f6f0.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SecurityGroupIDs)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SubnetIDs != nil {
				f6f0.SubnetIds = aws.ToStringSlice(r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SubnetIDs)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.Tags != nil {
				f6f0.Tags = aws.ToStringMap(r.ko.Spec.PrivateEndpoint.ManagedVPCResource.Tags)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.VPCIdentifier != nil {
				f6f0.VpcIdentifier = r.ko.Spec.PrivateEndpoint.ManagedVPCResource.VPCIdentifier
			}
			f6f0Parent.Value = *f6f0
			f6 = f6f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.PrivateEndpoint.SelfManagedLatticeResource != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SelfManagedLatticeResource"))
			}
			f6f1Parent := &svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource{}
			var f6f1 svcsdktypes.SelfManagedLatticeResource
			isInterfaceSet := false
			if r.ko.Spec.PrivateEndpoint.SelfManagedLatticeResource.ResourceConfigurationIdentifier != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ResourceConfigurationIdentifier"))
				}
				f6f1f0Parent := &svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier{}
				f6f1f0Parent.Value = *r.ko.Spec.PrivateEndpoint.SelfManagedLatticeResource.ResourceConfigurationIdentifier
				f6f1 = f6f1f0Parent
				isInterfaceSet = true
			}
			f6f1Parent.Value = f6f1
			f6 = f6f1Parent
			isInterfaceSet = true
		}
		res.PrivateEndpoint = f6
	}
	if r.ko.Spec.TargetConfiguration != nil {
		var f7 svcsdktypes.TargetConfiguration
		isInterfaceSet := false
		if r.ko.Spec.TargetConfiguration.Mcp != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Mcp"))
			}
			f7f0Parent := &svcsdktypes.TargetConfigurationMemberMcp{}
			var f7f0 svcsdktypes.McpTargetConfiguration
			isInterfaceSet := false
			if r.ko.Spec.TargetConfiguration.Mcp.APIGateway != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ApiGateway"))
				}
				f7f0f0Parent := &svcsdktypes.McpTargetConfigurationMemberApiGateway{}
				f7f0f0 := &svcsdktypes.ApiGatewayTargetConfiguration{}
				if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration != nil {
					f7f0f0f0 := &svcsdktypes.ApiGatewayToolConfiguration{}
					if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters != nil {
						f7f0f0f0f0 := []svcsdktypes.ApiGatewayToolFilter{}
						for _, f7f0f0f0f0iter := range r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters {
							f7f0f0f0f0elem := &svcsdktypes.ApiGatewayToolFilter{}
							if f7f0f0f0f0iter.FilterPath != nil {
								f7f0f0f0f0elem.FilterPath = f7f0f0f0f0iter.FilterPath
							}
							if f7f0f0f0f0iter.Methods != nil {
								f7f0f0f0f0elemf1 := []svcsdktypes.RestApiMethod{}
								for _, f7f0f0f0f0elemf1iter := range f7f0f0f0f0iter.Methods {
									var f7f0f0f0f0elemf1elem string
									f7f0f0f0f0elemf1elem = string(*f7f0f0f0f0elemf1iter)
									f7f0f0f0f0elemf1 = append(f7f0f0f0f0elemf1, svcsdktypes.RestApiMethod(f7f0f0f0f0elemf1elem))
								}
								f7f0f0f0f0elem.Methods = f7f0f0f0f0elemf1
							}
							f7f0f0f0f0 = append(f7f0f0f0f0, *f7f0f0f0f0elem)
						}
						f7f0f0f0.ToolFilters = f7f0f0f0f0
					}
					if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides != nil {
						f7f0f0f0f1 := []svcsdktypes.ApiGatewayToolOverride{}
						for _, f7f0f0f0f1iter := range r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides {
							f7f0f0f0f1elem := &svcsdktypes.ApiGatewayToolOverride{}
							if f7f0f0f0f1iter.Description != nil {
								f7f0f0f0f1elem.Description = f7f0f0f0f1iter.Description
							}
							if f7f0f0f0f1iter.Method != nil {
								f7f0f0f0f1elem.Method = svcsdktypes.RestApiMethod(*f7f0f0f0f1iter.Method)
							}
							if f7f0f0f0f1iter.Name != nil {
								f7f0f0f0f1elem.Name = f7f0f0f0f1iter.Name
							}
							if f7f0f0f0f1iter.Path != nil {
								f7f0f0f0f1elem.Path = f7f0f0f0f1iter.Path
							}
							f7f0f0f0f1 = append(f7f0f0f0f1, *f7f0f0f0f1elem)
						}
						f7f0f0f0.ToolOverrides = f7f0f0f0f1
					}
					f7f0f0.ApiGatewayToolConfiguration = f7f0f0f0
				}
				if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID != nil {
					f7f0f0.RestApiId = r.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID
				}
				if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage != nil {
					f7f0f0.Stage = r.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage
				}
				f7f0f0Parent.Value = *f7f0f0
				f7f0 = f7f0f0Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.Lambda != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Lambda"))
				}
				f7f0f1Parent := &svcsdktypes.McpTargetConfigurationMemberLambda{}
				f7f0f1 := &svcsdktypes.McpLambdaTargetConfiguration{}
				if r.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN != nil {
					f7f0f1.LambdaArn = r.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN
				}
				if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema != nil {
					var f7f0f1f1 svcsdktypes.ToolSchema
					isInterfaceSet := false
					if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for InlinePayload"))
						}
						f7f0f1f1f0Parent := &svcsdktypes.ToolSchemaMemberInlinePayload{}
						f7f0f1f1f0 := []svcsdktypes.ToolDefinition{}
						for _, f7f0f1f1f0iter := range r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload {
							f7f0f1f1f0elem := &svcsdktypes.ToolDefinition{}
							if f7f0f1f1f0iter.Description != nil {
								f7f0f1f1f0elem.Description = f7f0f1f1f0iter.Description
							}
							if f7f0f1f1f0iter.Name != nil {
								f7f0f1f1f0elem.Name = f7f0f1f1f0iter.Name
							}
							f7f0f1f1f0 = append(f7f0f1f1f0, *f7f0f1f1f0elem)
						}
						f7f0f1f1f0Parent.Value = f7f0f1f1f0
						f7f0f1f1 = f7f0f1f1f0Parent
						isInterfaceSet = true
					}
					if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3 != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
						}
						f7f0f1f1f1Parent := &svcsdktypes.ToolSchemaMemberS3{}
						f7f0f1f1f1 := &svcsdktypes.S3Configuration{}
						if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID != nil {
							f7f0f1f1f1.BucketOwnerAccountId = r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID
						}
						if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI != nil {
							f7f0f1f1f1.Uri = r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI
						}
						f7f0f1f1f1Parent.Value = *f7f0f1f1f1
						f7f0f1f1 = f7f0f1f1f1Parent
						isInterfaceSet = true
					}
					f7f0f1.ToolSchema = f7f0f1f1
				}
				f7f0f1Parent.Value = *f7f0f1
				f7f0 = f7f0f1Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.McpServer != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for McpServer"))
				}
				f7f0f2Parent := &svcsdktypes.McpTargetConfigurationMemberMcpServer{}
				f7f0f2 := &svcsdktypes.McpServerTargetConfiguration{}
				if r.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint != nil {
					f7f0f2.Endpoint = r.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint
				}
				f7f0f2Parent.Value = *f7f0f2
				f7f0 = f7f0f2Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for OpenApiSchema"))
				}
				f7f0f3Parent := &svcsdktypes.McpTargetConfigurationMemberOpenApiSchema{}
				var f7f0f3 svcsdktypes.ApiSchemaConfiguration
				isInterfaceSet := false
				if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for InlinePayload"))
					}
					f7f0f3f0Parent := &svcsdktypes.ApiSchemaConfigurationMemberInlinePayload{}
					f7f0f3f0Parent.Value = *r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload
					f7f0f3 = f7f0f3f0Parent
					isInterfaceSet = true
				}
				if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3 != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
					}
					f7f0f3f1Parent := &svcsdktypes.ApiSchemaConfigurationMemberS3{}
					f7f0f3f1 := &svcsdktypes.S3Configuration{}
					if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID != nil {
						f7f0f3f1.BucketOwnerAccountId = r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID
					}
					if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI != nil {
						f7f0f3f1.Uri = r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI
					}
					f7f0f3f1Parent.Value = *f7f0f3f1
					f7f0f3 = f7f0f3f1Parent
					isInterfaceSet = true
				}
				f7f0f3Parent.Value = f7f0f3
				f7f0 = f7f0f3Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SmithyModel"))
				}
				f7f0f4Parent := &svcsdktypes.McpTargetConfigurationMemberSmithyModel{}
				var f7f0f4 svcsdktypes.ApiSchemaConfiguration
				isInterfaceSet := false
				if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for InlinePayload"))
					}
					f7f0f4f0Parent := &svcsdktypes.ApiSchemaConfigurationMemberInlinePayload{}
					f7f0f4f0Parent.Value = *r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload
					f7f0f4 = f7f0f4f0Parent
					isInterfaceSet = true
				}
				if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3 != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
					}
					f7f0f4f1Parent := &svcsdktypes.ApiSchemaConfigurationMemberS3{}
					f7f0f4f1 := &svcsdktypes.S3Configuration{}
					if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID != nil {
						f7f0f4f1.BucketOwnerAccountId = r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID
					}
					if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI != nil {
						f7f0f4f1.Uri = r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI
					}
					f7f0f4f1Parent.Value = *f7f0f4f1
					f7f0f4 = f7f0f4f1Parent
					isInterfaceSet = true
				}
				f7f0f4Parent.Value = f7f0f4
				f7f0 = f7f0f4Parent
				isInterfaceSet = true
			}
			f7f0Parent.Value = f7f0
			f7 = f7f0Parent
			isInterfaceSet = true
		}
		res.TargetConfiguration = f7
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	if err := setSchemaDefinitionsOnUpdateInput(desired, input); err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateGatewayTargetOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateGatewayTarget(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateGatewayTarget", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CredentialProviderConfigurations != nil {
		f1 := []*svcapitypes.CredentialProviderConfiguration{}
		for _, f1iter := range resp.CredentialProviderConfigurations {
			f1elem := &svcapitypes.CredentialProviderConfiguration{}
			if f1iter.CredentialProvider != nil {
				f1elemf0 := &svcapitypes.CredentialProvider{}
				switch f1iter.CredentialProvider.(type) {
				case *svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider:
					f1elemf0f0 := f1iter.CredentialProvider.(*svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider)
					if f1elemf0f0 != nil {
						f1elemf0f0f0 := &svcapitypes.GatewayAPIKeyCredentialProvider{}
						if f1elemf0f0.Value.CredentialLocation != "" {
							f1elemf0f0f0.CredentialLocation = aws.String(string(f1elemf0f0.Value.CredentialLocation))
						}
						if f1elemf0f0.Value.CredentialParameterName != nil {
							f1elemf0f0f0.CredentialParameterName = f1elemf0f0.Value.CredentialParameterName
						}
						if f1elemf0f0.Value.CredentialPrefix != nil {
							f1elemf0f0f0.CredentialPrefix = f1elemf0f0.Value.CredentialPrefix
						}
						if f1elemf0f0.Value.ProviderArn != nil {
							f1elemf0f0f0.ProviderARN = f1elemf0f0.Value.ProviderArn
						}
						f1elemf0.APIKeyCredentialProvider = f1elemf0f0f0
					}
				case *svcsdktypes.CredentialProviderMemberOauthCredentialProvider:
					f1elemf0f1 := f1iter.CredentialProvider.(*svcsdktypes.CredentialProviderMemberOauthCredentialProvider)
					if f1elemf0f1 != nil {
						f1elemf0f1f1 := &svcapitypes.OAuthCredentialProvider{}
						if f1elemf0f1.Value.CustomParameters != nil {
							f1elemf0f1f1.CustomParameters = aws.StringMap(f1elemf0f1.Value.CustomParameters)
						}
						if f1elemf0f1.Value.DefaultReturnUrl != nil {
							f1elemf0f1f1.DefaultReturnURL = f1elemf0f1.Value.DefaultReturnUrl
						}
						if f1elemf0f1.Value.GrantType != "" {
							f1elemf0f1f1.GrantType = aws.String(string(f1elemf0f1.Value.GrantType))
						}
						if f1elemf0f1.Value.ProviderArn != nil {
							f1elemf0f1f1.ProviderARN = f1elemf0f1.Value.ProviderArn
						}
						if f1elemf0f1.Value.Scopes != nil {
							f1elemf0f1f1.Scopes = aws.StringSlice(f1elemf0f1.Value.Scopes)
						}
						f1elemf0.OauthCredentialProvider = f1elemf0f1f1
					}
				}
				f1elem.CredentialProvider = f1elemf0
			}
			if f1iter.CredentialProviderType != "" {
				f1elem.CredentialProviderType = aws.String(string(f1iter.CredentialProviderType))
			}
			f1 = append(f1, f1elem)
		}
		ko.Spec.CredentialProviderConfigurations = f1
	} else {
		ko.Spec.CredentialProviderConfigurations = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.GatewayArn != nil {
		ko.Status.GatewayARN = resp.GatewayArn
	} else {
		ko.Status.GatewayARN = nil
	}
	if resp.LastSynchronizedAt != nil {
		ko.Status.LastSynchronizedAt = &metav1.Time{*resp.LastSynchronizedAt}
	} else {
		ko.Status.LastSynchronizedAt = nil
	}
	if resp.MetadataConfiguration != nil {
		f5 := &svcapitypes.MetadataConfiguration{}
		if resp.MetadataConfiguration.AllowedQueryParameters != nil {
			f5.AllowedQueryParameters = aws.StringSlice(resp.MetadataConfiguration.AllowedQueryParameters)
		}
		if resp.MetadataConfiguration.AllowedRequestHeaders != nil {
			f5.AllowedRequestHeaders = aws.StringSlice(resp.MetadataConfiguration.AllowedRequestHeaders)
		}
		if resp.MetadataConfiguration.AllowedResponseHeaders != nil {
			f5.AllowedResponseHeaders = aws.StringSlice(resp.MetadataConfiguration.AllowedResponseHeaders)
		}
		ko.Spec.MetadataConfiguration = f5
	} else {
		ko.Spec.MetadataConfiguration = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.PrivateEndpoint != nil {
		f7 := &svcapitypes.PrivateEndpoint{}
		switch resp.PrivateEndpoint.(type) {
		case *svcsdktypes.PrivateEndpointMemberManagedVpcResource:
			f7f0 := resp.PrivateEndpoint.(*svcsdktypes.PrivateEndpointMemberManagedVpcResource)
			if f7f0 != nil {
				f7f0f0 := &svcapitypes.ManagedVPCResource{}
				if f7f0.Value.EndpointIpAddressType != "" {
					f7f0f0.EndpointIPAddressType = aws.String(string(f7f0.Value.EndpointIpAddressType))
				}
				if f7f0.Value.RoutingDomain != nil {
					f7f0f0.RoutingDomain = f7f0.Value.RoutingDomain
				}
				if f7f0.Value.SecurityGroupIds != nil {
					f7f0f0.SecurityGroupIDs = aws.StringSlice(f7f0.Value.SecurityGroupIds)
				}
				if f7f0.Value.SubnetIds != nil {
					f7f0f0.SubnetIDs = aws.StringSlice(f7f0.Value.SubnetIds)
				}
				if f7f0.Value.Tags != nil {
					f7f0f0.Tags = aws.StringMap(f7f0.Value.Tags)
				}
				if f7f0.Value.VpcIdentifier != nil {
					f7f0f0.VPCIdentifier = f7f0.Value.VpcIdentifier
				}
				f7.ManagedVPCResource = f7f0f0
			}
		case *svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource:
			f7f1 := resp.PrivateEndpoint.(*svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource)
			if f7f1 != nil {
				f7f1f1 := &svcapitypes.SelfManagedLatticeResource{}
				switch f7f1.Value.(type) {
				case *svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier:
					f7f1f1f0 := f7f1.Value.(*svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier)
					if f7f1f1f0 != nil {
						f7f1f1.ResourceConfigurationIdentifier = &f7f1f1f0.Value
					}
				}
				f7.SelfManagedLatticeResource = f7f1f1
			}
		}
		ko.Spec.PrivateEndpoint = f7
	} else {
		ko.Spec.PrivateEndpoint = nil
	}
	if resp.PrivateEndpointManagedResources != nil {
		f8 := []*svcapitypes.ManagedResourceDetails{}
		for _, f8iter := range resp.PrivateEndpointManagedResources {
			f8elem := &svcapitypes.ManagedResourceDetails{}
			if f8iter.Domain != nil {
				f8elem.Domain = f8iter.Domain
			}
			if f8iter.ResourceAssociationArn != nil {
				f8elem.ResourceAssociationARN = f8iter.ResourceAssociationArn
			}
			if f8iter.ResourceGatewayArn != nil {
				f8elem.ResourceGatewayARN = f8iter.ResourceGatewayArn
			}
			f8 = append(f8, f8elem)
		}
		ko.Status.PrivateEndpointManagedResources = f8
	} else {
		ko.Status.PrivateEndpointManagedResources = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.StatusReasons != nil {
		ko.Status.StatusReasons = aws.StringSlice(resp.StatusReasons)
	} else {
		ko.Status.StatusReasons = nil
	}
	if resp.TargetConfiguration != nil {
		f11 := &svcapitypes.TargetConfiguration{}
		switch resp.TargetConfiguration.(type) {
		case *svcsdktypes.TargetConfigurationMemberMcp:
			f11f0 := resp.TargetConfiguration.(*svcsdktypes.TargetConfigurationMemberMcp)
			if f11f0 != nil {
				f11f0f0 := &svcapitypes.McpTargetConfiguration{}
				switch f11f0.Value.(type) {
				case *svcsdktypes.McpTargetConfigurationMemberApiGateway:
					f11f0f0f0 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberApiGateway)
					if f11f0f0f0 != nil {
						f11f0f0f0f0 := &svcapitypes.APIGatewayTargetConfiguration{}
						if f11f0f0f0.Value.ApiGatewayToolConfiguration != nil {
							f11f0f0f0f0f0 := &svcapitypes.APIGatewayToolConfiguration{}
							if f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolFilters != nil {
								f11f0f0f0f0f0f0 := []*svcapitypes.APIGatewayToolFilter{}
								for _, f11f0f0f0f0f0f0iter := range f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolFilters {
									f11f0f0f0f0f0f0elem := &svcapitypes.APIGatewayToolFilter{}
									if f11f0f0f0f0f0f0iter.FilterPath != nil {
										f11f0f0f0f0f0f0elem.FilterPath = f11f0f0f0f0f0f0iter.FilterPath
									}
									if f11f0f0f0f0f0f0iter.Methods != nil {
										f11f0f0f0f0f0f0elemf1 := []*string{}
										for _, f11f0f0f0f0f0f0elemf1iter := range f11f0f0f0f0f0f0iter.Methods {
											var f11f0f0f0f0f0f0elemf1elem *string
											f11f0f0f0f0f0f0elemf1elem = aws.String(string(f11f0f0f0f0f0f0elemf1iter))
											f11f0f0f0f0f0f0elemf1 = append(f11f0f0f0f0f0f0elemf1, f11f0f0f0f0f0f0elemf1elem)
										}
										f11f0f0f0f0f0f0elem.Methods = f11f0f0f0f0f0f0elemf1
									}
									f11f0f0f0f0f0f0 = append(f11f0f0f0f0f0f0, f11f0f0f0f0f0f0elem)
								}
								f11f0f0f0f0f0.ToolFilters = f11f0f0f0f0f0f0
							}
							if f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolOverrides != nil {
								f11f0f0f0f0f0f1 := []*svcapitypes.APIGatewayToolOverride{}
								for _, f11f0f0f0f0f0f1iter := range f11f0f0f0.Value.ApiGatewayToolConfiguration.ToolOverrides {
									f11f0f0f0f0f0f1elem := &svcapitypes.APIGatewayToolOverride{}
									if f11f0f0f0f0f0f1iter.Description != nil {
										f11f0f0f0f0f0f1elem.Description = f11f0f0f0f0f0f1iter.Description
									}
									if f11f0f0f0f0f0f1iter.Method != "" {
										f11f0f0f0f0f0f1elem.Method = aws.String(string(f11f0f0f0f0f0f1iter.Method))
									}
									if f11f0f0f0f0f0f1iter.Name != nil {
										f11f0f0f0f0f0f1elem.Name = f11f0f0f0f0f0f1iter.Name
									}
									if f11f0f0f0f0f0f1iter.Path != nil {
										f11f0f0f0f0f0f1elem.Path = f11f0f0f0f0f0f1iter.Path
									}
									f11f0f0f0f0f0f1 = append(f11f0f0f0f0f0f1, f11f0f0f0f0f0f1elem)
								}
								f11f0f0f0f0f0.ToolOverrides = f11f0f0f0f0f0f1
							}
							f11f0f0f0f0.APIGatewayToolConfiguration = f11f0f0f0f0f0
						}
						if f11f0f0f0.Value.RestApiId != nil {
							f11f0f0f0f0.RestAPIID = f11f0f0f0.Value.RestApiId
						}
						if f11f0f0f0.Value.Stage != nil {
							f11f0f0f0f0.Stage = f11f0f0f0.Value.Stage
						}
						f11f0f0.APIGateway = f11f0f0f0f0
					}
				case *svcsdktypes.McpTargetConfigurationMemberLambda:
					f11f0f0f1 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberLambda)
					if f11f0f0f1 != nil {
						f11f0f0f1f1 := &svcapitypes.McpLambdaTargetConfiguration{}
						if f11f0f0f1.Value.LambdaArn != nil {
							f11f0f0f1f1.LambdaARN = f11f0f0f1.Value.LambdaArn
						}
						if f11f0f0f1.Value.ToolSchema != nil {
							f11f0f0f1f1f1 := &svcapitypes.ToolSchema{}
							switch f11f0f0f1.Value.ToolSchema.(type) {
							case *svcsdktypes.ToolSchemaMemberS3:
								f11f0f0f1f1f1f1 := f11f0f0f1.Value.ToolSchema.(*svcsdktypes.ToolSchemaMemberS3)
								if f11f0f0f1f1f1f1 != nil {
									f11f0f0f1f1f1f1f1 := &svcapitypes.S3Configuration{}
									if f11f0f0f1f1f1f1.Value.BucketOwnerAccountId != nil {
										f11f0f0f1f1f1f1f1.BucketOwnerAccountID = f11f0f0f1f1f1f1.Value.BucketOwnerAccountId
									}
									if f11f0f0f1f1f1f1.Value.Uri != nil {
										f11f0f0f1f1f1f1f1.URI = f11f0f0f1f1f1f1.Value.Uri
									}
									f11f0f0f1f1f1.S3 = f11f0f0f1f1f1f1f1
								}
							}
							f11f0f0f1f1.ToolSchema = f11f0f0f1f1f1
						}
						f11f0f0.Lambda = f11f0f0f1f1
					}
				case *svcsdktypes.McpTargetConfigurationMemberMcpServer:
					f11f0f0f2 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberMcpServer)
					if f11f0f0f2 != nil {
						f11f0f0f2f2 := &svcapitypes.McpServerTargetConfiguration{}
						if f11f0f0f2.Value.Endpoint != nil {
							f11f0f0f2f2.Endpoint = f11f0f0f2.Value.Endpoint
						}
						f11f0f0.McpServer = f11f0f0f2f2
					}
				case *svcsdktypes.McpTargetConfigurationMemberOpenApiSchema:
					f11f0f0f3 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberOpenApiSchema)
					if f11f0f0f3 != nil {
						f11f0f0f3f3 := &svcapitypes.APISchemaConfiguration{}
						switch f11f0f0f3.Value.(type) {
						case *svcsdktypes.ApiSchemaConfigurationMemberInlinePayload:
							f11f0f0f3f3f0 := f11f0f0f3.Value.(*svcsdktypes.ApiSchemaConfigurationMemberInlinePayload)
							if f11f0f0f3f3f0 != nil {
								f11f0f0f3f3.InlinePayload = &f11f0f0f3f3f0.Value
							}
						case *svcsdktypes.ApiSchemaConfigurationMemberS3:
							f11f0f0f3f3f1 := f11f0f0f3.Value.(*svcsdktypes.ApiSchemaConfigurationMemberS3)
							if f11f0f0f3f3f1 != nil {
								f11f0f0f3f3f1f1 := &svcapitypes.S3Configuration{}
								if f11f0f0f3f3f1.Value.BucketOwnerAccountId != nil {
									f11f0f0f3f3f1f1.BucketOwnerAccountID = f11f0f0f3f3f1.Value.BucketOwnerAccountId
								}
								if f11f0f0f3f3f1.Value.Uri != nil {
									f11f0f0f3f3f1f1.URI = f11f0f0f3f3f1.Value.Uri
								}
								f11f0f0f3f3.S3 = f11f0f0f3f3f1f1
							}
						}
						f11f0f0.OpenAPISchema = f11f0f0f3f3
					}
				case *svcsdktypes.McpTargetConfigurationMemberSmithyModel:
					f11f0f0f4 := f11f0.Value.(*svcsdktypes.McpTargetConfigurationMemberSmithyModel)
					if f11f0f0f4 != nil {
						f11f0f0f4f4 := &svcapitypes.APISchemaConfiguration{}
						switch f11f0f0f4.Value.(type) {
						case *svcsdktypes.ApiSchemaConfigurationMemberInlinePayload:
							f11f0f0f4f4f0 := f11f0f0f4.Value.(*svcsdktypes.ApiSchemaConfigurationMemberInlinePayload)
							if f11f0f0f4f4f0 != nil {
								f11f0f0f4f4.InlinePayload = &f11f0f0f4f4f0.Value
							}
						case *svcsdktypes.ApiSchemaConfigurationMemberS3:
							f11f0f0f4f4f1 := f11f0f0f4.Value.(*svcsdktypes.ApiSchemaConfigurationMemberS3)
							if f11f0f0f4f4f1 != nil {
								f11f0f0f4f4f1f1 := &svcapitypes.S3Configuration{}
								if f11f0f0f4f4f1.Value.BucketOwnerAccountId != nil {
									f11f0f0f4f4f1f1.BucketOwnerAccountID = f11f0f0f4f4f1.Value.BucketOwnerAccountId
								}
								if f11f0f0f4f4f1.Value.Uri != nil {
									f11f0f0f4f4f1f1.URI = f11f0f0f4f4f1.Value.Uri
								}
								f11f0f0f4f4.S3 = f11f0f0f4f4f1f1
							}
						}
						f11f0f0.SmithyModel = f11f0f0f4f4
					}
				}
				f11.Mcp = f11f0f0
			}
		}
		ko.Spec.TargetConfiguration = f11
	} else {
		ko.Spec.TargetConfiguration = nil
	}
	if resp.TargetId != nil {
		ko.Status.TargetID = resp.TargetId
	} else {
		ko.Status.TargetID = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	if desired.ko.Spec.TargetConfiguration != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp.Lambda != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema != nil &&
		desired.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload != nil {
		ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload = desired.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload
	}
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateGatewayTargetInput, error) {
	res := &svcsdk.UpdateGatewayTargetInput{}

	if r.ko.Spec.CredentialProviderConfigurations != nil {
		f0 := []svcsdktypes.CredentialProviderConfiguration{}
		for _, f0iter := range r.ko.Spec.CredentialProviderConfigurations {
			f0elem := &svcsdktypes.CredentialProviderConfiguration{}
			if f0iter.CredentialProvider != nil {
				var f0elemf0 svcsdktypes.CredentialProvider
				isInterfaceSet := false
				if f0iter.CredentialProvider.APIKeyCredentialProvider != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ApiKeyCredentialProvider"))
					}
					f0elemf0f0Parent := &svcsdktypes.CredentialProviderMemberApiKeyCredentialProvider{}
					f0elemf0f0 := &svcsdktypes.GatewayApiKeyCredentialProvider{}
					if f0iter.CredentialProvider.APIKeyCredentialProvider.CredentialLocation != nil {
						f0elemf0f0.CredentialLocation = svcsdktypes.ApiKeyCredentialLocation(*f0iter.CredentialProvider.APIKeyCredentialProvider.CredentialLocation)
					}
					if f0iter.CredentialProvider.APIKeyCredentialProvider.CredentialParameterName != nil {
						f0elemf0f0.CredentialParameterName = f0iter.CredentialProvider.APIKeyCredentialProvider.CredentialParameterName
					}
					if f0iter.CredentialProvider.APIKeyCredentialProvider.CredentialPrefix != nil {
						f0elemf0f0.CredentialPrefix = f0iter.CredentialProvider.APIKeyCredentialProvider.CredentialPrefix
					}
					if f0iter.CredentialProvider.APIKeyCredentialProvider.ProviderARN != nil {
						f0elemf0f0.ProviderArn = f0iter.CredentialProvider.APIKeyCredentialProvider.ProviderARN
					}
					f0elemf0f0Parent.Value = *f0elemf0f0
					f0elemf0 = f0elemf0f0Parent
					isInterfaceSet = true
				}
				if f0iter.CredentialProvider.OauthCredentialProvider != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for OauthCredentialProvider"))
					}
					f0elemf0f1Parent := &svcsdktypes.CredentialProviderMemberOauthCredentialProvider{}
					f0elemf0f1 := &svcsdktypes.OAuthCredentialProvider{}
					if f0iter.CredentialProvider.OauthCredentialProvider.CustomParameters != nil {
						f0elemf0f1.CustomParameters = aws.ToStringMap(f0iter.CredentialProvider.OauthCredentialProvider.CustomParameters)
					}
					if f0iter.CredentialProvider.OauthCredentialProvider.DefaultReturnURL != nil {
						f0elemf0f1.DefaultReturnUrl = f0iter.CredentialProvider.OauthCredentialProvider.DefaultReturnURL
					}
					if f0iter.CredentialProvider.OauthCredentialProvider.GrantType != nil {
						f0elemf0f1.GrantType = svcsdktypes.OAuthGrantType(*f0iter.CredentialProvider.OauthCredentialProvider.GrantType)
					}
					if f0iter.CredentialProvider.OauthCredentialProvider.ProviderARN != nil {
						f0elemf0f1.ProviderArn = f0iter.CredentialProvider.OauthCredentialProvider.ProviderARN
					}
					if f0iter.CredentialProvider.OauthCredentialProvider.Scopes != nil {
						f0elemf0f1.Scopes = aws.ToStringSlice(f0iter.CredentialProvider.OauthCredentialProvider.Scopes)
					}
					f0elemf0f1Parent.Value = *f0elemf0f1
					f0elemf0 = f0elemf0f1Parent
					isInterfaceSet = true
				}
				f0elem.CredentialProvider = f0elemf0
			}
			if f0iter.CredentialProviderType != nil {
				f0elem.CredentialProviderType = svcsdktypes.CredentialProviderType(*f0iter.CredentialProviderType)
			}
			f0 = append(f0, *f0elem)
		}
		res.CredentialProviderConfigurations = f0
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Spec.MetadataConfiguration != nil {
		f3 := &svcsdktypes.MetadataConfiguration{}
		if r.ko.Spec.MetadataConfiguration.AllowedQueryParameters != nil {
			f3.AllowedQueryParameters = aws.ToStringSlice(r.ko.Spec.MetadataConfiguration.AllowedQueryParameters)
		}
		if r.ko.Spec.MetadataConfiguration.AllowedRequestHeaders != nil {
			f3.AllowedRequestHeaders = aws.ToStringSlice(r.ko.Spec.MetadataConfiguration.AllowedRequestHeaders)
		}
		if r.ko.Spec.MetadataConfiguration.AllowedResponseHeaders != nil {
			f3.AllowedResponseHeaders = aws.ToStringSlice(r.ko.Spec.MetadataConfiguration.AllowedResponseHeaders)
		}
		res.MetadataConfiguration = f3
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.PrivateEndpoint != nil {
		var f5 svcsdktypes.PrivateEndpoint
		isInterfaceSet := false
		if r.ko.Spec.PrivateEndpoint.ManagedVPCResource != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ManagedVpcResource"))
			}
			f5f0Parent := &svcsdktypes.PrivateEndpointMemberManagedVpcResource{}
			f5f0 := &svcsdktypes.ManagedVpcResource{}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.EndpointIPAddressType != nil {
				f5f0.EndpointIpAddressType = svcsdktypes.EndpointIpAddressType(*r.ko.Spec.PrivateEndpoint.ManagedVPCResource.EndpointIPAddressType)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.RoutingDomain != nil {
				f5f0.RoutingDomain = r.ko.Spec.PrivateEndpoint.ManagedVPCResource.RoutingDomain
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SecurityGroupIDs != nil {
				f5f0.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SecurityGroupIDs)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SubnetIDs != nil {
				f5f0.SubnetIds = aws.ToStringSlice(r.ko.Spec.PrivateEndpoint.ManagedVPCResource.SubnetIDs)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.Tags != nil {
				f5f0.Tags = aws.ToStringMap(r.ko.Spec.PrivateEndpoint.ManagedVPCResource.Tags)
			}
			if r.ko.Spec.PrivateEndpoint.ManagedVPCResource.VPCIdentifier != nil {
				f5f0.VpcIdentifier = r.ko.Spec.PrivateEndpoint.ManagedVPCResource.VPCIdentifier
			}
			f5f0Parent.Value = *f5f0
			f5 = f5f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.PrivateEndpoint.SelfManagedLatticeResource != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SelfManagedLatticeResource"))
			}
			f5f1Parent := &svcsdktypes.PrivateEndpointMemberSelfManagedLatticeResource{}
			var f5f1 svcsdktypes.SelfManagedLatticeResource
			isInterfaceSet := false
			if r.ko.Spec.PrivateEndpoint.SelfManagedLatticeResource.ResourceConfigurationIdentifier != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ResourceConfigurationIdentifier"))
				}
				f5f1f0Parent := &svcsdktypes.SelfManagedLatticeResourceMemberResourceConfigurationIdentifier{}
				f5f1f0Parent.Value = *r.ko.Spec.PrivateEndpoint.SelfManagedLatticeResource.ResourceConfigurationIdentifier
				f5f1 = f5f1f0Parent
				isInterfaceSet = true
			}
			f5f1Parent.Value = f5f1
			f5 = f5f1Parent
			isInterfaceSet = true
		}
		res.PrivateEndpoint = f5
	}
	if r.ko.Spec.TargetConfiguration != nil {
		var f6 svcsdktypes.TargetConfiguration
		isInterfaceSet := false
		if r.ko.Spec.TargetConfiguration.Mcp != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Mcp"))
			}
			f6f0Parent := &svcsdktypes.TargetConfigurationMemberMcp{}
			var f6f0 svcsdktypes.McpTargetConfiguration
			isInterfaceSet := false
			if r.ko.Spec.TargetConfiguration.Mcp.APIGateway != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ApiGateway"))
				}
				f6f0f0Parent := &svcsdktypes.McpTargetConfigurationMemberApiGateway{}
				f6f0f0 := &svcsdktypes.ApiGatewayTargetConfiguration{}
				if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration != nil {
					f6f0f0f0 := &svcsdktypes.ApiGatewayToolConfiguration{}
					if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters != nil {
						f6f0f0f0f0 := []svcsdktypes.ApiGatewayToolFilter{}
						for _, f6f0f0f0f0iter := range r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters {
							f6f0f0f0f0elem := &svcsdktypes.ApiGatewayToolFilter{}
							if f6f0f0f0f0iter.FilterPath != nil {
								f6f0f0f0f0elem.FilterPath = f6f0f0f0f0iter.FilterPath
							}
							if f6f0f0f0f0iter.Methods != nil {
								f6f0f0f0f0elemf1 := []svcsdktypes.RestApiMethod{}
								for _, f6f0f0f0f0elemf1iter := range f6f0f0f0f0iter.Methods {
									var f6f0f0f0f0elemf1elem string
									f6f0f0f0f0elemf1elem = string(*f6f0f0f0f0elemf1iter)
									f6f0f0f0f0elemf1 = append(f6f0f0f0f0elemf1, svcsdktypes.RestApiMethod(f6f0f0f0f0elemf1elem))
								}
								f6f0f0f0f0elem.Methods = f6f0f0f0f0elemf1
							}
							f6f0f0f0f0 = append(f6f0f0f0f0, *f6f0f0f0f0elem)
						}
						f6f0f0f0.ToolFilters = f6f0f0f0f0
					}
					if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides != nil {
						f6f0f0f0f1 := []svcsdktypes.ApiGatewayToolOverride{}
						for _, f6f0f0f0f1iter := range r.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides {
							f6f0f0f0f1elem := &svcsdktypes.ApiGatewayToolOverride{}
							if f6f0f0f0f1iter.Description != nil {
								f6f0f0f0f1elem.Description = f6f0f0f0f1iter.Description
							}
							if f6f0f0f0f1iter.Method != nil {
								f6f0f0f0f1elem.Method = svcsdktypes.RestApiMethod(*f6f0f0f0f1iter.Method)
							}
							if f6f0f0f0f1iter.Name != nil {
								f6f0f0f0f1elem.Name = f6f0f0f0f1iter.Name
							}
							if f6f0f0f0f1iter.Path != nil {
								f6f0f0f0f1elem.Path = f6f0f0f0f1iter.Path
							}
							f6f0f0f0f1 = append(f6f0f0f0f1, *f6f0f0f0f1elem)
						}
						f6f0f0f0.ToolOverrides = f6f0f0f0f1
					}
					f6f0f0.ApiGatewayToolConfiguration = f6f0f0f0
				}
				if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID != nil {
					f6f0f0.RestApiId = r.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID
				}
				if r.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage != nil {
					f6f0f0.Stage = r.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage
				}
				f6f0f0Parent.Value = *f6f0f0
				f6f0 = f6f0f0Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.Lambda != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Lambda"))
				}
				f6f0f1Parent := &svcsdktypes.McpTargetConfigurationMemberLambda{}
				f6f0f1 := &svcsdktypes.McpLambdaTargetConfiguration{}
				if r.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN != nil {
					f6f0f1.LambdaArn = r.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN
				}
				if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema != nil {
					var f6f0f1f1 svcsdktypes.ToolSchema
					isInterfaceSet := false
					if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for InlinePayload"))
						}
						f6f0f1f1f0Parent := &svcsdktypes.ToolSchemaMemberInlinePayload{}
						f6f0f1f1f0 := []svcsdktypes.ToolDefinition{}
						for _, f6f0f1f1f0iter := range r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload {
							f6f0f1f1f0elem := &svcsdktypes.ToolDefinition{}
							if f6f0f1f1f0iter.Description != nil {
								f6f0f1f1f0elem.Description = f6f0f1f1f0iter.Description
							}
							if f6f0f1f1f0iter.Name != nil {
								f6f0f1f1f0elem.Name = f6f0f1f1f0iter.Name
							}
							f6f0f1f1f0 = append(f6f0f1f1f0, *f6f0f1f1f0elem)
						}
						f6f0f1f1f0Parent.Value = f6f0f1f1f0
						f6f0f1f1 = f6f0f1f1f0Parent
						isInterfaceSet = true
					}
					if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3 != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
						}
						f6f0f1f1f1Parent := &svcsdktypes.ToolSchemaMemberS3{}
						f6f0f1f1f1 := &svcsdktypes.S3Configuration{}
						if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID != nil {
							f6f0f1f1f1.BucketOwnerAccountId = r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID
						}
						if r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI != nil {
							f6f0f1f1f1.Uri = r.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI
						}
						f6f0f1f1f1Parent.Value = *f6f0f1f1f1
						f6f0f1f1 = f6f0f1f1f1Parent
						isInterfaceSet = true
					}
					f6f0f1.ToolSchema = f6f0f1f1
				}
				f6f0f1Parent.Value = *f6f0f1
				f6f0 = f6f0f1Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.McpServer != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for McpServer"))
				}
				f6f0f2Parent := &svcsdktypes.McpTargetConfigurationMemberMcpServer{}
				f6f0f2 := &svcsdktypes.McpServerTargetConfiguration{}
				if r.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint != nil {
					f6f0f2.Endpoint = r.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint
				}
				f6f0f2Parent.Value = *f6f0f2
				f6f0 = f6f0f2Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for OpenApiSchema"))
				}
				f6f0f3Parent := &svcsdktypes.McpTargetConfigurationMemberOpenApiSchema{}
				var f6f0f3 svcsdktypes.ApiSchemaConfiguration
				isInterfaceSet := false
				if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for InlinePayload"))
					}
					f6f0f3f0Parent := &svcsdktypes.ApiSchemaConfigurationMemberInlinePayload{}
					f6f0f3f0Parent.Value = *r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload
					f6f0f3 = f6f0f3f0Parent
					isInterfaceSet = true
				}
				if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3 != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
					}
					f6f0f3f1Parent := &svcsdktypes.ApiSchemaConfigurationMemberS3{}
					f6f0f3f1 := &svcsdktypes.S3Configuration{}
					if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID != nil {
						f6f0f3f1.BucketOwnerAccountId = r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID
					}
					if r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI != nil {
						f6f0f3f1.Uri = r.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI
					}
					f6f0f3f1Parent.Value = *f6f0f3f1
					f6f0f3 = f6f0f3f1Parent
					isInterfaceSet = true
				}
				f6f0f3Parent.Value = f6f0f3
				f6f0 = f6f0f3Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SmithyModel"))
				}
				f6f0f4Parent := &svcsdktypes.McpTargetConfigurationMemberSmithyModel{}
				var f6f0f4 svcsdktypes.ApiSchemaConfiguration
				isInterfaceSet := false
				if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for InlinePayload"))
					}
					f6f0f4f0Parent := &svcsdktypes.ApiSchemaConfigurationMemberInlinePayload{}
					f6f0f4f0Parent.Value = *r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload
					f6f0f4 = f6f0f4f0Parent
					isInterfaceSet = true
				}
				if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3 != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
					}
					f6f0f4f1Parent := &svcsdktypes.ApiSchemaConfigurationMemberS3{}
					f6f0f4f1 := &svcsdktypes.S3Configuration{}
					if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID != nil {
						f6f0f4f1.BucketOwnerAccountId = r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID
					}
					if r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI != nil {
						f6f0f4f1.Uri = r.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI
					}
					f6f0f4f1Parent.Value = *f6f0f4f1
					f6f0f4 = f6f0f4f1Parent
					isInterfaceSet = true
				}
				f6f0f4Parent.Value = f6f0f4
				f6f0 = f6f0f4Parent
				isInterfaceSet = true
			}
			f6f0Parent.Value = f6f0
			f6 = f6f0Parent
			isInterfaceSet = true
		}
		res.TargetConfiguration = f6
	}
	if r.ko.Status.TargetID != nil {
		res.TargetId = r.ko.Status.TargetID
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteGatewayTargetOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteGatewayTarget(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteGatewayTarget", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteGatewayTargetInput, error) {
	res := &svcsdk.DeleteGatewayTargetInput{}

	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Status.TargetID != nil {
		res.TargetId = r.ko.Status.TargetID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.GatewayTarget,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
