// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package gateway_rate_limit

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	ackutil "github.com/aws-controllers-k8s/runtime/pkg/util"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/bedrockagentcorecontrol-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.GatewayRateLimit{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetGatewayRateLimitOutput
	resp, err = rm.sdkapi.GetGatewayRateLimit(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetGatewayRateLimit", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.DimensionKeys != nil {
		ko.Spec.DimensionKeys = aws.StringSlice(resp.DimensionKeys)
	} else {
		ko.Spec.DimensionKeys = nil
	}
	if resp.Entries != nil {
		f3 := []*svcapitypes.LimitEntry{}
		for _, f3iter := range resp.Entries {
			f3elem := &svcapitypes.LimitEntry{}
			if f3iter.Connections != nil {
				f3elemf0 := []*svcapitypes.RateConfig{}
				for _, f3elemf0iter := range f3iter.Connections {
					f3elemf0elem := &svcapitypes.RateConfig{}
					if f3elemf0iter.Period != "" {
						f3elemf0elem.Period = aws.String(string(f3elemf0iter.Period))
					}
					if f3elemf0iter.Rate != nil {
						f3elemf0elem.Rate = f3elemf0iter.Rate
					}
					f3elemf0 = append(f3elemf0, f3elemf0elem)
				}
				f3elem.Connections = f3elemf0
			}
			if f3iter.Dimensions != nil {
				f3elem.Dimensions = aws.StringMap(f3iter.Dimensions)
			}
			if f3iter.Requests != nil {
				f3elemf2 := []*svcapitypes.RateConfig{}
				for _, f3elemf2iter := range f3iter.Requests {
					f3elemf2elem := &svcapitypes.RateConfig{}
					if f3elemf2iter.Period != "" {
						f3elemf2elem.Period = aws.String(string(f3elemf2iter.Period))
					}
					if f3elemf2iter.Rate != nil {
						f3elemf2elem.Rate = f3elemf2iter.Rate
					}
					f3elemf2 = append(f3elemf2, f3elemf2elem)
				}
				f3elem.Requests = f3elemf2
			}
			if f3iter.Tokens != nil {
				f3elemf3 := []*svcapitypes.RateConfig{}
				for _, f3elemf3iter := range f3iter.Tokens {
					f3elemf3elem := &svcapitypes.RateConfig{}
					if f3elemf3iter.Period != "" {
						f3elemf3elem.Period = aws.String(string(f3elemf3iter.Period))
					}
					if f3elemf3iter.Rate != nil {
						f3elemf3elem.Rate = f3elemf3iter.Rate
					}
					f3elemf3 = append(f3elemf3, f3elemf3elem)
				}
				f3elem.Tokens = f3elemf3
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.Entries = f3
	} else {
		ko.Spec.Entries = nil
	}
	if resp.GatewayIdentifier != nil {
		ko.Spec.GatewayIdentifier = resp.GatewayIdentifier
	} else {
		ko.Spec.GatewayIdentifier = nil
	}
	if resp.RateLimitId != nil {
		ko.Spec.RateLimitID = resp.RateLimitId
	} else {
		ko.Spec.RateLimitID = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.GatewayIdentifier == nil || r.ko.Spec.RateLimitID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetGatewayRateLimitInput, error) {
	res := &svcsdk.GetGatewayRateLimitInput{}

	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Spec.RateLimitID != nil {
		res.RateLimitId = r.ko.Spec.RateLimitID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateGatewayRateLimitOutput
	_ = resp
	resp, err = rm.sdkapi.CreateGatewayRateLimit(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateGatewayRateLimit", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.DimensionKeys != nil {
		ko.Spec.DimensionKeys = aws.StringSlice(resp.DimensionKeys)
	} else {
		ko.Spec.DimensionKeys = nil
	}
	if resp.Entries != nil {
		f3 := []*svcapitypes.LimitEntry{}
		for _, f3iter := range resp.Entries {
			f3elem := &svcapitypes.LimitEntry{}
			if f3iter.Connections != nil {
				f3elemf0 := []*svcapitypes.RateConfig{}
				for _, f3elemf0iter := range f3iter.Connections {
					f3elemf0elem := &svcapitypes.RateConfig{}
					if f3elemf0iter.Period != "" {
						f3elemf0elem.Period = aws.String(string(f3elemf0iter.Period))
					}
					if f3elemf0iter.Rate != nil {
						f3elemf0elem.Rate = f3elemf0iter.Rate
					}
					f3elemf0 = append(f3elemf0, f3elemf0elem)
				}
				f3elem.Connections = f3elemf0
			}
			if f3iter.Dimensions != nil {
				f3elem.Dimensions = aws.StringMap(f3iter.Dimensions)
			}
			if f3iter.Requests != nil {
				f3elemf2 := []*svcapitypes.RateConfig{}
				for _, f3elemf2iter := range f3iter.Requests {
					f3elemf2elem := &svcapitypes.RateConfig{}
					if f3elemf2iter.Period != "" {
						f3elemf2elem.Period = aws.String(string(f3elemf2iter.Period))
					}
					if f3elemf2iter.Rate != nil {
						f3elemf2elem.Rate = f3elemf2iter.Rate
					}
					f3elemf2 = append(f3elemf2, f3elemf2elem)
				}
				f3elem.Requests = f3elemf2
			}
			if f3iter.Tokens != nil {
				f3elemf3 := []*svcapitypes.RateConfig{}
				for _, f3elemf3iter := range f3iter.Tokens {
					f3elemf3elem := &svcapitypes.RateConfig{}
					if f3elemf3iter.Period != "" {
						f3elemf3elem.Period = aws.String(string(f3elemf3iter.Period))
					}
					if f3elemf3iter.Rate != nil {
						f3elemf3elem.Rate = f3elemf3iter.Rate
					}
					f3elemf3 = append(f3elemf3, f3elemf3elem)
				}
				f3elem.Tokens = f3elemf3
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.Entries = f3
	} else {
		ko.Spec.Entries = nil
	}
	if resp.GatewayIdentifier != nil {
		ko.Spec.GatewayIdentifier = resp.GatewayIdentifier
	} else {
		ko.Spec.GatewayIdentifier = nil
	}
	if resp.RateLimitId != nil {
		ko.Spec.RateLimitID = resp.RateLimitId
	} else {
		ko.Spec.RateLimitID = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateGatewayRateLimitInput, error) {
	res := &svcsdk.CreateGatewayRateLimitInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.DimensionKeys != nil {
		res.DimensionKeys = aws.ToStringSlice(r.ko.Spec.DimensionKeys)
	}
	if r.ko.Spec.Entries != nil {
		f3 := []svcsdktypes.LimitEntry{}
		for _, f3iter := range r.ko.Spec.Entries {
			f3elem := &svcsdktypes.LimitEntry{}
			if f3iter.Connections != nil {
				f3elemf0 := []svcsdktypes.RateConfig{}
				for _, f3elemf0iter := range f3iter.Connections {
					f3elemf0elem := &svcsdktypes.RateConfig{}
					if f3elemf0iter.Period != nil {
						f3elemf0elem.Period = svcsdktypes.Period(*f3elemf0iter.Period)
					}
					if f3elemf0iter.Rate != nil {
						f3elemf0elem.Rate = f3elemf0iter.Rate
					}
					f3elemf0 = append(f3elemf0, *f3elemf0elem)
				}
				f3elem.Connections = f3elemf0
			}
			if f3iter.Dimensions != nil {
				f3elem.Dimensions = aws.ToStringMap(f3iter.Dimensions)
			}
			if f3iter.Requests != nil {
				f3elemf2 := []svcsdktypes.RateConfig{}
				for _, f3elemf2iter := range f3iter.Requests {
					f3elemf2elem := &svcsdktypes.RateConfig{}
					if f3elemf2iter.Period != nil {
						f3elemf2elem.Period = svcsdktypes.Period(*f3elemf2iter.Period)
					}
					if f3elemf2iter.Rate != nil {
						f3elemf2elem.Rate = f3elemf2iter.Rate
					}
					f3elemf2 = append(f3elemf2, *f3elemf2elem)
				}
				f3elem.Requests = f3elemf2
			}
			if f3iter.Tokens != nil {
				f3elemf3 := []svcsdktypes.RateConfig{}
				for _, f3elemf3iter := range f3iter.Tokens {
					f3elemf3elem := &svcsdktypes.RateConfig{}
					if f3elemf3iter.Period != nil {
						f3elemf3elem.Period = svcsdktypes.Period(*f3elemf3iter.Period)
					}
					if f3elemf3iter.Rate != nil {
						f3elemf3elem.Rate = f3elemf3iter.Rate
					}
					f3elemf3 = append(f3elemf3, *f3elemf3elem)
				}
				f3elem.Tokens = f3elemf3
			}
			f3 = append(f3, *f3elem)
		}
		res.Entries = f3
	}
	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Spec.RateLimitID != nil {
		res.RateLimitId = r.ko.Spec.RateLimitID
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if latest.ko.Status.Status != nil {
		if !ackutil.InStrings(*latest.ko.Status.Status, []string{"ACTIVE"}) {
			return nil, ackrequeue.NeededAfter(
				fmt.Errorf("resource is in %s state, cannot be updated",
					*latest.ko.Status.Status),
				time.Duration(30)*time.Second,
			)
		}
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateGatewayRateLimitOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateGatewayRateLimit(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateGatewayRateLimit", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.DimensionKeys != nil {
		ko.Spec.DimensionKeys = aws.StringSlice(resp.DimensionKeys)
	} else {
		ko.Spec.DimensionKeys = nil
	}
	if resp.Entries != nil {
		f3 := []*svcapitypes.LimitEntry{}
		for _, f3iter := range resp.Entries {
			f3elem := &svcapitypes.LimitEntry{}
			if f3iter.Connections != nil {
				f3elemf0 := []*svcapitypes.RateConfig{}
				for _, f3elemf0iter := range f3iter.Connections {
					f3elemf0elem := &svcapitypes.RateConfig{}
					if f3elemf0iter.Period != "" {
						f3elemf0elem.Period = aws.String(string(f3elemf0iter.Period))
					}
					if f3elemf0iter.Rate != nil {
						f3elemf0elem.Rate = f3elemf0iter.Rate
					}
					f3elemf0 = append(f3elemf0, f3elemf0elem)
				}
				f3elem.Connections = f3elemf0
			}
			if f3iter.Dimensions != nil {
				f3elem.Dimensions = aws.StringMap(f3iter.Dimensions)
			}
			if f3iter.Requests != nil {
				f3elemf2 := []*svcapitypes.RateConfig{}
				for _, f3elemf2iter := range f3iter.Requests {
					f3elemf2elem := &svcapitypes.RateConfig{}
					if f3elemf2iter.Period != "" {
						f3elemf2elem.Period = aws.String(string(f3elemf2iter.Period))
					}
					if f3elemf2iter.Rate != nil {
						f3elemf2elem.Rate = f3elemf2iter.Rate
					}
					f3elemf2 = append(f3elemf2, f3elemf2elem)
				}
				f3elem.Requests = f3elemf2
			}
			if f3iter.Tokens != nil {
				f3elemf3 := []*svcapitypes.RateConfig{}
				for _, f3elemf3iter := range f3iter.Tokens {
					f3elemf3elem := &svcapitypes.RateConfig{}
					if f3elemf3iter.Period != "" {
						f3elemf3elem.Period = aws.String(string(f3elemf3iter.Period))
					}
					if f3elemf3iter.Rate != nil {
						f3elemf3elem.Rate = f3elemf3iter.Rate
					}
					f3elemf3 = append(f3elemf3, f3elemf3elem)
				}
				f3elem.Tokens = f3elemf3
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.Entries = f3
	} else {
		ko.Spec.Entries = nil
	}
	if resp.GatewayIdentifier != nil {
		ko.Spec.GatewayIdentifier = resp.GatewayIdentifier
	} else {
		ko.Spec.GatewayIdentifier = nil
	}
	if resp.RateLimitId != nil {
		ko.Spec.RateLimitID = resp.RateLimitId
	} else {
		ko.Spec.RateLimitID = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateGatewayRateLimitInput, error) {
	res := &svcsdk.UpdateGatewayRateLimitInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.Entries != nil {
		f1 := []svcsdktypes.LimitEntry{}
		for _, f1iter := range r.ko.Spec.Entries {
			f1elem := &svcsdktypes.LimitEntry{}
			if f1iter.Connections != nil {
				f1elemf0 := []svcsdktypes.RateConfig{}
				for _, f1elemf0iter := range f1iter.Connections {
					f1elemf0elem := &svcsdktypes.RateConfig{}
					if f1elemf0iter.Period != nil {
						f1elemf0elem.Period = svcsdktypes.Period(*f1elemf0iter.Period)
					}
					if f1elemf0iter.Rate != nil {
						f1elemf0elem.Rate = f1elemf0iter.Rate
					}
					f1elemf0 = append(f1elemf0, *f1elemf0elem)
				}
				f1elem.Connections = f1elemf0
			}
			if f1iter.Dimensions != nil {
				f1elem.Dimensions = aws.ToStringMap(f1iter.Dimensions)
			}
			if f1iter.Requests != nil {
				f1elemf2 := []svcsdktypes.RateConfig{}
				for _, f1elemf2iter := range f1iter.Requests {
					f1elemf2elem := &svcsdktypes.RateConfig{}
					if f1elemf2iter.Period != nil {
						f1elemf2elem.Period = svcsdktypes.Period(*f1elemf2iter.Period)
					}
					if f1elemf2iter.Rate != nil {
						f1elemf2elem.Rate = f1elemf2iter.Rate
					}
					f1elemf2 = append(f1elemf2, *f1elemf2elem)
				}
				f1elem.Requests = f1elemf2
			}
			if f1iter.Tokens != nil {
				f1elemf3 := []svcsdktypes.RateConfig{}
				for _, f1elemf3iter := range f1iter.Tokens {
					f1elemf3elem := &svcsdktypes.RateConfig{}
					if f1elemf3iter.Period != nil {
						f1elemf3elem.Period = svcsdktypes.Period(*f1elemf3iter.Period)
					}
					if f1elemf3iter.Rate != nil {
						f1elemf3elem.Rate = f1elemf3iter.Rate
					}
					f1elemf3 = append(f1elemf3, *f1elemf3elem)
				}
				f1elem.Tokens = f1elemf3
			}
			f1 = append(f1, *f1elem)
		}
		res.Entries = f1
	}
	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Spec.RateLimitID != nil {
		res.RateLimitId = r.ko.Spec.RateLimitID
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if r.ko.Status.Status != nil {
		if !ackutil.InStrings(*r.ko.Status.Status, []string{"ACTIVE"}) {
			return nil, ackrequeue.NeededAfter(
				fmt.Errorf("resource is in %s state, cannot be deleted",
					*r.ko.Status.Status),
				time.Duration(30)*time.Second,
			)
		}
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteGatewayRateLimitOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteGatewayRateLimit(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteGatewayRateLimit", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteGatewayRateLimitInput, error) {
	res := &svcsdk.DeleteGatewayRateLimitInput{}

	if r.ko.Spec.GatewayIdentifier != nil {
		res.GatewayIdentifier = r.ko.Spec.GatewayIdentifier
	}
	if r.ko.Spec.RateLimitID != nil {
		res.RateLimitId = r.ko.Spec.RateLimitID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.GatewayRateLimit,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
