---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-bedrockagentcorecontrol-reader
  namespace: default
rules:
- apiGroups:
  - bedrockagentcorecontrol.services.k8s.aws
  resources:
  verbs:
  - get
  - list
  - watch
