// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package policy

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Definition, b.ko.Spec.Definition) {
		delta.Add("Spec.Definition", a.ko.Spec.Definition, b.ko.Spec.Definition)
	} else if a.ko.Spec.Definition != nil && b.ko.Spec.Definition != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Definition.Cedar, b.ko.Spec.Definition.Cedar) {
			delta.Add("Spec.Definition.Cedar", a.ko.Spec.Definition.Cedar, b.ko.Spec.Definition.Cedar)
		} else if a.ko.Spec.Definition.Cedar != nil && b.ko.Spec.Definition.Cedar != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Definition.Cedar.Statement, b.ko.Spec.Definition.Cedar.Statement) {
				delta.Add("Spec.Definition.Cedar.Statement", a.ko.Spec.Definition.Cedar.Statement, b.ko.Spec.Definition.Cedar.Statement)
			} else if a.ko.Spec.Definition.Cedar.Statement != nil && b.ko.Spec.Definition.Cedar.Statement != nil {
				if *a.ko.Spec.Definition.Cedar.Statement != *b.ko.Spec.Definition.Cedar.Statement {
					delta.Add("Spec.Definition.Cedar.Statement", a.ko.Spec.Definition.Cedar.Statement, b.ko.Spec.Definition.Cedar.Statement)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PolicyEngineID, b.ko.Spec.PolicyEngineID) {
		delta.Add("Spec.PolicyEngineID", a.ko.Spec.PolicyEngineID, b.ko.Spec.PolicyEngineID)
	} else if a.ko.Spec.PolicyEngineID != nil && b.ko.Spec.PolicyEngineID != nil {
		if *a.ko.Spec.PolicyEngineID != *b.ko.Spec.PolicyEngineID {
			delta.Add("Spec.PolicyEngineID", a.ko.Spec.PolicyEngineID, b.ko.Spec.PolicyEngineID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.PolicyEngineRef, b.ko.Spec.PolicyEngineRef) {
		delta.Add("Spec.PolicyEngineRef", a.ko.Spec.PolicyEngineRef, b.ko.Spec.PolicyEngineRef)
	}

	return delta
}
