# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription:
    Amazon Bedrock Agent Core Control controller is a service controller for managing Bedrock Agent Core Control resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Bedrock Agent Core Control
description: |-
  Manage Amazon Bedrock Agent Core Control resources in AWS from within your Kubernetes cluster.


  **About Amazon Bedrock Agent Core Control**


  Amazon Bedrock Agent Core Control is a fully managed service that makes it easy to build and scale generative AI applications. With Bedrock, you can access foundation models from leading AI companies, customize them with your own data, and integrate them into your applications.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
  - kind: UserPool
    spec: "{}"
maintainers:
  - name: "bedrockagentcorecontrol maintainer team"
    email: "ack-maintainers@amazon.com"
links:
  - name: Amazon Bedrock Agent Core Control Developer Resources
    url: https://aws.amazon.com/bedrock/dev-resources/
