// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/bedrockagentcorecontrol-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Memory{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetMemoryOutput
	resp, err = rm.sdkapi.GetMemory(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetMemory", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Memory.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Memory.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Memory.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Memory.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Memory.Description != nil {
		ko.Spec.Description = resp.Memory.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.Memory.EncryptionKeyArn != nil {
		ko.Spec.EncryptionKeyARN = resp.Memory.EncryptionKeyArn
	} else {
		ko.Spec.EncryptionKeyARN = nil
	}
	if resp.Memory.EventExpiryDuration != nil {
		eventExpiryDurationCopy := int64(*resp.Memory.EventExpiryDuration)
		ko.Spec.EventExpiryDuration = &eventExpiryDurationCopy
	} else {
		ko.Spec.EventExpiryDuration = nil
	}
	if resp.Memory.FailureReason != nil {
		ko.Status.FailureReason = resp.Memory.FailureReason
	} else {
		ko.Status.FailureReason = nil
	}
	if resp.Memory.Id != nil {
		ko.Status.ID = resp.Memory.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.Memory.MemoryExecutionRoleArn != nil {
		ko.Spec.MemoryExecutionRoleARN = resp.Memory.MemoryExecutionRoleArn
	} else {
		ko.Spec.MemoryExecutionRoleARN = nil
	}
	if resp.Memory.Name != nil {
		ko.Spec.Name = resp.Memory.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Memory.Status != "" {
		ko.Status.Status = aws.String(string(resp.Memory.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Memory.Strategies != nil {
		f10 := []*svcapitypes.MemoryStrategy{}
		for _, f10iter := range resp.Memory.Strategies {
			f10elem := &svcapitypes.MemoryStrategy{}
			if f10iter.Configuration != nil {
				f10elemf0 := &svcapitypes.StrategyConfiguration{}
				if f10iter.Configuration.Consolidation != nil {
					f10elemf0f0 := &svcapitypes.ConsolidationConfiguration{}
					switch f10iter.Configuration.Consolidation.(type) {
					case *svcsdktypes.ConsolidationConfigurationMemberCustomConsolidationConfiguration:
						f10elemf0f0f0 := f10iter.Configuration.Consolidation.(*svcsdktypes.ConsolidationConfigurationMemberCustomConsolidationConfiguration)
						if f10elemf0f0f0 != nil {
							f10elemf0f0f0f0 := &svcapitypes.CustomConsolidationConfiguration{}
							switch f10elemf0f0f0.Value.(type) {
							case *svcsdktypes.CustomConsolidationConfigurationMemberEpisodicConsolidationOverride:
								f10elemf0f0f0f0f0 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberEpisodicConsolidationOverride)
								if f10elemf0f0f0f0f0 != nil {
									f10elemf0f0f0f0f0f0 := &svcapitypes.EpisodicConsolidationOverride{}
									if f10elemf0f0f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f0f0.AppendToPrompt = f10elemf0f0f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f0.Value.ModelId != nil {
										f10elemf0f0f0f0f0f0.ModelID = f10elemf0f0f0f0f0.Value.ModelId
									}
									f10elemf0f0f0f0.EpisodicConsolidationOverride = f10elemf0f0f0f0f0f0
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberSemanticConsolidationOverride:
								f10elemf0f0f0f0f1 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberSemanticConsolidationOverride)
								if f10elemf0f0f0f0f1 != nil {
									f10elemf0f0f0f0f1f1 := &svcapitypes.SemanticConsolidationOverride{}
									if f10elemf0f0f0f0f1.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f1f1.AppendToPrompt = f10elemf0f0f0f0f1.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f1.Value.ModelId != nil {
										f10elemf0f0f0f0f1f1.ModelID = f10elemf0f0f0f0f1.Value.ModelId
									}
									f10elemf0f0f0f0.SemanticConsolidationOverride = f10elemf0f0f0f0f1f1
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberSummaryConsolidationOverride:
								f10elemf0f0f0f0f2 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberSummaryConsolidationOverride)
								if f10elemf0f0f0f0f2 != nil {
									f10elemf0f0f0f0f2f2 := &svcapitypes.SummaryConsolidationOverride{}
									if f10elemf0f0f0f0f2.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f2f2.AppendToPrompt = f10elemf0f0f0f0f2.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f2.Value.ModelId != nil {
										f10elemf0f0f0f0f2f2.ModelID = f10elemf0f0f0f0f2.Value.ModelId
									}
									f10elemf0f0f0f0.SummaryConsolidationOverride = f10elemf0f0f0f0f2f2
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberUserPreferenceConsolidationOverride:
								f10elemf0f0f0f0f3 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberUserPreferenceConsolidationOverride)
								if f10elemf0f0f0f0f3 != nil {
									f10elemf0f0f0f0f3f3 := &svcapitypes.UserPreferenceConsolidationOverride{}
									if f10elemf0f0f0f0f3.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f3f3.AppendToPrompt = f10elemf0f0f0f0f3.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f3.Value.ModelId != nil {
										f10elemf0f0f0f0f3f3.ModelID = f10elemf0f0f0f0f3.Value.ModelId
									}
									f10elemf0f0f0f0.UserPreferenceConsolidationOverride = f10elemf0f0f0f0f3f3
								}
							}
							f10elemf0f0.CustomConsolidationConfiguration = f10elemf0f0f0f0
						}
					}
					f10elemf0.Consolidation = f10elemf0f0
				}
				if f10iter.Configuration.Extraction != nil {
					f10elemf0f1 := &svcapitypes.ExtractionConfiguration{}
					switch f10iter.Configuration.Extraction.(type) {
					case *svcsdktypes.ExtractionConfigurationMemberCustomExtractionConfiguration:
						f10elemf0f1f0 := f10iter.Configuration.Extraction.(*svcsdktypes.ExtractionConfigurationMemberCustomExtractionConfiguration)
						if f10elemf0f1f0 != nil {
							f10elemf0f1f0f0 := &svcapitypes.CustomExtractionConfiguration{}
							switch f10elemf0f1f0.Value.(type) {
							case *svcsdktypes.CustomExtractionConfigurationMemberEpisodicExtractionOverride:
								f10elemf0f1f0f0f0 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberEpisodicExtractionOverride)
								if f10elemf0f1f0f0f0 != nil {
									f10elemf0f1f0f0f0f0 := &svcapitypes.EpisodicExtractionOverride{}
									if f10elemf0f1f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f0f0.AppendToPrompt = f10elemf0f1f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f0.Value.ModelId != nil {
										f10elemf0f1f0f0f0f0.ModelID = f10elemf0f1f0f0f0.Value.ModelId
									}
									f10elemf0f1f0f0.EpisodicExtractionOverride = f10elemf0f1f0f0f0f0
								}
							case *svcsdktypes.CustomExtractionConfigurationMemberSemanticExtractionOverride:
								f10elemf0f1f0f0f1 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberSemanticExtractionOverride)
								if f10elemf0f1f0f0f1 != nil {
									f10elemf0f1f0f0f1f1 := &svcapitypes.SemanticExtractionOverride{}
									if f10elemf0f1f0f0f1.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f1f1.AppendToPrompt = f10elemf0f1f0f0f1.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f1.Value.ModelId != nil {
										f10elemf0f1f0f0f1f1.ModelID = f10elemf0f1f0f0f1.Value.ModelId
									}
									f10elemf0f1f0f0.SemanticExtractionOverride = f10elemf0f1f0f0f1f1
								}
							case *svcsdktypes.CustomExtractionConfigurationMemberUserPreferenceExtractionOverride:
								f10elemf0f1f0f0f2 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberUserPreferenceExtractionOverride)
								if f10elemf0f1f0f0f2 != nil {
									f10elemf0f1f0f0f2f2 := &svcapitypes.UserPreferenceExtractionOverride{}
									if f10elemf0f1f0f0f2.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f2f2.AppendToPrompt = f10elemf0f1f0f0f2.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f2.Value.ModelId != nil {
										f10elemf0f1f0f0f2f2.ModelID = f10elemf0f1f0f0f2.Value.ModelId
									}
									f10elemf0f1f0f0.UserPreferenceExtractionOverride = f10elemf0f1f0f0f2f2
								}
							}
							f10elemf0f1.CustomExtractionConfiguration = f10elemf0f1f0f0
						}
					}
					f10elemf0.Extraction = f10elemf0f1
				}
				if f10iter.Configuration.Reflection != nil {
					f10elemf0f2 := &svcapitypes.ReflectionConfiguration{}
					switch f10iter.Configuration.Reflection.(type) {
					case *svcsdktypes.ReflectionConfigurationMemberCustomReflectionConfiguration:
						f10elemf0f2f0 := f10iter.Configuration.Reflection.(*svcsdktypes.ReflectionConfigurationMemberCustomReflectionConfiguration)
						if f10elemf0f2f0 != nil {
							f10elemf0f2f0f0 := &svcapitypes.CustomReflectionConfiguration{}
							switch f10elemf0f2f0.Value.(type) {
							case *svcsdktypes.CustomReflectionConfigurationMemberEpisodicReflectionOverride:
								f10elemf0f2f0f0f0 := f10elemf0f2f0.Value.(*svcsdktypes.CustomReflectionConfigurationMemberEpisodicReflectionOverride)
								if f10elemf0f2f0f0f0 != nil {
									f10elemf0f2f0f0f0f0 := &svcapitypes.EpisodicReflectionOverride{}
									if f10elemf0f2f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f2f0f0f0f0.AppendToPrompt = f10elemf0f2f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f2f0f0f0.Value.ModelId != nil {
										f10elemf0f2f0f0f0f0.ModelID = f10elemf0f2f0f0f0.Value.ModelId
									}
									if f10elemf0f2f0f0f0.Value.NamespaceTemplates != nil {
										f10elemf0f2f0f0f0f0.NamespaceTemplates = aws.StringSlice(f10elemf0f2f0f0f0.Value.NamespaceTemplates)
									}
									if f10elemf0f2f0f0f0.Value.Namespaces != nil {
										f10elemf0f2f0f0f0f0.Namespaces = aws.StringSlice(f10elemf0f2f0f0f0.Value.Namespaces)
									}
									f10elemf0f2f0f0.EpisodicReflectionOverride = f10elemf0f2f0f0f0f0
								}
							}
							f10elemf0f2.CustomReflectionConfiguration = f10elemf0f2f0f0
						}
					case *svcsdktypes.ReflectionConfigurationMemberEpisodicReflectionConfiguration:
						f10elemf0f2f1 := f10iter.Configuration.Reflection.(*svcsdktypes.ReflectionConfigurationMemberEpisodicReflectionConfiguration)
						if f10elemf0f2f1 != nil {
							f10elemf0f2f1f1 := &svcapitypes.EpisodicReflectionConfiguration{}
							if f10elemf0f2f1.Value.NamespaceTemplates != nil {
								f10elemf0f2f1f1.NamespaceTemplates = aws.StringSlice(f10elemf0f2f1.Value.NamespaceTemplates)
							}
							if f10elemf0f2f1.Value.Namespaces != nil {
								f10elemf0f2f1f1.Namespaces = aws.StringSlice(f10elemf0f2f1.Value.Namespaces)
							}
							f10elemf0f2.EpisodicReflectionConfiguration = f10elemf0f2f1f1
						}
					}
					f10elemf0.Reflection = f10elemf0f2
				}
				if f10iter.Configuration.SelfManagedConfiguration != nil {
					f10elemf0f3 := &svcapitypes.SelfManagedConfiguration{}
					if f10iter.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize != nil {
						historicalContextWindowSizeCopy := int64(*f10iter.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize)
						f10elemf0f3.HistoricalContextWindowSize = &historicalContextWindowSizeCopy
					}
					if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration != nil {
						f10elemf0f3f1 := &svcapitypes.InvocationConfiguration{}
						if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName != nil {
							f10elemf0f3f1.PayloadDeliveryBucketName = f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName
						}
						if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicArn != nil {
							f10elemf0f3f1.TopicARN = f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicArn
						}
						f10elemf0f3.InvocationConfiguration = f10elemf0f3f1
					}
					if f10iter.Configuration.SelfManagedConfiguration.TriggerConditions != nil {
						f10elemf0f3f2 := []*svcapitypes.TriggerCondition{}
						for _, f10elemf0f3f2iter := range f10iter.Configuration.SelfManagedConfiguration.TriggerConditions {
							f10elemf0f3f2elem := &svcapitypes.TriggerCondition{}
							switch f10elemf0f3f2iter.(type) {
							case *svcsdktypes.TriggerConditionMemberMessageBasedTrigger:
								f10elemf0f3f2elemf0 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberMessageBasedTrigger)
								if f10elemf0f3f2elemf0 != nil {
									f10elemf0f3f2elemf0f0 := &svcapitypes.MessageBasedTrigger{}
									if f10elemf0f3f2elemf0.Value.MessageCount != nil {
										messageCountCopy := int64(*f10elemf0f3f2elemf0.Value.MessageCount)
										f10elemf0f3f2elemf0f0.MessageCount = &messageCountCopy
									}
									f10elemf0f3f2elem.MessageBasedTrigger = f10elemf0f3f2elemf0f0
								}
							case *svcsdktypes.TriggerConditionMemberTimeBasedTrigger:
								f10elemf0f3f2elemf1 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberTimeBasedTrigger)
								if f10elemf0f3f2elemf1 != nil {
									f10elemf0f3f2elemf1f1 := &svcapitypes.TimeBasedTrigger{}
									if f10elemf0f3f2elemf1.Value.IdleSessionTimeout != nil {
										idleSessionTimeoutCopy := int64(*f10elemf0f3f2elemf1.Value.IdleSessionTimeout)
										f10elemf0f3f2elemf1f1.IdleSessionTimeout = &idleSessionTimeoutCopy
									}
									f10elemf0f3f2elem.TimeBasedTrigger = f10elemf0f3f2elemf1f1
								}
							case *svcsdktypes.TriggerConditionMemberTokenBasedTrigger:
								f10elemf0f3f2elemf2 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberTokenBasedTrigger)
								if f10elemf0f3f2elemf2 != nil {
									f10elemf0f3f2elemf2f2 := &svcapitypes.TokenBasedTrigger{}
									if f10elemf0f3f2elemf2.Value.TokenCount != nil {
										tokenCountCopy := int64(*f10elemf0f3f2elemf2.Value.TokenCount)
										f10elemf0f3f2elemf2f2.TokenCount = &tokenCountCopy
									}
									f10elemf0f3f2elem.TokenBasedTrigger = f10elemf0f3f2elemf2f2
								}
							}
							f10elemf0f3f2 = append(f10elemf0f3f2, f10elemf0f3f2elem)
						}
						f10elemf0f3.TriggerConditions = f10elemf0f3f2
					}
					f10elemf0.SelfManagedConfiguration = f10elemf0f3
				}
				if f10iter.Configuration.Type != "" {
					f10elemf0.Type = aws.String(string(f10iter.Configuration.Type))
				}
				f10elem.Configuration = f10elemf0
			}
			if f10iter.CreatedAt != nil {
				f10elem.CreatedAt = &metav1.Time{*f10iter.CreatedAt}
			}
			if f10iter.Description != nil {
				f10elem.Description = f10iter.Description
			}
			if f10iter.Name != nil {
				f10elem.Name = f10iter.Name
			}
			if f10iter.NamespaceTemplates != nil {
				f10elem.NamespaceTemplates = aws.StringSlice(f10iter.NamespaceTemplates)
			}
			if f10iter.Namespaces != nil {
				f10elem.Namespaces = aws.StringSlice(f10iter.Namespaces)
			}
			if f10iter.Status != "" {
				f10elem.Status = aws.String(string(f10iter.Status))
			}
			if f10iter.StrategyId != nil {
				f10elem.StrategyID = f10iter.StrategyId
			}
			if f10iter.Type != "" {
				f10elem.Type = aws.String(string(f10iter.Type))
			}
			if f10iter.UpdatedAt != nil {
				f10elem.UpdatedAt = &metav1.Time{*f10iter.UpdatedAt}
			}
			f10 = append(f10, f10elem)
		}
		ko.Status.Strategies = f10
	} else {
		ko.Status.Strategies = nil
	}
	if resp.Memory.StreamDeliveryResources != nil {
		f11 := &svcapitypes.StreamDeliveryResources{}
		if resp.Memory.StreamDeliveryResources.Resources != nil {
			f11f0 := []*svcapitypes.StreamDeliveryResource{}
			for _, f11f0iter := range resp.Memory.StreamDeliveryResources.Resources {
				f11f0elem := &svcapitypes.StreamDeliveryResource{}
				switch f11f0iter.(type) {
				case *svcsdktypes.StreamDeliveryResourceMemberKinesis:
					f11f0elemf0 := f11f0iter.(*svcsdktypes.StreamDeliveryResourceMemberKinesis)
					if f11f0elemf0 != nil {
						f11f0elemf0f0 := &svcapitypes.KinesisResource{}
						if f11f0elemf0.Value.ContentConfigurations != nil {
							f11f0elemf0f0f0 := []*svcapitypes.ContentConfiguration{}
							for _, f11f0elemf0f0f0iter := range f11f0elemf0.Value.ContentConfigurations {
								f11f0elemf0f0f0elem := &svcapitypes.ContentConfiguration{}
								if f11f0elemf0f0f0iter.Level != "" {
									f11f0elemf0f0f0elem.Level = aws.String(string(f11f0elemf0f0f0iter.Level))
								}
								if f11f0elemf0f0f0iter.Type != "" {
									f11f0elemf0f0f0elem.Type = aws.String(string(f11f0elemf0f0f0iter.Type))
								}
								f11f0elemf0f0f0 = append(f11f0elemf0f0f0, f11f0elemf0f0f0elem)
							}
							f11f0elemf0f0.ContentConfigurations = f11f0elemf0f0f0
						}
						if f11f0elemf0.Value.DataStreamArn != nil {
							f11f0elemf0f0.DataStreamARN = f11f0elemf0.Value.DataStreamArn
						}
						f11f0elem.Kinesis = f11f0elemf0f0
					}
				}
				f11f0 = append(f11f0, f11f0elem)
			}
			f11.Resources = f11f0
		}
		ko.Spec.StreamDeliveryResources = f11
	} else {
		ko.Spec.StreamDeliveryResources = nil
	}
	if resp.Memory.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Memory.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	tags, err := rm.getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN))
	if err != nil {
		return nil, err
	}
	ko.Spec.Tags = tags

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetMemoryInput, error) {
	res := &svcsdk.GetMemoryInput{}

	if r.ko.Status.ID != nil {
		res.MemoryId = r.ko.Status.ID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateMemoryOutput
	_ = resp
	resp, err = rm.sdkapi.CreateMemory(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateMemory", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Memory.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Memory.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Memory.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Memory.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Memory.Description != nil {
		ko.Spec.Description = resp.Memory.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.Memory.EncryptionKeyArn != nil {
		ko.Spec.EncryptionKeyARN = resp.Memory.EncryptionKeyArn
	} else {
		ko.Spec.EncryptionKeyARN = nil
	}
	if resp.Memory.EventExpiryDuration != nil {
		eventExpiryDurationCopy := int64(*resp.Memory.EventExpiryDuration)
		ko.Spec.EventExpiryDuration = &eventExpiryDurationCopy
	} else {
		ko.Spec.EventExpiryDuration = nil
	}
	if resp.Memory.FailureReason != nil {
		ko.Status.FailureReason = resp.Memory.FailureReason
	} else {
		ko.Status.FailureReason = nil
	}
	if resp.Memory.Id != nil {
		ko.Status.ID = resp.Memory.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.Memory.MemoryExecutionRoleArn != nil {
		ko.Spec.MemoryExecutionRoleARN = resp.Memory.MemoryExecutionRoleArn
	} else {
		ko.Spec.MemoryExecutionRoleARN = nil
	}
	if resp.Memory.Name != nil {
		ko.Spec.Name = resp.Memory.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Memory.Status != "" {
		ko.Status.Status = aws.String(string(resp.Memory.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Memory.Strategies != nil {
		f10 := []*svcapitypes.MemoryStrategy{}
		for _, f10iter := range resp.Memory.Strategies {
			f10elem := &svcapitypes.MemoryStrategy{}
			if f10iter.Configuration != nil {
				f10elemf0 := &svcapitypes.StrategyConfiguration{}
				if f10iter.Configuration.Consolidation != nil {
					f10elemf0f0 := &svcapitypes.ConsolidationConfiguration{}
					switch f10iter.Configuration.Consolidation.(type) {
					case *svcsdktypes.ConsolidationConfigurationMemberCustomConsolidationConfiguration:
						f10elemf0f0f0 := f10iter.Configuration.Consolidation.(*svcsdktypes.ConsolidationConfigurationMemberCustomConsolidationConfiguration)
						if f10elemf0f0f0 != nil {
							f10elemf0f0f0f0 := &svcapitypes.CustomConsolidationConfiguration{}
							switch f10elemf0f0f0.Value.(type) {
							case *svcsdktypes.CustomConsolidationConfigurationMemberEpisodicConsolidationOverride:
								f10elemf0f0f0f0f0 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberEpisodicConsolidationOverride)
								if f10elemf0f0f0f0f0 != nil {
									f10elemf0f0f0f0f0f0 := &svcapitypes.EpisodicConsolidationOverride{}
									if f10elemf0f0f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f0f0.AppendToPrompt = f10elemf0f0f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f0.Value.ModelId != nil {
										f10elemf0f0f0f0f0f0.ModelID = f10elemf0f0f0f0f0.Value.ModelId
									}
									f10elemf0f0f0f0.EpisodicConsolidationOverride = f10elemf0f0f0f0f0f0
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberSemanticConsolidationOverride:
								f10elemf0f0f0f0f1 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberSemanticConsolidationOverride)
								if f10elemf0f0f0f0f1 != nil {
									f10elemf0f0f0f0f1f1 := &svcapitypes.SemanticConsolidationOverride{}
									if f10elemf0f0f0f0f1.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f1f1.AppendToPrompt = f10elemf0f0f0f0f1.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f1.Value.ModelId != nil {
										f10elemf0f0f0f0f1f1.ModelID = f10elemf0f0f0f0f1.Value.ModelId
									}
									f10elemf0f0f0f0.SemanticConsolidationOverride = f10elemf0f0f0f0f1f1
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberSummaryConsolidationOverride:
								f10elemf0f0f0f0f2 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberSummaryConsolidationOverride)
								if f10elemf0f0f0f0f2 != nil {
									f10elemf0f0f0f0f2f2 := &svcapitypes.SummaryConsolidationOverride{}
									if f10elemf0f0f0f0f2.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f2f2.AppendToPrompt = f10elemf0f0f0f0f2.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f2.Value.ModelId != nil {
										f10elemf0f0f0f0f2f2.ModelID = f10elemf0f0f0f0f2.Value.ModelId
									}
									f10elemf0f0f0f0.SummaryConsolidationOverride = f10elemf0f0f0f0f2f2
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberUserPreferenceConsolidationOverride:
								f10elemf0f0f0f0f3 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberUserPreferenceConsolidationOverride)
								if f10elemf0f0f0f0f3 != nil {
									f10elemf0f0f0f0f3f3 := &svcapitypes.UserPreferenceConsolidationOverride{}
									if f10elemf0f0f0f0f3.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f3f3.AppendToPrompt = f10elemf0f0f0f0f3.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f3.Value.ModelId != nil {
										f10elemf0f0f0f0f3f3.ModelID = f10elemf0f0f0f0f3.Value.ModelId
									}
									f10elemf0f0f0f0.UserPreferenceConsolidationOverride = f10elemf0f0f0f0f3f3
								}
							}
							f10elemf0f0.CustomConsolidationConfiguration = f10elemf0f0f0f0
						}
					}
					f10elemf0.Consolidation = f10elemf0f0
				}
				if f10iter.Configuration.Extraction != nil {
					f10elemf0f1 := &svcapitypes.ExtractionConfiguration{}
					switch f10iter.Configuration.Extraction.(type) {
					case *svcsdktypes.ExtractionConfigurationMemberCustomExtractionConfiguration:
						f10elemf0f1f0 := f10iter.Configuration.Extraction.(*svcsdktypes.ExtractionConfigurationMemberCustomExtractionConfiguration)
						if f10elemf0f1f0 != nil {
							f10elemf0f1f0f0 := &svcapitypes.CustomExtractionConfiguration{}
							switch f10elemf0f1f0.Value.(type) {
							case *svcsdktypes.CustomExtractionConfigurationMemberEpisodicExtractionOverride:
								f10elemf0f1f0f0f0 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberEpisodicExtractionOverride)
								if f10elemf0f1f0f0f0 != nil {
									f10elemf0f1f0f0f0f0 := &svcapitypes.EpisodicExtractionOverride{}
									if f10elemf0f1f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f0f0.AppendToPrompt = f10elemf0f1f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f0.Value.ModelId != nil {
										f10elemf0f1f0f0f0f0.ModelID = f10elemf0f1f0f0f0.Value.ModelId
									}
									f10elemf0f1f0f0.EpisodicExtractionOverride = f10elemf0f1f0f0f0f0
								}
							case *svcsdktypes.CustomExtractionConfigurationMemberSemanticExtractionOverride:
								f10elemf0f1f0f0f1 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberSemanticExtractionOverride)
								if f10elemf0f1f0f0f1 != nil {
									f10elemf0f1f0f0f1f1 := &svcapitypes.SemanticExtractionOverride{}
									if f10elemf0f1f0f0f1.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f1f1.AppendToPrompt = f10elemf0f1f0f0f1.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f1.Value.ModelId != nil {
										f10elemf0f1f0f0f1f1.ModelID = f10elemf0f1f0f0f1.Value.ModelId
									}
									f10elemf0f1f0f0.SemanticExtractionOverride = f10elemf0f1f0f0f1f1
								}
							case *svcsdktypes.CustomExtractionConfigurationMemberUserPreferenceExtractionOverride:
								f10elemf0f1f0f0f2 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberUserPreferenceExtractionOverride)
								if f10elemf0f1f0f0f2 != nil {
									f10elemf0f1f0f0f2f2 := &svcapitypes.UserPreferenceExtractionOverride{}
									if f10elemf0f1f0f0f2.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f2f2.AppendToPrompt = f10elemf0f1f0f0f2.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f2.Value.ModelId != nil {
										f10elemf0f1f0f0f2f2.ModelID = f10elemf0f1f0f0f2.Value.ModelId
									}
									f10elemf0f1f0f0.UserPreferenceExtractionOverride = f10elemf0f1f0f0f2f2
								}
							}
							f10elemf0f1.CustomExtractionConfiguration = f10elemf0f1f0f0
						}
					}
					f10elemf0.Extraction = f10elemf0f1
				}
				if f10iter.Configuration.Reflection != nil {
					f10elemf0f2 := &svcapitypes.ReflectionConfiguration{}
					switch f10iter.Configuration.Reflection.(type) {
					case *svcsdktypes.ReflectionConfigurationMemberCustomReflectionConfiguration:
						f10elemf0f2f0 := f10iter.Configuration.Reflection.(*svcsdktypes.ReflectionConfigurationMemberCustomReflectionConfiguration)
						if f10elemf0f2f0 != nil {
							f10elemf0f2f0f0 := &svcapitypes.CustomReflectionConfiguration{}
							switch f10elemf0f2f0.Value.(type) {
							case *svcsdktypes.CustomReflectionConfigurationMemberEpisodicReflectionOverride:
								f10elemf0f2f0f0f0 := f10elemf0f2f0.Value.(*svcsdktypes.CustomReflectionConfigurationMemberEpisodicReflectionOverride)
								if f10elemf0f2f0f0f0 != nil {
									f10elemf0f2f0f0f0f0 := &svcapitypes.EpisodicReflectionOverride{}
									if f10elemf0f2f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f2f0f0f0f0.AppendToPrompt = f10elemf0f2f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f2f0f0f0.Value.ModelId != nil {
										f10elemf0f2f0f0f0f0.ModelID = f10elemf0f2f0f0f0.Value.ModelId
									}
									if f10elemf0f2f0f0f0.Value.NamespaceTemplates != nil {
										f10elemf0f2f0f0f0f0.NamespaceTemplates = aws.StringSlice(f10elemf0f2f0f0f0.Value.NamespaceTemplates)
									}
									if f10elemf0f2f0f0f0.Value.Namespaces != nil {
										f10elemf0f2f0f0f0f0.Namespaces = aws.StringSlice(f10elemf0f2f0f0f0.Value.Namespaces)
									}
									f10elemf0f2f0f0.EpisodicReflectionOverride = f10elemf0f2f0f0f0f0
								}
							}
							f10elemf0f2.CustomReflectionConfiguration = f10elemf0f2f0f0
						}
					case *svcsdktypes.ReflectionConfigurationMemberEpisodicReflectionConfiguration:
						f10elemf0f2f1 := f10iter.Configuration.Reflection.(*svcsdktypes.ReflectionConfigurationMemberEpisodicReflectionConfiguration)
						if f10elemf0f2f1 != nil {
							f10elemf0f2f1f1 := &svcapitypes.EpisodicReflectionConfiguration{}
							if f10elemf0f2f1.Value.NamespaceTemplates != nil {
								f10elemf0f2f1f1.NamespaceTemplates = aws.StringSlice(f10elemf0f2f1.Value.NamespaceTemplates)
							}
							if f10elemf0f2f1.Value.Namespaces != nil {
								f10elemf0f2f1f1.Namespaces = aws.StringSlice(f10elemf0f2f1.Value.Namespaces)
							}
							f10elemf0f2.EpisodicReflectionConfiguration = f10elemf0f2f1f1
						}
					}
					f10elemf0.Reflection = f10elemf0f2
				}
				if f10iter.Configuration.SelfManagedConfiguration != nil {
					f10elemf0f3 := &svcapitypes.SelfManagedConfiguration{}
					if f10iter.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize != nil {
						historicalContextWindowSizeCopy := int64(*f10iter.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize)
						f10elemf0f3.HistoricalContextWindowSize = &historicalContextWindowSizeCopy
					}
					if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration != nil {
						f10elemf0f3f1 := &svcapitypes.InvocationConfiguration{}
						if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName != nil {
							f10elemf0f3f1.PayloadDeliveryBucketName = f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName
						}
						if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicArn != nil {
							f10elemf0f3f1.TopicARN = f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicArn
						}
						f10elemf0f3.InvocationConfiguration = f10elemf0f3f1
					}
					if f10iter.Configuration.SelfManagedConfiguration.TriggerConditions != nil {
						f10elemf0f3f2 := []*svcapitypes.TriggerCondition{}
						for _, f10elemf0f3f2iter := range f10iter.Configuration.SelfManagedConfiguration.TriggerConditions {
							f10elemf0f3f2elem := &svcapitypes.TriggerCondition{}
							switch f10elemf0f3f2iter.(type) {
							case *svcsdktypes.TriggerConditionMemberMessageBasedTrigger:
								f10elemf0f3f2elemf0 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberMessageBasedTrigger)
								if f10elemf0f3f2elemf0 != nil {
									f10elemf0f3f2elemf0f0 := &svcapitypes.MessageBasedTrigger{}
									if f10elemf0f3f2elemf0.Value.MessageCount != nil {
										messageCountCopy := int64(*f10elemf0f3f2elemf0.Value.MessageCount)
										f10elemf0f3f2elemf0f0.MessageCount = &messageCountCopy
									}
									f10elemf0f3f2elem.MessageBasedTrigger = f10elemf0f3f2elemf0f0
								}
							case *svcsdktypes.TriggerConditionMemberTimeBasedTrigger:
								f10elemf0f3f2elemf1 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberTimeBasedTrigger)
								if f10elemf0f3f2elemf1 != nil {
									f10elemf0f3f2elemf1f1 := &svcapitypes.TimeBasedTrigger{}
									if f10elemf0f3f2elemf1.Value.IdleSessionTimeout != nil {
										idleSessionTimeoutCopy := int64(*f10elemf0f3f2elemf1.Value.IdleSessionTimeout)
										f10elemf0f3f2elemf1f1.IdleSessionTimeout = &idleSessionTimeoutCopy
									}
									f10elemf0f3f2elem.TimeBasedTrigger = f10elemf0f3f2elemf1f1
								}
							case *svcsdktypes.TriggerConditionMemberTokenBasedTrigger:
								f10elemf0f3f2elemf2 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberTokenBasedTrigger)
								if f10elemf0f3f2elemf2 != nil {
									f10elemf0f3f2elemf2f2 := &svcapitypes.TokenBasedTrigger{}
									if f10elemf0f3f2elemf2.Value.TokenCount != nil {
										tokenCountCopy := int64(*f10elemf0f3f2elemf2.Value.TokenCount)
										f10elemf0f3f2elemf2f2.TokenCount = &tokenCountCopy
									}
									f10elemf0f3f2elem.TokenBasedTrigger = f10elemf0f3f2elemf2f2
								}
							}
							f10elemf0f3f2 = append(f10elemf0f3f2, f10elemf0f3f2elem)
						}
						f10elemf0f3.TriggerConditions = f10elemf0f3f2
					}
					f10elemf0.SelfManagedConfiguration = f10elemf0f3
				}
				if f10iter.Configuration.Type != "" {
					f10elemf0.Type = aws.String(string(f10iter.Configuration.Type))
				}
				f10elem.Configuration = f10elemf0
			}
			if f10iter.CreatedAt != nil {
				f10elem.CreatedAt = &metav1.Time{*f10iter.CreatedAt}
			}
			if f10iter.Description != nil {
				f10elem.Description = f10iter.Description
			}
			if f10iter.Name != nil {
				f10elem.Name = f10iter.Name
			}
			if f10iter.NamespaceTemplates != nil {
				f10elem.NamespaceTemplates = aws.StringSlice(f10iter.NamespaceTemplates)
			}
			if f10iter.Namespaces != nil {
				f10elem.Namespaces = aws.StringSlice(f10iter.Namespaces)
			}
			if f10iter.Status != "" {
				f10elem.Status = aws.String(string(f10iter.Status))
			}
			if f10iter.StrategyId != nil {
				f10elem.StrategyID = f10iter.StrategyId
			}
			if f10iter.Type != "" {
				f10elem.Type = aws.String(string(f10iter.Type))
			}
			if f10iter.UpdatedAt != nil {
				f10elem.UpdatedAt = &metav1.Time{*f10iter.UpdatedAt}
			}
			f10 = append(f10, f10elem)
		}
		ko.Status.Strategies = f10
	} else {
		ko.Status.Strategies = nil
	}
	if resp.Memory.StreamDeliveryResources != nil {
		f11 := &svcapitypes.StreamDeliveryResources{}
		if resp.Memory.StreamDeliveryResources.Resources != nil {
			f11f0 := []*svcapitypes.StreamDeliveryResource{}
			for _, f11f0iter := range resp.Memory.StreamDeliveryResources.Resources {
				f11f0elem := &svcapitypes.StreamDeliveryResource{}
				switch f11f0iter.(type) {
				case *svcsdktypes.StreamDeliveryResourceMemberKinesis:
					f11f0elemf0 := f11f0iter.(*svcsdktypes.StreamDeliveryResourceMemberKinesis)
					if f11f0elemf0 != nil {
						f11f0elemf0f0 := &svcapitypes.KinesisResource{}
						if f11f0elemf0.Value.ContentConfigurations != nil {
							f11f0elemf0f0f0 := []*svcapitypes.ContentConfiguration{}
							for _, f11f0elemf0f0f0iter := range f11f0elemf0.Value.ContentConfigurations {
								f11f0elemf0f0f0elem := &svcapitypes.ContentConfiguration{}
								if f11f0elemf0f0f0iter.Level != "" {
									f11f0elemf0f0f0elem.Level = aws.String(string(f11f0elemf0f0f0iter.Level))
								}
								if f11f0elemf0f0f0iter.Type != "" {
									f11f0elemf0f0f0elem.Type = aws.String(string(f11f0elemf0f0f0iter.Type))
								}
								f11f0elemf0f0f0 = append(f11f0elemf0f0f0, f11f0elemf0f0f0elem)
							}
							f11f0elemf0f0.ContentConfigurations = f11f0elemf0f0f0
						}
						if f11f0elemf0.Value.DataStreamArn != nil {
							f11f0elemf0f0.DataStreamARN = f11f0elemf0.Value.DataStreamArn
						}
						f11f0elem.Kinesis = f11f0elemf0f0
					}
				}
				f11f0 = append(f11f0, f11f0elem)
			}
			f11.Resources = f11f0
		}
		ko.Spec.StreamDeliveryResources = f11
	} else {
		ko.Spec.StreamDeliveryResources = nil
	}
	if resp.Memory.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Memory.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateMemoryInput, error) {
	res := &svcsdk.CreateMemoryInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EncryptionKeyARN != nil {
		res.EncryptionKeyArn = r.ko.Spec.EncryptionKeyARN
	}
	if r.ko.Spec.EventExpiryDuration != nil {
		eventExpiryDurationCopy0 := *r.ko.Spec.EventExpiryDuration
		if eventExpiryDurationCopy0 > math.MaxInt32 || eventExpiryDurationCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field eventExpiryDuration is of type int32")
		}
		eventExpiryDurationCopy := int32(eventExpiryDurationCopy0)
		res.EventExpiryDuration = &eventExpiryDurationCopy
	}
	if r.ko.Spec.MemoryExecutionRoleARN != nil {
		res.MemoryExecutionRoleArn = r.ko.Spec.MemoryExecutionRoleARN
	}
	if r.ko.Spec.MemoryStrategies != nil {
		f5 := []svcsdktypes.MemoryStrategyInput{}
		for _, f5iter := range r.ko.Spec.MemoryStrategies {
			var f5elem svcsdktypes.MemoryStrategyInput
			isInterfaceSet := false
			if f5iter.CustomMemoryStrategy != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CustomMemoryStrategy"))
				}
				f5elemf0Parent := &svcsdktypes.MemoryStrategyInputMemberCustomMemoryStrategy{}
				f5elemf0 := &svcsdktypes.CustomMemoryStrategyInput{}
				if f5iter.CustomMemoryStrategy.Configuration != nil {
					var f5elemf0f0 svcsdktypes.CustomConfigurationInput
					isInterfaceSet := false
					if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for EpisodicOverride"))
						}
						f5elemf0f0f0Parent := &svcsdktypes.CustomConfigurationInputMemberEpisodicOverride{}
						f5elemf0f0f0 := &svcsdktypes.EpisodicOverrideConfigurationInput{}
						if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Consolidation != nil {
							f5elemf0f0f0f0 := &svcsdktypes.EpisodicOverrideConsolidationConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Consolidation.AppendToPrompt != nil {
								f5elemf0f0f0f0.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Consolidation.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Consolidation.ModelID != nil {
								f5elemf0f0f0f0.ModelId = f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Consolidation.ModelID
							}
							f5elemf0f0f0.Consolidation = f5elemf0f0f0f0
						}
						if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Extraction != nil {
							f5elemf0f0f0f1 := &svcsdktypes.EpisodicOverrideExtractionConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Extraction.AppendToPrompt != nil {
								f5elemf0f0f0f1.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Extraction.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Extraction.ModelID != nil {
								f5elemf0f0f0f1.ModelId = f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Extraction.ModelID
							}
							f5elemf0f0f0.Extraction = f5elemf0f0f0f1
						}
						if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection != nil {
							f5elemf0f0f0f2 := &svcsdktypes.EpisodicOverrideReflectionConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.AppendToPrompt != nil {
								f5elemf0f0f0f2.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.ModelID != nil {
								f5elemf0f0f0f2.ModelId = f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.ModelID
							}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.NamespaceTemplates != nil {
								f5elemf0f0f0f2.NamespaceTemplates = aws.ToStringSlice(f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.NamespaceTemplates)
							}
							if f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.Namespaces != nil {
								f5elemf0f0f0f2.Namespaces = aws.ToStringSlice(f5iter.CustomMemoryStrategy.Configuration.EpisodicOverride.Reflection.Namespaces)
							}
							f5elemf0f0f0.Reflection = f5elemf0f0f0f2
						}
						f5elemf0f0f0Parent.Value = *f5elemf0f0f0
						f5elemf0f0 = f5elemf0f0f0Parent
						isInterfaceSet = true
					}
					if f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SelfManagedConfiguration"))
						}
						f5elemf0f0f1Parent := &svcsdktypes.CustomConfigurationInputMemberSelfManagedConfiguration{}
						f5elemf0f0f1 := &svcsdktypes.SelfManagedConfigurationInput{}
						if f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize != nil {
							historicalContextWindowSizeCopy0 := *f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize
							if historicalContextWindowSizeCopy0 > math.MaxInt32 || historicalContextWindowSizeCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field historicalContextWindowSize is of type int32")
							}
							historicalContextWindowSizeCopy := int32(historicalContextWindowSizeCopy0)
							f5elemf0f0f1.HistoricalContextWindowSize = &historicalContextWindowSizeCopy
						}
						if f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.InvocationConfiguration != nil {
							f5elemf0f0f1f1 := &svcsdktypes.InvocationConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName != nil {
								f5elemf0f0f1f1.PayloadDeliveryBucketName = f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName
							}
							if f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicARN != nil {
								f5elemf0f0f1f1.TopicArn = f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicARN
							}
							f5elemf0f0f1.InvocationConfiguration = f5elemf0f0f1f1
						}
						if f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.TriggerConditions != nil {
							f5elemf0f0f1f2 := []svcsdktypes.TriggerConditionInput{}
							for _, f5elemf0f0f1f2iter := range f5iter.CustomMemoryStrategy.Configuration.SelfManagedConfiguration.TriggerConditions {
								var f5elemf0f0f1f2elem svcsdktypes.TriggerConditionInput
								isInterfaceSet := false
								if f5elemf0f0f1f2iter.MessageBasedTrigger != nil {
									if isInterfaceSet {
										return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MessageBasedTrigger"))
									}
									f5elemf0f0f1f2elemf0Parent := &svcsdktypes.TriggerConditionInputMemberMessageBasedTrigger{}
									f5elemf0f0f1f2elemf0 := &svcsdktypes.MessageBasedTriggerInput{}
									if f5elemf0f0f1f2iter.MessageBasedTrigger.MessageCount != nil {
										messageCountCopy0 := *f5elemf0f0f1f2iter.MessageBasedTrigger.MessageCount
										if messageCountCopy0 > math.MaxInt32 || messageCountCopy0 < math.MinInt32 {
											return nil, fmt.Errorf("error: field messageCount is of type int32")
										}
										messageCountCopy := int32(messageCountCopy0)
										f5elemf0f0f1f2elemf0.MessageCount = &messageCountCopy
									}
									f5elemf0f0f1f2elemf0Parent.Value = *f5elemf0f0f1f2elemf0
									f5elemf0f0f1f2elem = f5elemf0f0f1f2elemf0Parent
									isInterfaceSet = true
								}
								if f5elemf0f0f1f2iter.TimeBasedTrigger != nil {
									if isInterfaceSet {
										return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for TimeBasedTrigger"))
									}
									f5elemf0f0f1f2elemf1Parent := &svcsdktypes.TriggerConditionInputMemberTimeBasedTrigger{}
									f5elemf0f0f1f2elemf1 := &svcsdktypes.TimeBasedTriggerInput{}
									if f5elemf0f0f1f2iter.TimeBasedTrigger.IdleSessionTimeout != nil {
										idleSessionTimeoutCopy0 := *f5elemf0f0f1f2iter.TimeBasedTrigger.IdleSessionTimeout
										if idleSessionTimeoutCopy0 > math.MaxInt32 || idleSessionTimeoutCopy0 < math.MinInt32 {
											return nil, fmt.Errorf("error: field idleSessionTimeout is of type int32")
										}
										idleSessionTimeoutCopy := int32(idleSessionTimeoutCopy0)
										f5elemf0f0f1f2elemf1.IdleSessionTimeout = &idleSessionTimeoutCopy
									}
									f5elemf0f0f1f2elemf1Parent.Value = *f5elemf0f0f1f2elemf1
									f5elemf0f0f1f2elem = f5elemf0f0f1f2elemf1Parent
									isInterfaceSet = true
								}
								if f5elemf0f0f1f2iter.TokenBasedTrigger != nil {
									if isInterfaceSet {
										return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for TokenBasedTrigger"))
									}
									f5elemf0f0f1f2elemf2Parent := &svcsdktypes.TriggerConditionInputMemberTokenBasedTrigger{}
									f5elemf0f0f1f2elemf2 := &svcsdktypes.TokenBasedTriggerInput{}
									if f5elemf0f0f1f2iter.TokenBasedTrigger.TokenCount != nil {
										tokenCountCopy0 := *f5elemf0f0f1f2iter.TokenBasedTrigger.TokenCount
										if tokenCountCopy0 > math.MaxInt32 || tokenCountCopy0 < math.MinInt32 {
											return nil, fmt.Errorf("error: field tokenCount is of type int32")
										}
										tokenCountCopy := int32(tokenCountCopy0)
										f5elemf0f0f1f2elemf2.TokenCount = &tokenCountCopy
									}
									f5elemf0f0f1f2elemf2Parent.Value = *f5elemf0f0f1f2elemf2
									f5elemf0f0f1f2elem = f5elemf0f0f1f2elemf2Parent
									isInterfaceSet = true
								}
								f5elemf0f0f1f2 = append(f5elemf0f0f1f2, f5elemf0f0f1f2elem)
							}
							f5elemf0f0f1.TriggerConditions = f5elemf0f0f1f2
						}
						f5elemf0f0f1Parent.Value = *f5elemf0f0f1
						f5elemf0f0 = f5elemf0f0f1Parent
						isInterfaceSet = true
					}
					if f5iter.CustomMemoryStrategy.Configuration.SemanticOverride != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SemanticOverride"))
						}
						f5elemf0f0f2Parent := &svcsdktypes.CustomConfigurationInputMemberSemanticOverride{}
						f5elemf0f0f2 := &svcsdktypes.SemanticOverrideConfigurationInput{}
						if f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Consolidation != nil {
							f5elemf0f0f2f0 := &svcsdktypes.SemanticOverrideConsolidationConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Consolidation.AppendToPrompt != nil {
								f5elemf0f0f2f0.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Consolidation.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Consolidation.ModelID != nil {
								f5elemf0f0f2f0.ModelId = f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Consolidation.ModelID
							}
							f5elemf0f0f2.Consolidation = f5elemf0f0f2f0
						}
						if f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Extraction != nil {
							f5elemf0f0f2f1 := &svcsdktypes.SemanticOverrideExtractionConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Extraction.AppendToPrompt != nil {
								f5elemf0f0f2f1.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Extraction.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Extraction.ModelID != nil {
								f5elemf0f0f2f1.ModelId = f5iter.CustomMemoryStrategy.Configuration.SemanticOverride.Extraction.ModelID
							}
							f5elemf0f0f2.Extraction = f5elemf0f0f2f1
						}
						f5elemf0f0f2Parent.Value = *f5elemf0f0f2
						f5elemf0f0 = f5elemf0f0f2Parent
						isInterfaceSet = true
					}
					if f5iter.CustomMemoryStrategy.Configuration.SummaryOverride != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SummaryOverride"))
						}
						f5elemf0f0f3Parent := &svcsdktypes.CustomConfigurationInputMemberSummaryOverride{}
						f5elemf0f0f3 := &svcsdktypes.SummaryOverrideConfigurationInput{}
						if f5iter.CustomMemoryStrategy.Configuration.SummaryOverride.Consolidation != nil {
							f5elemf0f0f3f0 := &svcsdktypes.SummaryOverrideConsolidationConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.SummaryOverride.Consolidation.AppendToPrompt != nil {
								f5elemf0f0f3f0.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.SummaryOverride.Consolidation.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.SummaryOverride.Consolidation.ModelID != nil {
								f5elemf0f0f3f0.ModelId = f5iter.CustomMemoryStrategy.Configuration.SummaryOverride.Consolidation.ModelID
							}
							f5elemf0f0f3.Consolidation = f5elemf0f0f3f0
						}
						f5elemf0f0f3Parent.Value = *f5elemf0f0f3
						f5elemf0f0 = f5elemf0f0f3Parent
						isInterfaceSet = true
					}
					if f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for UserPreferenceOverride"))
						}
						f5elemf0f0f4Parent := &svcsdktypes.CustomConfigurationInputMemberUserPreferenceOverride{}
						f5elemf0f0f4 := &svcsdktypes.UserPreferenceOverrideConfigurationInput{}
						if f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Consolidation != nil {
							f5elemf0f0f4f0 := &svcsdktypes.UserPreferenceOverrideConsolidationConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Consolidation.AppendToPrompt != nil {
								f5elemf0f0f4f0.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Consolidation.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Consolidation.ModelID != nil {
								f5elemf0f0f4f0.ModelId = f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Consolidation.ModelID
							}
							f5elemf0f0f4.Consolidation = f5elemf0f0f4f0
						}
						if f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Extraction != nil {
							f5elemf0f0f4f1 := &svcsdktypes.UserPreferenceOverrideExtractionConfigurationInput{}
							if f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Extraction.AppendToPrompt != nil {
								f5elemf0f0f4f1.AppendToPrompt = f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Extraction.AppendToPrompt
							}
							if f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Extraction.ModelID != nil {
								f5elemf0f0f4f1.ModelId = f5iter.CustomMemoryStrategy.Configuration.UserPreferenceOverride.Extraction.ModelID
							}
							f5elemf0f0f4.Extraction = f5elemf0f0f4f1
						}
						f5elemf0f0f4Parent.Value = *f5elemf0f0f4
						f5elemf0f0 = f5elemf0f0f4Parent
						isInterfaceSet = true
					}
					f5elemf0.Configuration = f5elemf0f0
				}
				if f5iter.CustomMemoryStrategy.Description != nil {
					f5elemf0.Description = f5iter.CustomMemoryStrategy.Description
				}
				if f5iter.CustomMemoryStrategy.Name != nil {
					f5elemf0.Name = f5iter.CustomMemoryStrategy.Name
				}
				if f5iter.CustomMemoryStrategy.NamespaceTemplates != nil {
					f5elemf0.NamespaceTemplates = aws.ToStringSlice(f5iter.CustomMemoryStrategy.NamespaceTemplates)
				}
				if f5iter.CustomMemoryStrategy.Namespaces != nil {
					f5elemf0.Namespaces = aws.ToStringSlice(f5iter.CustomMemoryStrategy.Namespaces)
				}
				f5elemf0Parent.Value = *f5elemf0
				f5elem = f5elemf0Parent
				isInterfaceSet = true
			}
			if f5iter.EpisodicMemoryStrategy != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for EpisodicMemoryStrategy"))
				}
				f5elemf1Parent := &svcsdktypes.MemoryStrategyInputMemberEpisodicMemoryStrategy{}
				f5elemf1 := &svcsdktypes.EpisodicMemoryStrategyInput{}
				if f5iter.EpisodicMemoryStrategy.Description != nil {
					f5elemf1.Description = f5iter.EpisodicMemoryStrategy.Description
				}
				if f5iter.EpisodicMemoryStrategy.Name != nil {
					f5elemf1.Name = f5iter.EpisodicMemoryStrategy.Name
				}
				if f5iter.EpisodicMemoryStrategy.NamespaceTemplates != nil {
					f5elemf1.NamespaceTemplates = aws.ToStringSlice(f5iter.EpisodicMemoryStrategy.NamespaceTemplates)
				}
				if f5iter.EpisodicMemoryStrategy.Namespaces != nil {
					f5elemf1.Namespaces = aws.ToStringSlice(f5iter.EpisodicMemoryStrategy.Namespaces)
				}
				if f5iter.EpisodicMemoryStrategy.ReflectionConfiguration != nil {
					f5elemf1f4 := &svcsdktypes.EpisodicReflectionConfigurationInput{}
					if f5iter.EpisodicMemoryStrategy.ReflectionConfiguration.NamespaceTemplates != nil {
						f5elemf1f4.NamespaceTemplates = aws.ToStringSlice(f5iter.EpisodicMemoryStrategy.ReflectionConfiguration.NamespaceTemplates)
					}
					if f5iter.EpisodicMemoryStrategy.ReflectionConfiguration.Namespaces != nil {
						f5elemf1f4.Namespaces = aws.ToStringSlice(f5iter.EpisodicMemoryStrategy.ReflectionConfiguration.Namespaces)
					}
					f5elemf1.ReflectionConfiguration = f5elemf1f4
				}
				f5elemf1Parent.Value = *f5elemf1
				f5elem = f5elemf1Parent
				isInterfaceSet = true
			}
			if f5iter.SemanticMemoryStrategy != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SemanticMemoryStrategy"))
				}
				f5elemf2Parent := &svcsdktypes.MemoryStrategyInputMemberSemanticMemoryStrategy{}
				f5elemf2 := &svcsdktypes.SemanticMemoryStrategyInput{}
				if f5iter.SemanticMemoryStrategy.Description != nil {
					f5elemf2.Description = f5iter.SemanticMemoryStrategy.Description
				}
				if f5iter.SemanticMemoryStrategy.Name != nil {
					f5elemf2.Name = f5iter.SemanticMemoryStrategy.Name
				}
				if f5iter.SemanticMemoryStrategy.NamespaceTemplates != nil {
					f5elemf2.NamespaceTemplates = aws.ToStringSlice(f5iter.SemanticMemoryStrategy.NamespaceTemplates)
				}
				if f5iter.SemanticMemoryStrategy.Namespaces != nil {
					f5elemf2.Namespaces = aws.ToStringSlice(f5iter.SemanticMemoryStrategy.Namespaces)
				}
				f5elemf2Parent.Value = *f5elemf2
				f5elem = f5elemf2Parent
				isInterfaceSet = true
			}
			if f5iter.SummaryMemoryStrategy != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SummaryMemoryStrategy"))
				}
				f5elemf3Parent := &svcsdktypes.MemoryStrategyInputMemberSummaryMemoryStrategy{}
				f5elemf3 := &svcsdktypes.SummaryMemoryStrategyInput{}
				if f5iter.SummaryMemoryStrategy.Description != nil {
					f5elemf3.Description = f5iter.SummaryMemoryStrategy.Description
				}
				if f5iter.SummaryMemoryStrategy.Name != nil {
					f5elemf3.Name = f5iter.SummaryMemoryStrategy.Name
				}
				if f5iter.SummaryMemoryStrategy.NamespaceTemplates != nil {
					f5elemf3.NamespaceTemplates = aws.ToStringSlice(f5iter.SummaryMemoryStrategy.NamespaceTemplates)
				}
				if f5iter.SummaryMemoryStrategy.Namespaces != nil {
					f5elemf3.Namespaces = aws.ToStringSlice(f5iter.SummaryMemoryStrategy.Namespaces)
				}
				f5elemf3Parent.Value = *f5elemf3
				f5elem = f5elemf3Parent
				isInterfaceSet = true
			}
			if f5iter.UserPreferenceMemoryStrategy != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for UserPreferenceMemoryStrategy"))
				}
				f5elemf4Parent := &svcsdktypes.MemoryStrategyInputMemberUserPreferenceMemoryStrategy{}
				f5elemf4 := &svcsdktypes.UserPreferenceMemoryStrategyInput{}
				if f5iter.UserPreferenceMemoryStrategy.Description != nil {
					f5elemf4.Description = f5iter.UserPreferenceMemoryStrategy.Description
				}
				if f5iter.UserPreferenceMemoryStrategy.Name != nil {
					f5elemf4.Name = f5iter.UserPreferenceMemoryStrategy.Name
				}
				if f5iter.UserPreferenceMemoryStrategy.NamespaceTemplates != nil {
					f5elemf4.NamespaceTemplates = aws.ToStringSlice(f5iter.UserPreferenceMemoryStrategy.NamespaceTemplates)
				}
				if f5iter.UserPreferenceMemoryStrategy.Namespaces != nil {
					f5elemf4.Namespaces = aws.ToStringSlice(f5iter.UserPreferenceMemoryStrategy.Namespaces)
				}
				f5elemf4Parent.Value = *f5elemf4
				f5elem = f5elemf4Parent
				isInterfaceSet = true
			}
			f5 = append(f5, f5elem)
		}
		res.MemoryStrategies = f5
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.StreamDeliveryResources != nil {
		f7 := &svcsdktypes.StreamDeliveryResources{}
		if r.ko.Spec.StreamDeliveryResources.Resources != nil {
			f7f0 := []svcsdktypes.StreamDeliveryResource{}
			for _, f7f0iter := range r.ko.Spec.StreamDeliveryResources.Resources {
				var f7f0elem svcsdktypes.StreamDeliveryResource
				isInterfaceSet := false
				if f7f0iter.Kinesis != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Kinesis"))
					}
					f7f0elemf0Parent := &svcsdktypes.StreamDeliveryResourceMemberKinesis{}
					f7f0elemf0 := &svcsdktypes.KinesisResource{}
					if f7f0iter.Kinesis.ContentConfigurations != nil {
						f7f0elemf0f0 := []svcsdktypes.ContentConfiguration{}
						for _, f7f0elemf0f0iter := range f7f0iter.Kinesis.ContentConfigurations {
							f7f0elemf0f0elem := &svcsdktypes.ContentConfiguration{}
							if f7f0elemf0f0iter.Level != nil {
								f7f0elemf0f0elem.Level = svcsdktypes.ContentLevel(*f7f0elemf0f0iter.Level)
							}
							if f7f0elemf0f0iter.Type != nil {
								f7f0elemf0f0elem.Type = svcsdktypes.ContentType(*f7f0elemf0f0iter.Type)
							}
							f7f0elemf0f0 = append(f7f0elemf0f0, *f7f0elemf0f0elem)
						}
						f7f0elemf0.ContentConfigurations = f7f0elemf0f0
					}
					if f7f0iter.Kinesis.DataStreamARN != nil {
						f7f0elemf0.DataStreamArn = f7f0iter.Kinesis.DataStreamARN
					}
					f7f0elemf0Parent.Value = *f7f0elemf0
					f7f0elem = f7f0elemf0Parent
					isInterfaceSet = true
				}
				f7f0 = append(f7f0, f7f0elem)
			}
			f7.Resources = f7f0
		}
		res.StreamDeliveryResources = f7
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		err := rm.syncTags(
			ctx, desired, latest,
		)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags", "Spec.MemoryStrategies") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	if delta.DifferentAt("Spec.MemoryStrategies") {
		input.MemoryStrategies = buildModifyMemoryStrategies(
			desired.ko.Spec.MemoryStrategies,
			latest.ko.Status.Strategies,
		)
	}

	var resp *svcsdk.UpdateMemoryOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateMemory(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateMemory", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Memory.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Memory.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Memory.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Memory.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Memory.Description != nil {
		ko.Spec.Description = resp.Memory.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.Memory.EncryptionKeyArn != nil {
		ko.Spec.EncryptionKeyARN = resp.Memory.EncryptionKeyArn
	} else {
		ko.Spec.EncryptionKeyARN = nil
	}
	if resp.Memory.EventExpiryDuration != nil {
		eventExpiryDurationCopy := int64(*resp.Memory.EventExpiryDuration)
		ko.Spec.EventExpiryDuration = &eventExpiryDurationCopy
	} else {
		ko.Spec.EventExpiryDuration = nil
	}
	if resp.Memory.FailureReason != nil {
		ko.Status.FailureReason = resp.Memory.FailureReason
	} else {
		ko.Status.FailureReason = nil
	}
	if resp.Memory.Id != nil {
		ko.Status.ID = resp.Memory.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.Memory.MemoryExecutionRoleArn != nil {
		ko.Spec.MemoryExecutionRoleARN = resp.Memory.MemoryExecutionRoleArn
	} else {
		ko.Spec.MemoryExecutionRoleARN = nil
	}
	if resp.Memory.Name != nil {
		ko.Spec.Name = resp.Memory.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Memory.Status != "" {
		ko.Status.Status = aws.String(string(resp.Memory.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Memory.Strategies != nil {
		f10 := []*svcapitypes.MemoryStrategy{}
		for _, f10iter := range resp.Memory.Strategies {
			f10elem := &svcapitypes.MemoryStrategy{}
			if f10iter.Configuration != nil {
				f10elemf0 := &svcapitypes.StrategyConfiguration{}
				if f10iter.Configuration.Consolidation != nil {
					f10elemf0f0 := &svcapitypes.ConsolidationConfiguration{}
					switch f10iter.Configuration.Consolidation.(type) {
					case *svcsdktypes.ConsolidationConfigurationMemberCustomConsolidationConfiguration:
						f10elemf0f0f0 := f10iter.Configuration.Consolidation.(*svcsdktypes.ConsolidationConfigurationMemberCustomConsolidationConfiguration)
						if f10elemf0f0f0 != nil {
							f10elemf0f0f0f0 := &svcapitypes.CustomConsolidationConfiguration{}
							switch f10elemf0f0f0.Value.(type) {
							case *svcsdktypes.CustomConsolidationConfigurationMemberEpisodicConsolidationOverride:
								f10elemf0f0f0f0f0 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberEpisodicConsolidationOverride)
								if f10elemf0f0f0f0f0 != nil {
									f10elemf0f0f0f0f0f0 := &svcapitypes.EpisodicConsolidationOverride{}
									if f10elemf0f0f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f0f0.AppendToPrompt = f10elemf0f0f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f0.Value.ModelId != nil {
										f10elemf0f0f0f0f0f0.ModelID = f10elemf0f0f0f0f0.Value.ModelId
									}
									f10elemf0f0f0f0.EpisodicConsolidationOverride = f10elemf0f0f0f0f0f0
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberSemanticConsolidationOverride:
								f10elemf0f0f0f0f1 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberSemanticConsolidationOverride)
								if f10elemf0f0f0f0f1 != nil {
									f10elemf0f0f0f0f1f1 := &svcapitypes.SemanticConsolidationOverride{}
									if f10elemf0f0f0f0f1.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f1f1.AppendToPrompt = f10elemf0f0f0f0f1.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f1.Value.ModelId != nil {
										f10elemf0f0f0f0f1f1.ModelID = f10elemf0f0f0f0f1.Value.ModelId
									}
									f10elemf0f0f0f0.SemanticConsolidationOverride = f10elemf0f0f0f0f1f1
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberSummaryConsolidationOverride:
								f10elemf0f0f0f0f2 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberSummaryConsolidationOverride)
								if f10elemf0f0f0f0f2 != nil {
									f10elemf0f0f0f0f2f2 := &svcapitypes.SummaryConsolidationOverride{}
									if f10elemf0f0f0f0f2.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f2f2.AppendToPrompt = f10elemf0f0f0f0f2.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f2.Value.ModelId != nil {
										f10elemf0f0f0f0f2f2.ModelID = f10elemf0f0f0f0f2.Value.ModelId
									}
									f10elemf0f0f0f0.SummaryConsolidationOverride = f10elemf0f0f0f0f2f2
								}
							case *svcsdktypes.CustomConsolidationConfigurationMemberUserPreferenceConsolidationOverride:
								f10elemf0f0f0f0f3 := f10elemf0f0f0.Value.(*svcsdktypes.CustomConsolidationConfigurationMemberUserPreferenceConsolidationOverride)
								if f10elemf0f0f0f0f3 != nil {
									f10elemf0f0f0f0f3f3 := &svcapitypes.UserPreferenceConsolidationOverride{}
									if f10elemf0f0f0f0f3.Value.AppendToPrompt != nil {
										f10elemf0f0f0f0f3f3.AppendToPrompt = f10elemf0f0f0f0f3.Value.AppendToPrompt
									}
									if f10elemf0f0f0f0f3.Value.ModelId != nil {
										f10elemf0f0f0f0f3f3.ModelID = f10elemf0f0f0f0f3.Value.ModelId
									}
									f10elemf0f0f0f0.UserPreferenceConsolidationOverride = f10elemf0f0f0f0f3f3
								}
							}
							f10elemf0f0.CustomConsolidationConfiguration = f10elemf0f0f0f0
						}
					}
					f10elemf0.Consolidation = f10elemf0f0
				}
				if f10iter.Configuration.Extraction != nil {
					f10elemf0f1 := &svcapitypes.ExtractionConfiguration{}
					switch f10iter.Configuration.Extraction.(type) {
					case *svcsdktypes.ExtractionConfigurationMemberCustomExtractionConfiguration:
						f10elemf0f1f0 := f10iter.Configuration.Extraction.(*svcsdktypes.ExtractionConfigurationMemberCustomExtractionConfiguration)
						if f10elemf0f1f0 != nil {
							f10elemf0f1f0f0 := &svcapitypes.CustomExtractionConfiguration{}
							switch f10elemf0f1f0.Value.(type) {
							case *svcsdktypes.CustomExtractionConfigurationMemberEpisodicExtractionOverride:
								f10elemf0f1f0f0f0 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberEpisodicExtractionOverride)
								if f10elemf0f1f0f0f0 != nil {
									f10elemf0f1f0f0f0f0 := &svcapitypes.EpisodicExtractionOverride{}
									if f10elemf0f1f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f0f0.AppendToPrompt = f10elemf0f1f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f0.Value.ModelId != nil {
										f10elemf0f1f0f0f0f0.ModelID = f10elemf0f1f0f0f0.Value.ModelId
									}
									f10elemf0f1f0f0.EpisodicExtractionOverride = f10elemf0f1f0f0f0f0
								}
							case *svcsdktypes.CustomExtractionConfigurationMemberSemanticExtractionOverride:
								f10elemf0f1f0f0f1 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberSemanticExtractionOverride)
								if f10elemf0f1f0f0f1 != nil {
									f10elemf0f1f0f0f1f1 := &svcapitypes.SemanticExtractionOverride{}
									if f10elemf0f1f0f0f1.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f1f1.AppendToPrompt = f10elemf0f1f0f0f1.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f1.Value.ModelId != nil {
										f10elemf0f1f0f0f1f1.ModelID = f10elemf0f1f0f0f1.Value.ModelId
									}
									f10elemf0f1f0f0.SemanticExtractionOverride = f10elemf0f1f0f0f1f1
								}
							case *svcsdktypes.CustomExtractionConfigurationMemberUserPreferenceExtractionOverride:
								f10elemf0f1f0f0f2 := f10elemf0f1f0.Value.(*svcsdktypes.CustomExtractionConfigurationMemberUserPreferenceExtractionOverride)
								if f10elemf0f1f0f0f2 != nil {
									f10elemf0f1f0f0f2f2 := &svcapitypes.UserPreferenceExtractionOverride{}
									if f10elemf0f1f0f0f2.Value.AppendToPrompt != nil {
										f10elemf0f1f0f0f2f2.AppendToPrompt = f10elemf0f1f0f0f2.Value.AppendToPrompt
									}
									if f10elemf0f1f0f0f2.Value.ModelId != nil {
										f10elemf0f1f0f0f2f2.ModelID = f10elemf0f1f0f0f2.Value.ModelId
									}
									f10elemf0f1f0f0.UserPreferenceExtractionOverride = f10elemf0f1f0f0f2f2
								}
							}
							f10elemf0f1.CustomExtractionConfiguration = f10elemf0f1f0f0
						}
					}
					f10elemf0.Extraction = f10elemf0f1
				}
				if f10iter.Configuration.Reflection != nil {
					f10elemf0f2 := &svcapitypes.ReflectionConfiguration{}
					switch f10iter.Configuration.Reflection.(type) {
					case *svcsdktypes.ReflectionConfigurationMemberCustomReflectionConfiguration:
						f10elemf0f2f0 := f10iter.Configuration.Reflection.(*svcsdktypes.ReflectionConfigurationMemberCustomReflectionConfiguration)
						if f10elemf0f2f0 != nil {
							f10elemf0f2f0f0 := &svcapitypes.CustomReflectionConfiguration{}
							switch f10elemf0f2f0.Value.(type) {
							case *svcsdktypes.CustomReflectionConfigurationMemberEpisodicReflectionOverride:
								f10elemf0f2f0f0f0 := f10elemf0f2f0.Value.(*svcsdktypes.CustomReflectionConfigurationMemberEpisodicReflectionOverride)
								if f10elemf0f2f0f0f0 != nil {
									f10elemf0f2f0f0f0f0 := &svcapitypes.EpisodicReflectionOverride{}
									if f10elemf0f2f0f0f0.Value.AppendToPrompt != nil {
										f10elemf0f2f0f0f0f0.AppendToPrompt = f10elemf0f2f0f0f0.Value.AppendToPrompt
									}
									if f10elemf0f2f0f0f0.Value.ModelId != nil {
										f10elemf0f2f0f0f0f0.ModelID = f10elemf0f2f0f0f0.Value.ModelId
									}
									if f10elemf0f2f0f0f0.Value.NamespaceTemplates != nil {
										f10elemf0f2f0f0f0f0.NamespaceTemplates = aws.StringSlice(f10elemf0f2f0f0f0.Value.NamespaceTemplates)
									}
									if f10elemf0f2f0f0f0.Value.Namespaces != nil {
										f10elemf0f2f0f0f0f0.Namespaces = aws.StringSlice(f10elemf0f2f0f0f0.Value.Namespaces)
									}
									f10elemf0f2f0f0.EpisodicReflectionOverride = f10elemf0f2f0f0f0f0
								}
							}
							f10elemf0f2.CustomReflectionConfiguration = f10elemf0f2f0f0
						}
					case *svcsdktypes.ReflectionConfigurationMemberEpisodicReflectionConfiguration:
						f10elemf0f2f1 := f10iter.Configuration.Reflection.(*svcsdktypes.ReflectionConfigurationMemberEpisodicReflectionConfiguration)
						if f10elemf0f2f1 != nil {
							f10elemf0f2f1f1 := &svcapitypes.EpisodicReflectionConfiguration{}
							if f10elemf0f2f1.Value.NamespaceTemplates != nil {
								f10elemf0f2f1f1.NamespaceTemplates = aws.StringSlice(f10elemf0f2f1.Value.NamespaceTemplates)
							}
							if f10elemf0f2f1.Value.Namespaces != nil {
								f10elemf0f2f1f1.Namespaces = aws.StringSlice(f10elemf0f2f1.Value.Namespaces)
							}
							f10elemf0f2.EpisodicReflectionConfiguration = f10elemf0f2f1f1
						}
					}
					f10elemf0.Reflection = f10elemf0f2
				}
				if f10iter.Configuration.SelfManagedConfiguration != nil {
					f10elemf0f3 := &svcapitypes.SelfManagedConfiguration{}
					if f10iter.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize != nil {
						historicalContextWindowSizeCopy := int64(*f10iter.Configuration.SelfManagedConfiguration.HistoricalContextWindowSize)
						f10elemf0f3.HistoricalContextWindowSize = &historicalContextWindowSizeCopy
					}
					if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration != nil {
						f10elemf0f3f1 := &svcapitypes.InvocationConfiguration{}
						if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName != nil {
							f10elemf0f3f1.PayloadDeliveryBucketName = f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.PayloadDeliveryBucketName
						}
						if f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicArn != nil {
							f10elemf0f3f1.TopicARN = f10iter.Configuration.SelfManagedConfiguration.InvocationConfiguration.TopicArn
						}
						f10elemf0f3.InvocationConfiguration = f10elemf0f3f1
					}
					if f10iter.Configuration.SelfManagedConfiguration.TriggerConditions != nil {
						f10elemf0f3f2 := []*svcapitypes.TriggerCondition{}
						for _, f10elemf0f3f2iter := range f10iter.Configuration.SelfManagedConfiguration.TriggerConditions {
							f10elemf0f3f2elem := &svcapitypes.TriggerCondition{}
							switch f10elemf0f3f2iter.(type) {
							case *svcsdktypes.TriggerConditionMemberMessageBasedTrigger:
								f10elemf0f3f2elemf0 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberMessageBasedTrigger)
								if f10elemf0f3f2elemf0 != nil {
									f10elemf0f3f2elemf0f0 := &svcapitypes.MessageBasedTrigger{}
									if f10elemf0f3f2elemf0.Value.MessageCount != nil {
										messageCountCopy := int64(*f10elemf0f3f2elemf0.Value.MessageCount)
										f10elemf0f3f2elemf0f0.MessageCount = &messageCountCopy
									}
									f10elemf0f3f2elem.MessageBasedTrigger = f10elemf0f3f2elemf0f0
								}
							case *svcsdktypes.TriggerConditionMemberTimeBasedTrigger:
								f10elemf0f3f2elemf1 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberTimeBasedTrigger)
								if f10elemf0f3f2elemf1 != nil {
									f10elemf0f3f2elemf1f1 := &svcapitypes.TimeBasedTrigger{}
									if f10elemf0f3f2elemf1.Value.IdleSessionTimeout != nil {
										idleSessionTimeoutCopy := int64(*f10elemf0f3f2elemf1.Value.IdleSessionTimeout)
										f10elemf0f3f2elemf1f1.IdleSessionTimeout = &idleSessionTimeoutCopy
									}
									f10elemf0f3f2elem.TimeBasedTrigger = f10elemf0f3f2elemf1f1
								}
							case *svcsdktypes.TriggerConditionMemberTokenBasedTrigger:
								f10elemf0f3f2elemf2 := f10elemf0f3f2iter.(*svcsdktypes.TriggerConditionMemberTokenBasedTrigger)
								if f10elemf0f3f2elemf2 != nil {
									f10elemf0f3f2elemf2f2 := &svcapitypes.TokenBasedTrigger{}
									if f10elemf0f3f2elemf2.Value.TokenCount != nil {
										tokenCountCopy := int64(*f10elemf0f3f2elemf2.Value.TokenCount)
										f10elemf0f3f2elemf2f2.TokenCount = &tokenCountCopy
									}
									f10elemf0f3f2elem.TokenBasedTrigger = f10elemf0f3f2elemf2f2
								}
							}
							f10elemf0f3f2 = append(f10elemf0f3f2, f10elemf0f3f2elem)
						}
						f10elemf0f3.TriggerConditions = f10elemf0f3f2
					}
					f10elemf0.SelfManagedConfiguration = f10elemf0f3
				}
				if f10iter.Configuration.Type != "" {
					f10elemf0.Type = aws.String(string(f10iter.Configuration.Type))
				}
				f10elem.Configuration = f10elemf0
			}
			if f10iter.CreatedAt != nil {
				f10elem.CreatedAt = &metav1.Time{*f10iter.CreatedAt}
			}
			if f10iter.Description != nil {
				f10elem.Description = f10iter.Description
			}
			if f10iter.Name != nil {
				f10elem.Name = f10iter.Name
			}
			if f10iter.NamespaceTemplates != nil {
				f10elem.NamespaceTemplates = aws.StringSlice(f10iter.NamespaceTemplates)
			}
			if f10iter.Namespaces != nil {
				f10elem.Namespaces = aws.StringSlice(f10iter.Namespaces)
			}
			if f10iter.Status != "" {
				f10elem.Status = aws.String(string(f10iter.Status))
			}
			if f10iter.StrategyId != nil {
				f10elem.StrategyID = f10iter.StrategyId
			}
			if f10iter.Type != "" {
				f10elem.Type = aws.String(string(f10iter.Type))
			}
			if f10iter.UpdatedAt != nil {
				f10elem.UpdatedAt = &metav1.Time{*f10iter.UpdatedAt}
			}
			f10 = append(f10, f10elem)
		}
		ko.Status.Strategies = f10
	} else {
		ko.Status.Strategies = nil
	}
	if resp.Memory.StreamDeliveryResources != nil {
		f11 := &svcapitypes.StreamDeliveryResources{}
		if resp.Memory.StreamDeliveryResources.Resources != nil {
			f11f0 := []*svcapitypes.StreamDeliveryResource{}
			for _, f11f0iter := range resp.Memory.StreamDeliveryResources.Resources {
				f11f0elem := &svcapitypes.StreamDeliveryResource{}
				switch f11f0iter.(type) {
				case *svcsdktypes.StreamDeliveryResourceMemberKinesis:
					f11f0elemf0 := f11f0iter.(*svcsdktypes.StreamDeliveryResourceMemberKinesis)
					if f11f0elemf0 != nil {
						f11f0elemf0f0 := &svcapitypes.KinesisResource{}
						if f11f0elemf0.Value.ContentConfigurations != nil {
							f11f0elemf0f0f0 := []*svcapitypes.ContentConfiguration{}
							for _, f11f0elemf0f0f0iter := range f11f0elemf0.Value.ContentConfigurations {
								f11f0elemf0f0f0elem := &svcapitypes.ContentConfiguration{}
								if f11f0elemf0f0f0iter.Level != "" {
									f11f0elemf0f0f0elem.Level = aws.String(string(f11f0elemf0f0f0iter.Level))
								}
								if f11f0elemf0f0f0iter.Type != "" {
									f11f0elemf0f0f0elem.Type = aws.String(string(f11f0elemf0f0f0iter.Type))
								}
								f11f0elemf0f0f0 = append(f11f0elemf0f0f0, f11f0elemf0f0f0elem)
							}
							f11f0elemf0f0.ContentConfigurations = f11f0elemf0f0f0
						}
						if f11f0elemf0.Value.DataStreamArn != nil {
							f11f0elemf0f0.DataStreamARN = f11f0elemf0.Value.DataStreamArn
						}
						f11f0elem.Kinesis = f11f0elemf0f0
					}
				}
				f11f0 = append(f11f0, f11f0elem)
			}
			f11.Resources = f11f0
		}
		ko.Spec.StreamDeliveryResources = f11
	} else {
		ko.Spec.StreamDeliveryResources = nil
	}
	if resp.Memory.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Memory.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateMemoryInput, error) {
	res := &svcsdk.UpdateMemoryInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EventExpiryDuration != nil {
		eventExpiryDurationCopy0 := *r.ko.Spec.EventExpiryDuration
		if eventExpiryDurationCopy0 > math.MaxInt32 || eventExpiryDurationCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field eventExpiryDuration is of type int32")
		}
		eventExpiryDurationCopy := int32(eventExpiryDurationCopy0)
		res.EventExpiryDuration = &eventExpiryDurationCopy
	}
	if r.ko.Spec.MemoryExecutionRoleARN != nil {
		res.MemoryExecutionRoleArn = r.ko.Spec.MemoryExecutionRoleARN
	}
	if r.ko.Status.ID != nil {
		res.MemoryId = r.ko.Status.ID
	}
	if r.ko.Spec.StreamDeliveryResources != nil {
		f5 := &svcsdktypes.StreamDeliveryResources{}
		if r.ko.Spec.StreamDeliveryResources.Resources != nil {
			f5f0 := []svcsdktypes.StreamDeliveryResource{}
			for _, f5f0iter := range r.ko.Spec.StreamDeliveryResources.Resources {
				var f5f0elem svcsdktypes.StreamDeliveryResource
				isInterfaceSet := false
				if f5f0iter.Kinesis != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Kinesis"))
					}
					f5f0elemf0Parent := &svcsdktypes.StreamDeliveryResourceMemberKinesis{}
					f5f0elemf0 := &svcsdktypes.KinesisResource{}
					if f5f0iter.Kinesis.ContentConfigurations != nil {
						f5f0elemf0f0 := []svcsdktypes.ContentConfiguration{}
						for _, f5f0elemf0f0iter := range f5f0iter.Kinesis.ContentConfigurations {
							f5f0elemf0f0elem := &svcsdktypes.ContentConfiguration{}
							if f5f0elemf0f0iter.Level != nil {
								f5f0elemf0f0elem.Level = svcsdktypes.ContentLevel(*f5f0elemf0f0iter.Level)
							}
							if f5f0elemf0f0iter.Type != nil {
								f5f0elemf0f0elem.Type = svcsdktypes.ContentType(*f5f0elemf0f0iter.Type)
							}
							f5f0elemf0f0 = append(f5f0elemf0f0, *f5f0elemf0f0elem)
						}
						f5f0elemf0.ContentConfigurations = f5f0elemf0f0
					}
					if f5f0iter.Kinesis.DataStreamARN != nil {
						f5f0elemf0.DataStreamArn = f5f0iter.Kinesis.DataStreamARN
					}
					f5f0elemf0Parent.Value = *f5f0elemf0
					f5f0elem = f5f0elemf0Parent
					isInterfaceSet = true
				}
				f5f0 = append(f5f0, f5f0elem)
			}
			f5.Resources = f5f0
		}
		res.StreamDeliveryResources = f5
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteMemoryOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteMemory(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteMemory", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteMemoryInput, error) {
	res := &svcsdk.DeleteMemoryInput{}

	if r.ko.Status.ID != nil {
		res.MemoryId = r.ko.Status.ID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Memory,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"ConflictException":
		return true
	default:
		return false
	}
}
