// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package browser

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	ackutil "github.com/aws-controllers-k8s/runtime/pkg/util"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/bedrockagentcorecontrol-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Browser{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetBrowserOutput
	resp, err = rm.sdkapi.GetBrowser(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetBrowser", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BrowserArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BrowserArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BrowserId != nil {
		ko.Status.BrowserID = resp.BrowserId
	} else {
		ko.Status.BrowserID = nil
	}
	if resp.BrowserSigning != nil {
		f2 := &svcapitypes.BrowserSigningConfigInput{}
		f2.Enabled = &resp.BrowserSigning.Enabled
		ko.Spec.BrowserSigning = f2
	} else {
		ko.Spec.BrowserSigning = nil
	}
	if resp.Certificates != nil {
		f3 := []*svcapitypes.Certificate{}
		for _, f3iter := range resp.Certificates {
			f3elem := &svcapitypes.Certificate{}
			if f3iter.Location != nil {
				f3elemf0 := &svcapitypes.CertificateLocation{}
				switch f3iter.Location.(type) {
				case *svcsdktypes.CertificateLocationMemberSecretsManager:
					f3elemf0f0 := f3iter.Location.(*svcsdktypes.CertificateLocationMemberSecretsManager)
					if f3elemf0f0 != nil {
						f3elemf0f0f0 := &svcapitypes.SecretsManagerLocation{}
						if f3elemf0f0.Value.SecretArn != nil {
							f3elemf0f0f0.SecretARN = f3elemf0f0.Value.SecretArn
						}
						f3elemf0.SecretsManager = f3elemf0f0f0
					}
				}
				f3elem.Location = f3elemf0
			}
			f3 = append(f3, f3elem)
		}
		ko.Spec.Certificates = f3
	} else {
		ko.Spec.Certificates = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.EnterprisePolicies != nil {
		f6 := []*svcapitypes.BrowserEnterprisePolicy{}
		for _, f6iter := range resp.EnterprisePolicies {
			f6elem := &svcapitypes.BrowserEnterprisePolicy{}
			if f6iter.Location != nil {
				f6elemf0 := &svcapitypes.ResourceLocation{}
				switch f6iter.Location.(type) {
				case *svcsdktypes.ResourceLocationMemberS3:
					f6elemf0f0 := f6iter.Location.(*svcsdktypes.ResourceLocationMemberS3)
					if f6elemf0f0 != nil {
						f6elemf0f0f0 := &svcapitypes.S3Location{}
						if f6elemf0f0.Value.Bucket != nil {
							f6elemf0f0f0.Bucket = f6elemf0f0.Value.Bucket
						}
						if f6elemf0f0.Value.Prefix != nil {
							f6elemf0f0f0.Prefix = f6elemf0f0.Value.Prefix
						}
						if f6elemf0f0.Value.VersionId != nil {
							f6elemf0f0f0.VersionID = f6elemf0f0.Value.VersionId
						}
						f6elemf0.S3 = f6elemf0f0f0
					}
				}
				f6elem.Location = f6elemf0
			}
			if f6iter.Type != "" {
				f6elem.Type = aws.String(string(f6iter.Type))
			}
			f6 = append(f6, f6elem)
		}
		ko.Spec.EnterprisePolicies = f6
	} else {
		ko.Spec.EnterprisePolicies = nil
	}
	if resp.ExecutionRoleArn != nil {
		ko.Spec.ExecutionRoleARN = resp.ExecutionRoleArn
	} else {
		ko.Spec.ExecutionRoleARN = nil
	}
	if resp.FailureReason != nil {
		ko.Status.FailureReason = resp.FailureReason
	} else {
		ko.Status.FailureReason = nil
	}
	if resp.LastUpdatedAt != nil {
		ko.Status.LastUpdatedAt = &metav1.Time{*resp.LastUpdatedAt}
	} else {
		ko.Status.LastUpdatedAt = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.NetworkConfiguration != nil {
		f11 := &svcapitypes.BrowserNetworkConfiguration{}
		if resp.NetworkConfiguration.NetworkMode != "" {
			f11.NetworkMode = aws.String(string(resp.NetworkConfiguration.NetworkMode))
		}
		if resp.NetworkConfiguration.VpcConfig != nil {
			f11f1 := &svcapitypes.VPCConfig{}
			if resp.NetworkConfiguration.VpcConfig.SecurityGroups != nil {
				f11f1.SecurityGroups = aws.StringSlice(resp.NetworkConfiguration.VpcConfig.SecurityGroups)
			}
			if resp.NetworkConfiguration.VpcConfig.Subnets != nil {
				f11f1.Subnets = aws.StringSlice(resp.NetworkConfiguration.VpcConfig.Subnets)
			}
			f11.VPCConfig = f11f1
		}
		ko.Spec.NetworkConfiguration = f11
	} else {
		ko.Spec.NetworkConfiguration = nil
	}
	if resp.Recording != nil {
		f12 := &svcapitypes.RecordingConfig{}
		f12.Enabled = &resp.Recording.Enabled
		if resp.Recording.S3Location != nil {
			f12f1 := &svcapitypes.S3Location{}
			if resp.Recording.S3Location.Bucket != nil {
				f12f1.Bucket = resp.Recording.S3Location.Bucket
			}
			if resp.Recording.S3Location.Prefix != nil {
				f12f1.Prefix = resp.Recording.S3Location.Prefix
			}
			if resp.Recording.S3Location.VersionId != nil {
				f12f1.VersionID = resp.Recording.S3Location.VersionId
			}
			f12.S3Location = f12f1
		}
		ko.Spec.Recording = f12
	} else {
		ko.Spec.Recording = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	tags, err := rm.getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN))
	if err != nil {
		return nil, err
	}
	ko.Spec.Tags = tags

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.BrowserID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetBrowserInput, error) {
	res := &svcsdk.GetBrowserInput{}

	if r.ko.Status.BrowserID != nil {
		res.BrowserId = r.ko.Status.BrowserID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateBrowserOutput
	_ = resp
	resp, err = rm.sdkapi.CreateBrowser(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateBrowser", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BrowserArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BrowserArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BrowserId != nil {
		ko.Status.BrowserID = resp.BrowserId
	} else {
		ko.Status.BrowserID = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateBrowserInput, error) {
	res := &svcsdk.CreateBrowserInput{}

	if r.ko.Spec.BrowserSigning != nil {
		f0 := &svcsdktypes.BrowserSigningConfigInput{}
		if r.ko.Spec.BrowserSigning.Enabled != nil {
			f0.Enabled = *r.ko.Spec.BrowserSigning.Enabled
		}
		res.BrowserSigning = f0
	}
	if r.ko.Spec.Certificates != nil {
		f1 := []svcsdktypes.Certificate{}
		for _, f1iter := range r.ko.Spec.Certificates {
			f1elem := &svcsdktypes.Certificate{}
			if f1iter.Location != nil {
				var f1elemf0 svcsdktypes.CertificateLocation
				isInterfaceSet := false
				if f1iter.Location.SecretsManager != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for SecretsManager"))
					}
					f1elemf0f0Parent := &svcsdktypes.CertificateLocationMemberSecretsManager{}
					f1elemf0f0 := &svcsdktypes.SecretsManagerLocation{}
					if f1iter.Location.SecretsManager.SecretARN != nil {
						f1elemf0f0.SecretArn = f1iter.Location.SecretsManager.SecretARN
					}
					f1elemf0f0Parent.Value = *f1elemf0f0
					f1elemf0 = f1elemf0f0Parent
					isInterfaceSet = true
				}
				f1elem.Location = f1elemf0
			}
			f1 = append(f1, *f1elem)
		}
		res.Certificates = f1
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EnterprisePolicies != nil {
		f4 := []svcsdktypes.BrowserEnterprisePolicy{}
		for _, f4iter := range r.ko.Spec.EnterprisePolicies {
			f4elem := &svcsdktypes.BrowserEnterprisePolicy{}
			if f4iter.Location != nil {
				var f4elemf0 svcsdktypes.ResourceLocation
				isInterfaceSet := false
				if f4iter.Location.S3 != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
					}
					f4elemf0f0Parent := &svcsdktypes.ResourceLocationMemberS3{}
					f4elemf0f0 := &svcsdktypes.S3Location{}
					if f4iter.Location.S3.Bucket != nil {
						f4elemf0f0.Bucket = f4iter.Location.S3.Bucket
					}
					if f4iter.Location.S3.Prefix != nil {
						f4elemf0f0.Prefix = f4iter.Location.S3.Prefix
					}
					if f4iter.Location.S3.VersionID != nil {
						f4elemf0f0.VersionId = f4iter.Location.S3.VersionID
					}
					f4elemf0f0Parent.Value = *f4elemf0f0
					f4elemf0 = f4elemf0f0Parent
					isInterfaceSet = true
				}
				f4elem.Location = f4elemf0
			}
			if f4iter.Type != nil {
				f4elem.Type = svcsdktypes.BrowserEnterprisePolicyType(*f4iter.Type)
			}
			f4 = append(f4, *f4elem)
		}
		res.EnterprisePolicies = f4
	}
	if r.ko.Spec.ExecutionRoleARN != nil {
		res.ExecutionRoleArn = r.ko.Spec.ExecutionRoleARN
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f7 := &svcsdktypes.BrowserNetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.NetworkMode != nil {
			f7.NetworkMode = svcsdktypes.BrowserNetworkMode(*r.ko.Spec.NetworkConfiguration.NetworkMode)
		}
		if r.ko.Spec.NetworkConfiguration.VPCConfig != nil {
			f7f1 := &svcsdktypes.VpcConfig{}
			if r.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups != nil {
				f7f1.SecurityGroups = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups)
			}
			if r.ko.Spec.NetworkConfiguration.VPCConfig.Subnets != nil {
				f7f1.Subnets = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.VPCConfig.Subnets)
			}
			f7.VpcConfig = f7f1
		}
		res.NetworkConfiguration = f7
	}
	if r.ko.Spec.Recording != nil {
		f8 := &svcsdktypes.RecordingConfig{}
		if r.ko.Spec.Recording.Enabled != nil {
			f8.Enabled = *r.ko.Spec.Recording.Enabled
		}
		if r.ko.Spec.Recording.S3Location != nil {
			f8f1 := &svcsdktypes.S3Location{}
			if r.ko.Spec.Recording.S3Location.Bucket != nil {
				f8f1.Bucket = r.ko.Spec.Recording.S3Location.Bucket
			}
			if r.ko.Spec.Recording.S3Location.Prefix != nil {
				f8f1.Prefix = r.ko.Spec.Recording.S3Location.Prefix
			}
			if r.ko.Spec.Recording.S3Location.VersionID != nil {
				f8f1.VersionId = r.ko.Spec.Recording.S3Location.VersionID
			}
			f8.S3Location = f8f1
		}
		res.Recording = f8
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdate(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if r.ko.Status.Status != nil {
		if !ackutil.InStrings(*r.ko.Status.Status, []string{"READY", "CREATE_FAILED", "DELETE_FAILED"}) {
			return nil, ackrequeue.NeededAfter(
				fmt.Errorf("resource is in %s state, cannot be deleted",
					*r.ko.Status.Status),
				time.Duration(30)*time.Second,
			)
		}
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteBrowserOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteBrowser(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteBrowser", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteBrowserInput, error) {
	res := &svcsdk.DeleteBrowserInput{}

	if r.ko.Status.BrowserID != nil {
		res.BrowserId = r.ko.Status.BrowserID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Browser,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"ConflictException":
		return true
	default:
		return false
	}
}
