// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ApiKeyCredentialProviderSpec defines the desired state of ApiKeyCredentialProvider.
type APIKeyCredentialProviderSpec struct {

	// The API key to use for authentication. This value is encrypted and stored
	// securely.
	// +kubebuilder:validation:Required
	APIKey *ackv1alpha1.SecretKeyReference `json:"apiKey"`
	// The name of the API key credential provider. The name must be unique within
	// your account.
	//
	// Regex Pattern: `^[a-zA-Z0-9\-_]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// A map of tag keys and values to assign to the API key credential provider.
	// Tags enable you to categorize your resources in different ways, for example,
	// by purpose, owner, or environment.
	Tags map[string]*string `json:"tags,omitempty"`
}

// APIKeyCredentialProviderStatus defines the observed state of APIKeyCredentialProvider
type APIKeyCredentialProviderStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The Amazon Resource Name (ARN) of the secret containing the API key.
	// +kubebuilder:validation:Optional
	APIKeySecretARN *Secret `json:"apiKeySecretARN,omitempty"`
}

// APIKeyCredentialProvider is the Schema for the APIKeyCredentialProviders API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type APIKeyCredentialProvider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              APIKeyCredentialProviderSpec   `json:"spec,omitempty"`
	Status            APIKeyCredentialProviderStatus `json:"status,omitempty"`
}

// APIKeyCredentialProviderList contains a list of APIKeyCredentialProvider
// +kubebuilder:object:root=true
type APIKeyCredentialProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []APIKeyCredentialProvider `json:"items"`
}

func init() {
	SchemeBuilder.Register(&APIKeyCredentialProvider{}, &APIKeyCredentialProviderList{})
}
