// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BrowserProfileSpec defines the desired state of BrowserProfile.
type BrowserProfileSpec struct {

	// A description of the browser profile. Use this field to describe the purpose
	// or contents of the profile.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	Description *string `json:"description,omitempty"`
	// The name of the browser profile. The name must be unique within your account
	// and can contain alphanumeric characters and underscores.
	//
	// Regex Pattern: `^[a-zA-Z][a-zA-Z0-9_]{0,47}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// A map of tag keys and values to assign to the browser profile. Tags enable
	// you to categorize your resources in different ways, for example, by purpose,
	// owner, or environment.
	Tags map[string]*string `json:"tags,omitempty"`
}

// BrowserProfileStatus defines the observed state of BrowserProfile
type BrowserProfileStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the browser profile was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The unique identifier of the created browser profile.
	//
	// Regex Pattern: `^[a-zA-Z][a-zA-Z0-9_]{0,47}-[a-zA-Z0-9]{10}$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The timestamp when browser session data was last saved to this profile.
	// +kubebuilder:validation:Optional
	LastSavedAt *metav1.Time `json:"lastSavedAt,omitempty"`
	// The identifier of the browser from which data was last saved to this profile.
	//
	// Regex Pattern: `^(aws\.browser\.v1|[a-zA-Z][a-zA-Z0-9_]{0,47}-[a-zA-Z0-9]{10})$`
	// +kubebuilder:validation:Optional
	LastSavedBrowserID *string `json:"lastSavedBrowserID,omitempty"`
	// The identifier of the browser session from which data was last saved to this
	// profile.
	//
	// Regex Pattern: `^[0-9a-zA-Z]{1,40}$`
	// +kubebuilder:validation:Optional
	LastSavedBrowserSessionID *string `json:"lastSavedBrowserSessionID,omitempty"`
	// The timestamp when the browser profile was last updated.
	// +kubebuilder:validation:Optional
	LastUpdatedAt *metav1.Time `json:"lastUpdatedAt,omitempty"`
	// The current status of the browser profile.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// BrowserProfile is the Schema for the BrowserProfiles API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type BrowserProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BrowserProfileSpec   `json:"spec,omitempty"`
	Status            BrowserProfileStatus `json:"status,omitempty"`
}

// BrowserProfileList contains a list of BrowserProfile
// +kubebuilder:object:root=true
type BrowserProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BrowserProfile `json:"items"`
}

func init() {
	SchemeBuilder.Register(&BrowserProfile{}, &BrowserProfileList{})
}
