// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type APIKeyCredentialLocation string

const (
	APIKeyCredentialLocation_HEADER          APIKeyCredentialLocation = "HEADER"
	APIKeyCredentialLocation_QUERY_PARAMETER APIKeyCredentialLocation = "QUERY_PARAMETER"
)

type AgentRuntimeEndpointStatus string

const (
	AgentRuntimeEndpointStatus_CREATE_FAILED AgentRuntimeEndpointStatus = "CREATE_FAILED"
	AgentRuntimeEndpointStatus_CREATING      AgentRuntimeEndpointStatus = "CREATING"
	AgentRuntimeEndpointStatus_DELETING      AgentRuntimeEndpointStatus = "DELETING"
	AgentRuntimeEndpointStatus_READY         AgentRuntimeEndpointStatus = "READY"
	AgentRuntimeEndpointStatus_UPDATE_FAILED AgentRuntimeEndpointStatus = "UPDATE_FAILED"
	AgentRuntimeEndpointStatus_UPDATING      AgentRuntimeEndpointStatus = "UPDATING"
)

type AgentRuntimeStatus_SDK string

const (
	AgentRuntimeStatus_SDK_CREATE_FAILED AgentRuntimeStatus_SDK = "CREATE_FAILED"
	AgentRuntimeStatus_SDK_CREATING      AgentRuntimeStatus_SDK = "CREATING"
	AgentRuntimeStatus_SDK_DELETING      AgentRuntimeStatus_SDK = "DELETING"
	AgentRuntimeStatus_SDK_READY         AgentRuntimeStatus_SDK = "READY"
	AgentRuntimeStatus_SDK_UPDATE_FAILED AgentRuntimeStatus_SDK = "UPDATE_FAILED"
	AgentRuntimeStatus_SDK_UPDATING      AgentRuntimeStatus_SDK = "UPDATING"
)

type AuthorizerType string

const (
	AuthorizerType_CUSTOM_JWT AuthorizerType = "CUSTOM_JWT"
)

type BrowserNetworkMode string

const (
	BrowserNetworkMode_PUBLIC BrowserNetworkMode = "PUBLIC"
	BrowserNetworkMode_VPC    BrowserNetworkMode = "VPC"
)

type BrowserStatus string

const (
	BrowserStatus_CREATE_FAILED BrowserStatus = "CREATE_FAILED"
	BrowserStatus_CREATING      BrowserStatus = "CREATING"
	BrowserStatus_DELETED       BrowserStatus = "DELETED"
	BrowserStatus_DELETE_FAILED BrowserStatus = "DELETE_FAILED"
	BrowserStatus_DELETING      BrowserStatus = "DELETING"
	BrowserStatus_READY         BrowserStatus = "READY"
)

type CodeInterpreterNetworkMode string

const (
	CodeInterpreterNetworkMode_PUBLIC  CodeInterpreterNetworkMode = "PUBLIC"
	CodeInterpreterNetworkMode_SANDBOX CodeInterpreterNetworkMode = "SANDBOX"
	CodeInterpreterNetworkMode_VPC     CodeInterpreterNetworkMode = "VPC"
)

type CodeInterpreterStatus string

const (
	CodeInterpreterStatus_CREATE_FAILED CodeInterpreterStatus = "CREATE_FAILED"
	CodeInterpreterStatus_CREATING      CodeInterpreterStatus = "CREATING"
	CodeInterpreterStatus_DELETED       CodeInterpreterStatus = "DELETED"
	CodeInterpreterStatus_DELETE_FAILED CodeInterpreterStatus = "DELETE_FAILED"
	CodeInterpreterStatus_DELETING      CodeInterpreterStatus = "DELETING"
	CodeInterpreterStatus_READY         CodeInterpreterStatus = "READY"
)

type CredentialProviderType string

const (
	CredentialProviderType_API_KEY          CredentialProviderType = "API_KEY"
	CredentialProviderType_GATEWAY_IAM_ROLE CredentialProviderType = "GATEWAY_IAM_ROLE"
	CredentialProviderType_OAUTH            CredentialProviderType = "OAUTH"
)

type CredentialProviderVendorType string

const (
	CredentialProviderVendorType_CustomOauth2     CredentialProviderVendorType = "CustomOauth2"
	CredentialProviderVendorType_GithubOauth2     CredentialProviderVendorType = "GithubOauth2"
	CredentialProviderVendorType_GoogleOauth2     CredentialProviderVendorType = "GoogleOauth2"
	CredentialProviderVendorType_MicrosoftOauth2  CredentialProviderVendorType = "MicrosoftOauth2"
	CredentialProviderVendorType_SalesforceOauth2 CredentialProviderVendorType = "SalesforceOauth2"
	CredentialProviderVendorType_SlackOauth2      CredentialProviderVendorType = "SlackOauth2"
)

type ExceptionLevel string

const (
	ExceptionLevel_DEBUG ExceptionLevel = "DEBUG"
)

type GatewayProtocolType string

const (
	GatewayProtocolType_MCP GatewayProtocolType = "MCP"
)

type GatewayStatus string

const (
	GatewayStatus_CREATING            GatewayStatus = "CREATING"
	GatewayStatus_DELETING            GatewayStatus = "DELETING"
	GatewayStatus_FAILED              GatewayStatus = "FAILED"
	GatewayStatus_READY               GatewayStatus = "READY"
	GatewayStatus_UPDATE_UNSUCCESSFUL GatewayStatus = "UPDATE_UNSUCCESSFUL"
	GatewayStatus_UPDATING            GatewayStatus = "UPDATING"
)

type KeyType string

const (
	KeyType_CustomerManagedKey KeyType = "CustomerManagedKey"
	KeyType_ServiceManagedKey  KeyType = "ServiceManagedKey"
)

type MemoryStatus string

const (
	MemoryStatus_ACTIVE   MemoryStatus = "ACTIVE"
	MemoryStatus_CREATING MemoryStatus = "CREATING"
	MemoryStatus_DELETING MemoryStatus = "DELETING"
	MemoryStatus_FAILED   MemoryStatus = "FAILED"
)

type MemoryStrategyStatus string

const (
	MemoryStrategyStatus_ACTIVE   MemoryStrategyStatus = "ACTIVE"
	MemoryStrategyStatus_CREATING MemoryStrategyStatus = "CREATING"
	MemoryStrategyStatus_DELETING MemoryStrategyStatus = "DELETING"
	MemoryStrategyStatus_FAILED   MemoryStrategyStatus = "FAILED"
)

type MemoryStrategyType string

const (
	MemoryStrategyType_CUSTOM          MemoryStrategyType = "CUSTOM"
	MemoryStrategyType_SEMANTIC        MemoryStrategyType = "SEMANTIC"
	MemoryStrategyType_SUMMARIZATION   MemoryStrategyType = "SUMMARIZATION"
	MemoryStrategyType_USER_PREFERENCE MemoryStrategyType = "USER_PREFERENCE"
)

type NetworkMode string

const (
	NetworkMode_PUBLIC NetworkMode = "PUBLIC"
	NetworkMode_VPC    NetworkMode = "VPC"
)

type OverrideType string

const (
	OverrideType_SEMANTIC_OVERRIDE        OverrideType = "SEMANTIC_OVERRIDE"
	OverrideType_SUMMARY_OVERRIDE         OverrideType = "SUMMARY_OVERRIDE"
	OverrideType_USER_PREFERENCE_OVERRIDE OverrideType = "USER_PREFERENCE_OVERRIDE"
)

type ResourceType string

const (
	ResourceType_CUSTOM ResourceType = "CUSTOM"
	ResourceType_SYSTEM ResourceType = "SYSTEM"
)

type SchemaType string

const (
	SchemaType_array   SchemaType = "array"
	SchemaType_boolean SchemaType = "boolean"
	SchemaType_integer SchemaType = "integer"
	SchemaType_number  SchemaType = "number"
	SchemaType_object  SchemaType = "object"
	SchemaType_string  SchemaType = "string"
)

type SearchType string

const (
	SearchType_SEMANTIC SearchType = "SEMANTIC"
)

type ServerProtocol string

const (
	ServerProtocol_HTTP ServerProtocol = "HTTP"
	ServerProtocol_MCP  ServerProtocol = "MCP"
)

type TargetStatus string

const (
	TargetStatus_CREATING            TargetStatus = "CREATING"
	TargetStatus_DELETING            TargetStatus = "DELETING"
	TargetStatus_FAILED              TargetStatus = "FAILED"
	TargetStatus_READY               TargetStatus = "READY"
	TargetStatus_UPDATE_UNSUCCESSFUL TargetStatus = "UPDATE_UNSUCCESSFUL"
	TargetStatus_UPDATING            TargetStatus = "UPDATING"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_CannotParse                          ValidationExceptionReason = "CannotParse"
	ValidationExceptionReason_EventInOtherSession                  ValidationExceptionReason = "EventInOtherSession"
	ValidationExceptionReason_FieldValidationFailed                ValidationExceptionReason = "FieldValidationFailed"
	ValidationExceptionReason_IdempotentParameterMismatchException ValidationExceptionReason = "IdempotentParameterMismatchException"
	ValidationExceptionReason_ResourceConflict                     ValidationExceptionReason = "ResourceConflict"
)
