// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MemorySpec defines the desired state of Memory.
//
// Contains information about a memory resource.
type MemorySpec struct {

	// The description of the memory.
	Description *string `json:"description,omitempty"`
	// The Amazon Resource Name (ARN) of the KMS key used to encrypt the memory
	// data.
	//
	// Regex Pattern: `^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	EncryptionKeyARN *string `json:"encryptionKeyARN,omitempty"`
	// The duration after which memory events expire. Specified as an ISO 8601 duration.
	// +kubebuilder:validation:Required
	EventExpiryDuration *int64 `json:"eventExpiryDuration"`
	// The Amazon Resource Name (ARN) of the IAM role that provides permissions
	// for the memory to access Amazon Web Services services.
	//
	// Regex Pattern: `^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$`
	MemoryExecutionRoleARN *string `json:"memoryExecutionRoleARN,omitempty"`
	// The memory strategies to use for this memory. Strategies define how information
	// is extracted, processed, and consolidated.
	MemoryStrategies []*MemoryStrategyInput `json:"memoryStrategies,omitempty"`
	// The name of the memory. The name must be unique within your account.
	//
	// Regex Pattern: `^[a-zA-Z][a-zA-Z0-9_]{0,47}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// A map of tag keys and values to assign to an AgentCore Memory. Tags enable
	// you to categorize your resources in different ways, for example, by purpose,
	// owner, or environment.
	Tags map[string]*string `json:"tags,omitempty"`
}

// MemoryStatus defines the observed state of Memory
type MemoryStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the memory was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The reason for failure if the memory is in a failed state.
	// +kubebuilder:validation:Optional
	FailureReason *string `json:"failureReason,omitempty"`
	// The unique identifier of the memory.
	//
	// Regex Pattern: `^[a-zA-Z][a-zA-Z0-9-_]{0,99}-[a-zA-Z0-9]{10}$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The current status of the memory.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The list of memory strategies associated with this memory.
	// +kubebuilder:validation:Optional
	Strategies []*MemoryStrategy `json:"strategies,omitempty"`
	// The timestamp when the memory was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// Memory is the Schema for the Memories API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Memory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MemorySpec   `json:"spec,omitempty"`
	Status            MemoryStatus `json:"status,omitempty"`
}

// MemoryList contains a list of Memory
// +kubebuilder:object:root=true
type MemoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Memory `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Memory{}, &MemoryList{})
}
