// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PolicyEngineSpec defines the desired state of PolicyEngine.
//
// Represents a policy engine resource within the AgentCore Policy system. Policy
// engines serve as containers for grouping related policies and provide the
// execution context for policy evaluation and management. Each policy engine
// can be associated with one Gateway (one engine per Gateway), where it intercepts
// all agent tool calls and evaluates them against the contained policies before
// allowing tools to execute. The policy engine maintains the Cedar schema generated
// from the Gateway's tool manifest, ensuring that policies are validated against
// the actual tools and parameters available. Policy engines support two enforcement
// modes that can be configured when associating with a Gateway: log-only mode
// for testing (evaluates decisions without blocking) and enforce mode for production
// (actively allows or denies based on policy evaluation).
type PolicyEngineSpec struct {

	// A human-readable description of the policy engine's purpose and scope (1-4,096
	// characters). This helps administrators understand the policy engine's role
	// in the overall governance strategy. Document which Gateway this engine will
	// be associated with, what types of tools or workflows it governs, and the
	// team or service responsible for maintaining it. Clear descriptions are essential
	// when managing multiple policy engines across different services or environments.
	Description *string `json:"description,omitempty"`
	// The Amazon Resource Name (ARN) of the KMS key used to encrypt the policy
	// engine data.
	//
	// Regex Pattern: `^arn:aws(|-cn|-us-gov):kms:[a-zA-Z0-9-]*:[0-9]{12}:key/[a-zA-Z0-9-]{36}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	EncryptionKeyARN *string                                  `json:"encryptionKeyARN,omitempty"`
	EncryptionKeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"encryptionKeyRef,omitempty"`
	// The customer-assigned immutable name for the policy engine. This name identifies
	// the policy engine and cannot be changed after creation.
	//
	// Regex Pattern: `^[A-Za-z][A-Za-z0-9_]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// A map of tag keys and values to assign to an AgentCore Policy. Tags enable
	// you to categorize your resources in different ways, for example, by purpose,
	// owner, or environment.
	Tags map[string]*string `json:"tags,omitempty"`
}

// PolicyEngineStatus defines the observed state of PolicyEngine
type PolicyEngineStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the policy engine was originally created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The unique identifier for the created policy engine. This system-generated
	// identifier consists of the user name plus a 10-character generated suffix
	// and is used for all subsequent policy engine operations.
	//
	// Regex Pattern: `^[A-Za-z][A-Za-z0-9_]*-[a-z0-9_]{10}$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The current status of the policy engine. A status of ACTIVE indicates the
	// policy engine is ready for use.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// Additional information about the policy engine status. This provides details
	// about any failures or the current state of the policy engine.
	// +kubebuilder:validation:Optional
	StatusReasons []*string `json:"statusReasons,omitempty"`
	// The timestamp when the policy engine was last modified. This tracks the most
	// recent changes to the policy engine configuration.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// PolicyEngine is the Schema for the PolicyEngines API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type PolicyEngine struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PolicyEngineSpec   `json:"spec,omitempty"`
	Status            PolicyEngineStatus `json:"status,omitempty"`
}

// PolicyEngineList contains a list of PolicyEngine
// +kubebuilder:object:root=true
type PolicyEngineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyEngine `json:"items"`
}

func init() {
	SchemeBuilder.Register(&PolicyEngine{}, &PolicyEngineList{})
}
