// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PolicySpec defines the desired state of Policy.
//
// Represents a complete policy resource within the AgentCore Policy system.
// Policies are ARN-able resources that contain Cedar policy statements and
// associated metadata for controlling agent behavior and access decisions.
// Each policy belongs to a policy engine and defines fine-grained authorization
// rules that are evaluated in real-time as agents interact with tools through
// Gateway. Policies use the Cedar policy language to specify who (principals
// based on OAuth claims like username, role, or scope) can perform what actions
// (tool calls) on which resources (Gateways), with optional conditions for
// attribute-based access control. Multiple policies can apply to a single request,
// with Cedar's forbid-wins semantics ensuring that security restrictions are
// never accidentally overridden.
type PolicySpec struct {

	// The Cedar policy statement that defines the access control rules. This contains
	// the actual policy logic written in Cedar policy language, specifying effect
	// (permit or forbid), principals, actions, resources, and conditions for agent
	// behavior control.
	// +kubebuilder:validation:Required
	Definition *PolicyDefinition `json:"definition"`
	// A human-readable description of the policy's purpose and functionality (1-4,096
	// characters). This helps policy administrators understand the policy's intent,
	// business rules, and operational scope. Use this field to document why the
	// policy exists, what business requirement it addresses, and any special considerations
	// for maintenance. Clear descriptions are essential for policy governance,
	// auditing, and troubleshooting.
	Description *string `json:"description,omitempty"`
	// The customer-assigned immutable name for the policy. Must be unique within
	// the account. This name is used for policy identification and cannot be changed
	// after creation.
	//
	// Regex Pattern: `^[A-Za-z][A-Za-z0-9_]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The identifier of the policy engine which contains this policy. Policy engines
	// group related policies and provide the execution context for policy evaluation.
	//
	// Regex Pattern: `^[A-Za-z][A-Za-z0-9_]*-[a-z0-9_]{10}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	PolicyEngineID  *string                                  `json:"policyEngineID,omitempty"`
	PolicyEngineRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"policyEngineRef,omitempty"`
	// The validation mode for the policy creation. Determines how Cedar analyzer
	// validation results are handled during policy creation. FAIL_ON_ANY_FINDINGS
	// (default) runs the Cedar analyzer to validate the policy against the Cedar
	// schema and tool context, failing creation if the analyzer detects any validation
	// issues to ensure strict conformance. IGNORE_ALL_FINDINGS runs the Cedar analyzer
	// but allows policy creation even if validation issues are detected, useful
	// for testing or when the policy schema is evolving. Use FAIL_ON_ANY_FINDINGS
	// for production policies to ensure correctness, and IGNORE_ALL_FINDINGS only
	// when you understand and accept the analyzer findings.
	ValidationMode *string `json:"validationMode,omitempty"`
}

// PolicyStatus defines the observed state of Policy
type PolicyStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the policy was originally created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The unique identifier for the created policy. This is a system-generated
	// identifier consisting of the user name plus a 10-character generated suffix,
	// used for all subsequent policy operations.
	//
	// Regex Pattern: `^[A-Za-z][A-Za-z0-9_]*-[a-z0-9_]{10}$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The current status of the policy. A status of ACTIVE indicates the policy
	// is ready for use.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// Additional information about the policy status. This provides details about
	// any failures or the current state of the policy.
	// +kubebuilder:validation:Optional
	StatusReasons []*string `json:"statusReasons,omitempty"`
	// The timestamp when the policy was last modified. This tracks the most recent
	// changes to the policy configuration.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// Policy is the Schema for the Policies API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PolicySpec   `json:"spec,omitempty"`
	Status            PolicyStatus `json:"status,omitempty"`
}

// PolicyList contains a list of Policy
// +kubebuilder:object:root=true
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Policy{}, &PolicyList{})
}
