// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// The configuration for an Amazon API Gateway target.
type APIGatewayTargetConfiguration struct {
	RestAPIID *string `json:"restAPIID,omitempty"`
	Stage     *string `json:"stage,omitempty"`
}

// Specifies which operations from an API Gateway REST API are exposed as tools.
// Tool names and descriptions are derived from the operationId and description
// fields in the API's exported OpenAPI specification.
type APIGatewayToolFilter struct {
	FilterPath *string `json:"filterPath,omitempty"`
}

// Settings to override configurations for a tool.
type APIGatewayToolOverride struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Path        *string `json:"path,omitempty"`
}

// Contains information about an API key credential provider.
type APIKeyCredentialProviderItem struct {
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// The artifact of the agent.
type AgentRuntimeArtifact struct {
	// The configuration for the source code that defines how the agent runtime
	// code should be executed, including the code location, runtime environment,
	// and entry point.
	CodeConfiguration *CodeConfiguration `json:"codeConfiguration,omitempty"`
	// Representation of a container configuration.
	ContainerConfiguration *ContainerConfiguration `json:"containerConfiguration,omitempty"`
}

// Contains information about an agent runtime endpoint. An endpoint provides
// a way to connect to and interact with an agent runtime.
type AgentRuntimeEndpoint_SDK struct {
	AgentRuntimeARN         *string      `json:"agentRuntimeARN,omitempty"`
	AgentRuntimeEndpointARN *string      `json:"agentRuntimeEndpointARN,omitempty"`
	CreatedAt               *metav1.Time `json:"createdAt,omitempty"`
	Description             *string      `json:"description,omitempty"`
	ID                      *string      `json:"id,omitempty"`
	LastUpdatedAt           *metav1.Time `json:"lastUpdatedAt,omitempty"`
	LiveVersion             *string      `json:"liveVersion,omitempty"`
	Name                    *string      `json:"name,omitempty"`
	Status                  *string      `json:"status,omitempty"`
	TargetVersion           *string      `json:"targetVersion,omitempty"`
}

// Contains information about an agent runtime. An agent runtime is the execution
// environment for a Amazon Bedrock AgentCore Agent.
type AgentRuntime_SDK struct {
	AgentRuntimeARN     *string      `json:"agentRuntimeARN,omitempty"`
	AgentRuntimeID      *string      `json:"agentRuntimeID,omitempty"`
	AgentRuntimeName    *string      `json:"agentRuntimeName,omitempty"`
	AgentRuntimeVersion *string      `json:"agentRuntimeVersion,omitempty"`
	Description         *string      `json:"description,omitempty"`
	LastUpdatedAt       *metav1.Time `json:"lastUpdatedAt,omitempty"`
	Status              *string      `json:"status,omitempty"`
}

// Represents inbound authorization configuration options used to authenticate
// incoming requests.
type AuthorizerConfiguration struct {
	// Configuration for inbound JWT-based authorization, specifying how incoming
	// requests should be authenticated.
	CustomJWTAuthorizer *CustomJWTAuthorizerConfiguration `json:"customJWTAuthorizer,omitempty"`
}

// Defines the value or values to match for and the relationship of the match.
type AuthorizingClaimMatchValueType struct {
	ClaimMatchOperator *string `json:"claimMatchOperator,omitempty"`
	// The value or values to match for.
	//
	//    * Include a matchValueString with the EQUALS operator to specify a string
	//    that matches the claim field value.
	//
	//    * Include a matchValueArray to specify an array of string values. You
	//    can use the following operators: Use CONTAINS to yield a match if the
	//    claim field value is in the array. Use CONTAINS_ANY to yield a match if
	//    the claim field value contains any of the strings in the array.
	ClaimMatchValue *ClaimMatchValueType `json:"claimMatchValue,omitempty"`
}

// The network configuration for a browser. This structure defines how the browser
// connects to the network.
type BrowserNetworkConfiguration struct {
	// VpcConfig for the Agent.
	VPCConfig *VPCConfig `json:"vpcConfig,omitempty"`
}

// Contains summary information about a browser profile. A browser profile stores
// persistent browser data that can be reused across browser sessions.
type BrowserProfileSummary struct {
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	Description   *string      `json:"description,omitempty"`
	LastSavedAt   *metav1.Time `json:"lastSavedAt,omitempty"`
	LastUpdatedAt *metav1.Time `json:"lastUpdatedAt,omitempty"`
}

// Configuration for enabling browser signing capabilities that allow agents
// to cryptographically identify themselves to websites using HTTP message signatures.
type BrowserSigningConfigInput struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// The current browser signing configuration that shows whether cryptographic
// agent identification is enabled for web bot authentication.
type BrowserSigningConfigOutput struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Contains summary information about a browser. A browser enables Amazon Bedrock
// AgentCore Agent to interact with web content.
type BrowserSummary struct {
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	Description   *string      `json:"description,omitempty"`
	LastUpdatedAt *metav1.Time `json:"lastUpdatedAt,omitempty"`
}

// The definition of a categorical rating scale option that provides a named
// category with its description for evaluation scoring.
type CategoricalScaleDefinition struct {
	Definition *string `json:"definition,omitempty"`
	Label      *string `json:"label,omitempty"`
}

// The value or values to match for.
//
//   - Include a matchValueString with the EQUALS operator to specify a string
//     that matches the claim field value.
//
//   - Include a matchValueArray to specify an array of string values. You
//     can use the following operators: Use CONTAINS to yield a match if the
//     claim field value is in the array. Use CONTAINS_ANY to yield a match if
//     the claim field value contains any of the strings in the array.
type ClaimMatchValueType struct {
	MatchValueString     *string   `json:"matchValueString,omitempty"`
	MatchValueStringList []*string `json:"matchValueStringList,omitempty"`
}

// The source code configuration that specifies the location and details of
// the code to be executed.
type Code struct {
	// The Amazon S3 location for storing data. This structure defines where in
	// Amazon S3 data is stored.
	S3 *S3Location `json:"s3,omitempty"`
}

// The configuration for the source code that defines how the agent runtime
// code should be executed, including the code location, runtime environment,
// and entry point.
type CodeConfiguration struct {
	// The source code configuration that specifies the location and details of
	// the code to be executed.
	Code       *Code     `json:"code,omitempty"`
	EntryPoint []*string `json:"entryPoint,omitempty"`
	Runtime    *string   `json:"runtime,omitempty"`
}

// The network configuration for a code interpreter. This structure defines
// how the code interpreter connects to the network.
type CodeInterpreterNetworkConfiguration struct {
	// VpcConfig for the Agent.
	VPCConfig *VPCConfig `json:"vpcConfig,omitempty"`
}

// Contains summary information about a code interpreter. A code interpreter
// enables Amazon Bedrock AgentCore Agent to execute code.
type CodeInterpreterSummary struct {
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	Description   *string      `json:"description,omitempty"`
	LastUpdatedAt *metav1.Time `json:"lastUpdatedAt,omitempty"`
}

// Contains consolidation configuration information for a memory strategy.
type ConsolidationConfiguration struct {
	// Contains custom consolidation configuration information.
	CustomConsolidationConfiguration *CustomConsolidationConfiguration `json:"customConsolidationConfiguration,omitempty"`
}

// Representation of a container configuration.
type ContainerConfiguration struct {
	ContainerURI *string `json:"containerURI,omitempty"`
}

// Defines what content to stream and at what level of detail.
type ContentConfiguration struct {
	Level *string `json:"level,omitempty"`
	Type  *string `json:"type_,omitempty"`
}

// Defines the name of a custom claim field and rules for finding matches to
// authenticate its value.
type CustomClaimValidationType struct {
	// Defines the value or values to match for and the relationship of the match.
	AuthorizingClaimMatchValue *AuthorizingClaimMatchValueType `json:"authorizingClaimMatchValue,omitempty"`
	InboundTokenClaimName      *string                         `json:"inboundTokenClaimName,omitempty"`
	InboundTokenClaimValueType *string                         `json:"inboundTokenClaimValueType,omitempty"`
}

// Input for custom configuration of a memory strategy.
type CustomConfigurationInput struct {
	// Input for the configuration to override the episodic memory strategy.
	EpisodicOverride *EpisodicOverrideConfigurationInput `json:"episodicOverride,omitempty"`
	// Input configuration for a self-managed memory strategy.
	SelfManagedConfiguration *SelfManagedConfigurationInput `json:"selfManagedConfiguration,omitempty"`
	// Input for semantic override configuration in a memory strategy.
	SemanticOverride *SemanticOverrideConfigurationInput `json:"semanticOverride,omitempty"`
	// Input for summary override configuration in a memory strategy.
	SummaryOverride *SummaryOverrideConfigurationInput `json:"summaryOverride,omitempty"`
	// Input for user preference override configuration in a memory strategy.
	UserPreferenceOverride *UserPreferenceOverrideConfigurationInput `json:"userPreferenceOverride,omitempty"`
}

// Contains custom consolidation configuration information.
type CustomConsolidationConfiguration struct {
	// Contains configurations to override the default consolidation step for the
	// episodic memory strategy.
	EpisodicConsolidationOverride *EpisodicConsolidationOverride `json:"episodicConsolidationOverride,omitempty"`
	// Contains semantic consolidation override configuration.
	SemanticConsolidationOverride *SemanticConsolidationOverride `json:"semanticConsolidationOverride,omitempty"`
	// Contains summary consolidation override configuration.
	SummaryConsolidationOverride *SummaryConsolidationOverride `json:"summaryConsolidationOverride,omitempty"`
	// Contains user preference consolidation override configuration.
	UserPreferenceConsolidationOverride *UserPreferenceConsolidationOverride `json:"userPreferenceConsolidationOverride,omitempty"`
}

// Input for a custom consolidation configuration.
type CustomConsolidationConfigurationInput struct {
	// Configurations for overriding the consolidation step of the episodic memory
	// strategy.
	EpisodicConsolidationOverride *EpisodicOverrideConsolidationConfigurationInput `json:"episodicConsolidationOverride,omitempty"`
	// Input for semantic override consolidation configuration in a memory strategy.
	SemanticConsolidationOverride *SemanticOverrideConsolidationConfigurationInput `json:"semanticConsolidationOverride,omitempty"`
	// Input for summary override consolidation configuration in a memory strategy.
	SummaryConsolidationOverride *SummaryOverrideConsolidationConfigurationInput `json:"summaryConsolidationOverride,omitempty"`
	// Input for user preference override consolidation configuration in a memory
	// strategy.
	UserPreferenceConsolidationOverride *UserPreferenceOverrideConsolidationConfigurationInput `json:"userPreferenceConsolidationOverride,omitempty"`
}

// Contains custom extraction configuration information.
type CustomExtractionConfiguration struct {
	// Contains configurations to override the default extraction step for the episodic
	// memory strategy.
	EpisodicExtractionOverride *EpisodicExtractionOverride `json:"episodicExtractionOverride,omitempty"`
	// Contains semantic extraction override configuration.
	SemanticExtractionOverride *SemanticExtractionOverride `json:"semanticExtractionOverride,omitempty"`
	// Contains user preference extraction override configuration.
	UserPreferenceExtractionOverride *UserPreferenceExtractionOverride `json:"userPreferenceExtractionOverride,omitempty"`
}

// Input for a custom extraction configuration.
type CustomExtractionConfigurationInput struct {
	// Configurations for overriding the extraction step of the episodic memory
	// strategy.
	EpisodicExtractionOverride *EpisodicOverrideExtractionConfigurationInput `json:"episodicExtractionOverride,omitempty"`
	// Input for semantic override extraction configuration in a memory strategy.
	SemanticExtractionOverride *SemanticOverrideExtractionConfigurationInput `json:"semanticExtractionOverride,omitempty"`
	// Input for user preference override extraction configuration in a memory strategy.
	UserPreferenceExtractionOverride *UserPreferenceOverrideExtractionConfigurationInput `json:"userPreferenceExtractionOverride,omitempty"`
}

// Configuration for inbound JWT-based authorization, specifying how incoming
// requests should be authenticated.
type CustomJWTAuthorizerConfiguration struct {
	AllowedAudience []*string                    `json:"allowedAudience,omitempty"`
	AllowedClients  []*string                    `json:"allowedClients,omitempty"`
	AllowedScopes   []*string                    `json:"allowedScopes,omitempty"`
	CustomClaims    []*CustomClaimValidationType `json:"customClaims,omitempty"`
	DiscoveryURL    *string                      `json:"discoveryURL,omitempty"`
}

// Input for creating a custom memory strategy.
type CustomMemoryStrategyInput struct {
	// Input for custom configuration of a memory strategy.
	Configuration      *CustomConfigurationInput `json:"configuration,omitempty"`
	Description        *string                   `json:"description,omitempty"`
	Name               *string                   `json:"name,omitempty"`
	NamespaceTemplates []*string                 `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string                 `json:"namespaces,omitempty"`
}

// Contains configurations for a custom reflection strategy.
type CustomReflectionConfiguration struct {
	// Contains configurations to override the default reflection step for the episodic
	// memory strategy.
	EpisodicReflectionOverride *EpisodicReflectionOverride `json:"episodicReflectionOverride,omitempty"`
}

// Input for a custom reflection configuration.
type CustomReflectionConfigurationInput struct {
	// Configurations for overriding the reflection step of the episodic memory
	// strategy.
	EpisodicReflectionOverride *EpisodicOverrideReflectionConfigurationInput `json:"episodicReflectionOverride,omitempty"`
}

// Input for deleting a memory strategy.
type DeleteMemoryStrategyInput struct {
	MemoryStrategyID *string `json:"memoryStrategyID,omitempty"`
}

// Contains configurations to override the default consolidation step for the
// episodic memory strategy.
type EpisodicConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Contains configurations to override the default extraction step for the episodic
// memory strategy.
type EpisodicExtractionOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating an episodic memory strategy.
type EpisodicMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
	// An episodic reflection configuration input.
	ReflectionConfiguration *EpisodicReflectionConfigurationInput `json:"reflectionConfiguration,omitempty"`
}

// Input for the configuration to override the episodic memory strategy.
type EpisodicOverrideConfigurationInput struct {
	// Configurations for overriding the consolidation step of the episodic memory
	// strategy.
	Consolidation *EpisodicOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
	// Configurations for overriding the extraction step of the episodic memory
	// strategy.
	Extraction *EpisodicOverrideExtractionConfigurationInput `json:"extraction,omitempty"`
	// Configurations for overriding the reflection step of the episodic memory
	// strategy.
	Reflection *EpisodicOverrideReflectionConfigurationInput `json:"reflection,omitempty"`
}

// Configurations for overriding the consolidation step of the episodic memory
// strategy.
type EpisodicOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Configurations for overriding the extraction step of the episodic memory
// strategy.
type EpisodicOverrideExtractionConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Configurations for overriding the reflection step of the episodic memory
// strategy.
type EpisodicOverrideReflectionConfigurationInput struct {
	AppendToPrompt     *string   `json:"appendToPrompt,omitempty"`
	ModelID            *string   `json:"modelID,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// The configuration for the reflections created with the episodic memory strategy.
type EpisodicReflectionConfiguration struct {
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// An episodic reflection configuration input.
type EpisodicReflectionConfigurationInput struct {
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Contains configurations to override the default reflection step for the episodic
// memory strategy.
type EpisodicReflectionOverride struct {
	AppendToPrompt     *string   `json:"appendToPrompt,omitempty"`
	ModelID            *string   `json:"modelID,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// The summary information about an evaluator, including basic metadata and
// status information.
type EvaluatorSummary struct {
	CreatedAt             *metav1.Time `json:"createdAt,omitempty"`
	LockedForModification *bool        `json:"lockedForModification,omitempty"`
	UpdatedAt             *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains extraction configuration information for a memory strategy.
type ExtractionConfiguration struct {
	// Contains custom extraction configuration information.
	CustomExtractionConfiguration *CustomExtractionConfiguration `json:"customExtractionConfiguration,omitempty"`
}

// Configuration for a filesystem that can be mounted into the AgentCore Runtime.
type FilesystemConfiguration struct {
	// Configuration for a session storage filesystem mounted into the AgentCore
	// Runtime. Session storage provides persistent storage that is preserved across
	// AgentCore Runtime session invocations.
	SessionStorage *SessionStorageConfiguration `json:"sessionStorage,omitempty"`
}

// The filter that applies conditions to agent traces during online evaluation
// to determine which traces should be evaluated.
type Filter struct {
	Key *string `json:"key,omitempty"`
}

// The value used in filter comparisons, supporting different data types for
// flexible filtering criteria.
type FilterValue struct {
	BooleanValue *bool   `json:"booleanValue,omitempty"`
	StringValue  *string `json:"stringValue,omitempty"`
}

// Represents a finding or issue discovered during policy generation or validation.
// Findings provide insights about potential problems, recommendations, or validation
// results from policy analysis operations. Finding types include: VALID (policy
// is ready to use), INVALID (policy has validation errors that must be fixed),
// NOT_TRANSLATABLE (input couldn't be converted to policy), ALLOW_ALL (policy
// would allow all actions, potential security risk), ALLOW_NONE (policy would
// allow no actions, unusable), DENY_ALL (policy would deny all actions, may
// be too restrictive), and DENY_NONE (policy would deny no actions, ineffective).
// Review all findings before creating policies from generated assets to ensure
// they match your security requirements.
type Finding struct {
	Description *string `json:"description,omitempty"`
}

// Contains summary information about a gateway.
type GatewaySummary struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// The gateway target.
type GatewayTarget struct {
	CreatedAt          *metav1.Time `json:"createdAt,omitempty"`
	LastSynchronizedAt *metav1.Time `json:"lastSynchronizedAt,omitempty"`
	UpdatedAt          *metav1.Time `json:"updatedAt,omitempty"`
}

// The configuration parameters that control how the foundation model behaves
// during evaluation, including response generation settings.
type InferenceConfiguration struct {
	MaxTokens *int64 `json:"maxTokens,omitempty"`
}

// The input configuration of the interceptor.
type InterceptorInputConfiguration struct {
	PassRequestHeaders *bool `json:"passRequestHeaders,omitempty"`
}

// The configuration to invoke a self-managed memory processing pipeline with.
type InvocationConfiguration struct {
	PayloadDeliveryBucketName *string `json:"payloadDeliveryBucketName,omitempty"`
	TopicARN                  *string `json:"topicARN,omitempty"`
}

// The configuration to invoke a self-managed memory processing pipeline with.
type InvocationConfigurationInput struct {
	PayloadDeliveryBucketName *string `json:"payloadDeliveryBucketName,omitempty"`
	TopicARN                  *string `json:"topicARN,omitempty"`
	// Reference field for TopicARN
	TopicRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"topicRef,omitempty"`
}

// Configuration for Kinesis Data Stream delivery.
type KinesisResource struct {
	ContentConfigurations []*ContentConfiguration `json:"contentConfigurations,omitempty"`
	DataStreamARN         *string                 `json:"dataStreamARN,omitempty"`
}

// LifecycleConfiguration lets you manage the lifecycle of runtime sessions
// and resources in AgentCore Runtime. This configuration helps optimize resource
// utilization by automatically cleaning up idle sessions and preventing long-running
// instances from consuming resources indefinitely.
type LifecycleConfiguration struct {
	IdleRuntimeSessionTimeout *int64 `json:"idleRuntimeSessionTimeout,omitempty"`
	MaxLifetime               *int64 `json:"maxLifetime,omitempty"`
}

// The target configuration for the MCP server.
type McpServerTargetConfiguration struct {
	Endpoint *string `json:"endpoint,omitempty"`
}

// Contains information about a memory strategy.
type MemoryStrategy struct {
	// Contains configuration information for a memory strategy.
	Configuration      *StrategyConfiguration `json:"configuration,omitempty"`
	CreatedAt          *metav1.Time           `json:"createdAt,omitempty"`
	Description        *string                `json:"description,omitempty"`
	Name               *string                `json:"name,omitempty"`
	NamespaceTemplates []*string              `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string              `json:"namespaces,omitempty"`
	Status             *string                `json:"status,omitempty"`
	StrategyID         *string                `json:"strategyID,omitempty"`
	Type               *string                `json:"type_,omitempty"`
	UpdatedAt          *metav1.Time           `json:"updatedAt,omitempty"`
}

// Contains input information for creating a memory strategy.
type MemoryStrategyInput struct {
	// Input for creating a custom memory strategy.
	CustomMemoryStrategy *CustomMemoryStrategyInput `json:"customMemoryStrategy,omitempty"`
	// Input for creating an episodic memory strategy.
	EpisodicMemoryStrategy *EpisodicMemoryStrategyInput `json:"episodicMemoryStrategy,omitempty"`
	// Input for creating a semantic memory strategy.
	SemanticMemoryStrategy *SemanticMemoryStrategyInput `json:"semanticMemoryStrategy,omitempty"`
	// Input for creating a summary memory strategy.
	SummaryMemoryStrategy *SummaryMemoryStrategyInput `json:"summaryMemoryStrategy,omitempty"`
	// Input for creating a user preference memory strategy.
	UserPreferenceMemoryStrategy *UserPreferenceMemoryStrategyInput `json:"userPreferenceMemoryStrategy,omitempty"`
}

// Contains summary information about a memory resource.
type MemorySummary struct {
	ARN       *string      `json:"arn,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	ID        *string      `json:"id,omitempty"`
	Status    *string      `json:"status,omitempty"`
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains information about a memory resource.
type Memory_SDK struct {
	ARN                    *string           `json:"arn,omitempty"`
	CreatedAt              *metav1.Time      `json:"createdAt,omitempty"`
	Description            *string           `json:"description,omitempty"`
	EncryptionKeyARN       *string           `json:"encryptionKeyARN,omitempty"`
	EventExpiryDuration    *int64            `json:"eventExpiryDuration,omitempty"`
	FailureReason          *string           `json:"failureReason,omitempty"`
	ID                     *string           `json:"id,omitempty"`
	MemoryExecutionRoleARN *string           `json:"memoryExecutionRoleARN,omitempty"`
	Name                   *string           `json:"name,omitempty"`
	Status                 *string           `json:"status,omitempty"`
	Strategies             []*MemoryStrategy `json:"strategies,omitempty"`
	// Configuration for streaming memory record data to external resources.
	StreamDeliveryResources *StreamDeliveryResources `json:"streamDeliveryResources,omitempty"`
	UpdatedAt               *metav1.Time             `json:"updatedAt,omitempty"`
}

// The trigger configuration based on a message.
type MessageBasedTrigger struct {
	MessageCount *int64 `json:"messageCount,omitempty"`
}

// The trigger configuration based on a message.
type MessageBasedTriggerInput struct {
	MessageCount *int64 `json:"messageCount,omitempty"`
}

// The configuration for updating invocation settings.
type ModifyInvocationConfigurationInput struct {
	PayloadDeliveryBucketName *string `json:"payloadDeliveryBucketName,omitempty"`
	TopicARN                  *string `json:"topicARN,omitempty"`
}

// Contains information for modifying memory strategies.
type ModifyMemoryStrategies struct {
	AddMemoryStrategies []*MemoryStrategyInput `json:"addMemoryStrategies,omitempty"`
}

// Input for modifying a memory strategy.
type ModifyMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	MemoryStrategyID   *string   `json:"memoryStrategyID,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Contains information for modifying a reflection configuration.
type ModifyReflectionConfiguration struct {
	// An episodic reflection configuration input.
	EpisodicReflectionConfiguration *EpisodicReflectionConfigurationInput `json:"episodicReflectionConfiguration,omitempty"`
}

// The configuration for updating the self-managed memory strategy.
type ModifySelfManagedConfiguration struct {
	HistoricalContextWindowSize *int64                   `json:"historicalContextWindowSize,omitempty"`
	TriggerConditions           []*TriggerConditionInput `json:"triggerConditions,omitempty"`
}

// SecurityConfig for the Agent.
type NetworkConfiguration struct {
	NetworkMode *string `json:"networkMode,omitempty"`
	// VpcConfig for the Agent.
	NetworkModeConfig *VPCConfig `json:"networkModeConfig,omitempty"`
}

// The definition of a numerical rating scale option that provides a numeric
// value with its description for evaluation scoring.
type NumericalScaleDefinition struct {
	Definition *string `json:"definition,omitempty"`
	Label      *string `json:"label,omitempty"`
}

// Contains information about an OAuth2 credential provider.
type Oauth2CredentialProviderItem struct {
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// The summary information about an online evaluation configuration, including
// basic metadata and execution status.
type OnlineEvaluationConfigSummary struct {
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	FailureReason *string      `json:"failureReason,omitempty"`
	UpdatedAt     *metav1.Time `json:"updatedAt,omitempty"`
}

// Represents a complete policy resource within the AgentCore Policy system.
// Policies are ARN-able resources that contain Cedar policy statements and
// associated metadata for controlling agent behavior and access decisions.
// Each policy belongs to a policy engine and defines fine-grained authorization
// rules that are evaluated in real-time as agents interact with tools through
// Gateway. Policies use the Cedar policy language to specify who (principals
// based on OAuth claims like username, role, or scope) can perform what actions
// (tool calls) on which resources (Gateways), with optional conditions for
// attribute-based access control. Multiple policies can apply to a single request,
// with Cedar's forbid-wins semantics ensuring that security restrictions are
// never accidentally overridden.
type Policy struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	Description *string      `json:"description,omitempty"`
	UpdatedAt   *metav1.Time `json:"updatedAt,omitempty"`
}

// Represents a policy engine resource within the AgentCore Policy system. Policy
// engines serve as containers for grouping related policies and provide the
// execution context for policy evaluation and management. Each policy engine
// can be associated with one Gateway (one engine per Gateway), where it intercepts
// all agent tool calls and evaluates them against the contained policies before
// allowing tools to execute. The policy engine maintains the Cedar schema generated
// from the Gateway's tool manifest, ensuring that policies are validated against
// the actual tools and parameters available. Policy engines support two enforcement
// modes that can be configured when associating with a Gateway: log-only mode
// for testing (evaluates decisions without blocking) and enforce mode for production
// (actively allows or denies based on policy evaluation).
type PolicyEngine struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	Description *string      `json:"description,omitempty"`
	UpdatedAt   *metav1.Time `json:"updatedAt,omitempty"`
}

// Represents a policy generation request within the AgentCore Policy system.
// Tracks the AI-powered conversion of natural language descriptions into Cedar
// policy statements, enabling users to author policies by describing authorization
// requirements in plain English. The generation process analyzes the natural
// language input along with the Gateway's tool context and Cedar schema to
// produce one or more validated policy options. Each generation request tracks
// the status of the conversion process and maintains findings about the generated
// policies, including validation results and potential issues. Generated policy
// assets remain available for one week after successful generation, allowing
// time to review and create policies from the generated options.
type PolicyGeneration struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Findings  *string      `json:"findings,omitempty"`
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// The protocol configuration for an agent runtime. This structure defines how
// the agent runtime communicates with clients.
type ProtocolConfiguration struct {
	ServerProtocol *string `json:"serverProtocol,omitempty"`
}

// The recording configuration for a browser. This structure defines how browser
// sessions are recorded.
type RecordingConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
	// The Amazon S3 location for storing data. This structure defines where in
	// Amazon S3 data is stored.
	S3Location *S3Location `json:"s3Location,omitempty"`
}

// Contains reflection configuration information for a memory strategy.
type ReflectionConfiguration struct {
	// Contains configurations for a custom reflection strategy.
	CustomReflectionConfiguration *CustomReflectionConfiguration `json:"customReflectionConfiguration,omitempty"`
	// The configuration for the reflections created with the episodic memory strategy.
	EpisodicReflectionConfiguration *EpisodicReflectionConfiguration `json:"episodicReflectionConfiguration,omitempty"`
}

// Configuration for HTTP request headers that will be passed through to the
// runtime.
type RequestHeaderConfiguration struct {
	RequestHeaderAllowlist []*string `json:"requestHeaderAllowlist,omitempty"`
}

// The location of a resource.
type ResourceLocation struct {
	// The Amazon S3 location for storing data. This structure defines where in
	// Amazon S3 data is stored.
	S3 *S3Location `json:"s3,omitempty"`
}

// Configuration for microVM metadata service settings.
type RuntimeMetadataConfiguration struct {
	RequireMMDSV2 *bool `json:"requireMMDSV2,omitempty"`
}

// The Amazon S3 location for storing data. This structure defines where in
// Amazon S3 data is stored.
type S3Location struct {
	Bucket    *string `json:"bucket,omitempty"`
	Prefix    *string `json:"prefix,omitempty"`
	VersionID *string `json:"versionID,omitempty"`
}

// A schema definition for a gateway target. This structure defines the structure
// of the API that the target exposes.
type SchemaDefinition struct {
	Description *string `json:"description,omitempty"`
}

// A configuration for a self-managed memory strategy.
type SelfManagedConfiguration struct {
	HistoricalContextWindowSize *int64 `json:"historicalContextWindowSize,omitempty"`
	// The configuration to invoke a self-managed memory processing pipeline with.
	InvocationConfiguration *InvocationConfiguration `json:"invocationConfiguration,omitempty"`
	TriggerConditions       []*TriggerCondition      `json:"triggerConditions,omitempty"`
}

// Input configuration for a self-managed memory strategy.
type SelfManagedConfigurationInput struct {
	HistoricalContextWindowSize *int64 `json:"historicalContextWindowSize,omitempty"`
	// The configuration to invoke a self-managed memory processing pipeline with.
	InvocationConfiguration *InvocationConfigurationInput `json:"invocationConfiguration,omitempty"`
	TriggerConditions       []*TriggerConditionInput      `json:"triggerConditions,omitempty"`
}

// Contains semantic consolidation override configuration.
type SemanticConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Contains semantic extraction override configuration.
type SemanticExtractionOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating a semantic memory strategy.
type SemanticMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Input for semantic override configuration in a memory strategy.
type SemanticOverrideConfigurationInput struct {
	// Input for semantic override consolidation configuration in a memory strategy.
	Consolidation *SemanticOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
	// Input for semantic override extraction configuration in a memory strategy.
	Extraction *SemanticOverrideExtractionConfigurationInput `json:"extraction,omitempty"`
}

// Input for semantic override consolidation configuration in a memory strategy.
type SemanticOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for semantic override extraction configuration in a memory strategy.
type SemanticOverrideExtractionConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// The configuration that defines how agent sessions are detected and when they
// are considered complete for evaluation.
type SessionConfig struct {
	SessionTimeoutMinutes *int64 `json:"sessionTimeoutMinutes,omitempty"`
}

// Configuration for a session storage filesystem mounted into the AgentCore
// Runtime. Session storage provides persistent storage that is preserved across
// AgentCore Runtime session invocations.
type SessionStorageConfiguration struct {
	MountPath *string `json:"mountPath,omitempty"`
}

// Contains configuration information for a memory strategy.
type StrategyConfiguration struct {
	// Contains consolidation configuration information for a memory strategy.
	Consolidation *ConsolidationConfiguration `json:"consolidation,omitempty"`
	// Contains extraction configuration information for a memory strategy.
	Extraction *ExtractionConfiguration `json:"extraction,omitempty"`
	// Contains reflection configuration information for a memory strategy.
	Reflection *ReflectionConfiguration `json:"reflection,omitempty"`
	// A configuration for a self-managed memory strategy.
	SelfManagedConfiguration *SelfManagedConfiguration `json:"selfManagedConfiguration,omitempty"`
	Type                     *string                   `json:"type_,omitempty"`
}

// Supported stream delivery resource types.
type StreamDeliveryResource struct {
	// Configuration for Kinesis Data Stream delivery.
	Kinesis *KinesisResource `json:"kinesis,omitempty"`
}

// Configuration for streaming memory record data to external resources.
type StreamDeliveryResources struct {
	Resources []*StreamDeliveryResource `json:"resources,omitempty"`
}

// Contains summary consolidation override configuration.
type SummaryConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating a summary memory strategy.
type SummaryMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Input for summary override configuration in a memory strategy.
type SummaryOverrideConfigurationInput struct {
	// Input for summary override consolidation configuration in a memory strategy.
	Consolidation *SummaryOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
}

// Input for summary override consolidation configuration in a memory strategy.
type SummaryOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Contains summary information about a gateway target. A target represents
// an endpoint that the gateway can connect to.
type TargetSummary struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// Trigger configuration based on time.
type TimeBasedTrigger struct {
	IdleSessionTimeout *int64 `json:"idleSessionTimeout,omitempty"`
}

// Trigger configuration based on time.
type TimeBasedTriggerInput struct {
	IdleSessionTimeout *int64 `json:"idleSessionTimeout,omitempty"`
}

// Trigger configuration based on tokens.
type TokenBasedTrigger struct {
	TokenCount *int64 `json:"tokenCount,omitempty"`
}

// Trigger configuration based on tokens.
type TokenBasedTriggerInput struct {
	TokenCount *int64 `json:"tokenCount,omitempty"`
}

// A tool definition for a gateway target. This structure defines a tool that
// the target exposes through the Model Context Protocol.
type ToolDefinition struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Condition that triggers memory processing.
type TriggerCondition struct {
	// The trigger configuration based on a message.
	MessageBasedTrigger *MessageBasedTrigger `json:"messageBasedTrigger,omitempty"`
	// Trigger configuration based on time.
	TimeBasedTrigger *TimeBasedTrigger `json:"timeBasedTrigger,omitempty"`
	// Trigger configuration based on tokens.
	TokenBasedTrigger *TokenBasedTrigger `json:"tokenBasedTrigger,omitempty"`
}

// Condition that triggers memory processing.
type TriggerConditionInput struct {
	// The trigger configuration based on a message.
	MessageBasedTrigger *MessageBasedTriggerInput `json:"messageBasedTrigger,omitempty"`
	// Trigger configuration based on time.
	TimeBasedTrigger *TimeBasedTriggerInput `json:"timeBasedTrigger,omitempty"`
	// Trigger configuration based on tokens.
	TokenBasedTrigger *TokenBasedTriggerInput `json:"tokenBasedTrigger,omitempty"`
}

// Wrapper for updating an optional Description field with PATCH semantics.When
// present in an update request, the description is replaced with optionalValue.When
// absent, the description is left unchanged.To unset the description, include
// the wrapper with optionalValue set to null.
type UpdatedDescription struct {
	OptionalValue *string `json:"optionalValue,omitempty"`
}

// Contains user preference consolidation override configuration.
type UserPreferenceConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Contains user preference extraction override configuration.
type UserPreferenceExtractionOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating a user preference memory strategy.
type UserPreferenceMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Input for user preference override configuration in a memory strategy.
type UserPreferenceOverrideConfigurationInput struct {
	// Input for user preference override consolidation configuration in a memory
	// strategy.
	Consolidation *UserPreferenceOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
	// Input for user preference override extraction configuration in a memory strategy.
	Extraction *UserPreferenceOverrideExtractionConfigurationInput `json:"extraction,omitempty"`
}

// Input for user preference override consolidation configuration in a memory
// strategy.
type UserPreferenceOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for user preference override extraction configuration in a memory strategy.
type UserPreferenceOverrideExtractionConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// VpcConfig for the Agent.
type VPCConfig struct {
	SecurityGroups []*string `json:"securityGroups,omitempty"`
	Subnets        []*string `json:"subnets,omitempty"`
}

// Stores information about a field passed inside a request that resulted in
// an exception.
type ValidationExceptionField struct {
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// The information about the workload identity.
type WorkloadIdentityDetails struct {
	WorkloadIdentityARN *string `json:"workloadIdentityARN,omitempty"`
}

// Contains information about a workload identity.
type WorkloadIdentityType struct {
	Name                *string `json:"name,omitempty"`
	WorkloadIdentityARN *string `json:"workloadIdentityARN,omitempty"`
}
