//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntime) DeepCopyInto(out *AgentRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntime.
func (in *AgentRuntime) DeepCopy() *AgentRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeArtifact) DeepCopyInto(out *AgentRuntimeArtifact) {
	*out = *in
	if in.ContainerConfiguration != nil {
		in, out := &in.ContainerConfiguration, &out.ContainerConfiguration
		*out = new(ContainerConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeArtifact.
func (in *AgentRuntimeArtifact) DeepCopy() *AgentRuntimeArtifact {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeEndpoint) DeepCopyInto(out *AgentRuntimeEndpoint) {
	*out = *in
	if in.AgentRuntimeARN != nil {
		in, out := &in.AgentRuntimeARN, &out.AgentRuntimeARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.LiveVersion != nil {
		in, out := &in.LiveVersion, &out.LiveVersion
		*out = new(string)
		**out = **in
	}
	if in.TargetVersion != nil {
		in, out := &in.TargetVersion, &out.TargetVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeEndpoint.
func (in *AgentRuntimeEndpoint) DeepCopy() *AgentRuntimeEndpoint {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeList) DeepCopyInto(out *AgentRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeList.
func (in *AgentRuntimeList) DeepCopy() *AgentRuntimeList {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeSpec) DeepCopyInto(out *AgentRuntimeSpec) {
	*out = *in
	if in.AgentRuntimeArtifact != nil {
		in, out := &in.AgentRuntimeArtifact, &out.AgentRuntimeArtifact
		*out = new(AgentRuntimeArtifact)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentRuntimeName != nil {
		in, out := &in.AgentRuntimeName, &out.AgentRuntimeName
		*out = new(string)
		**out = **in
	}
	if in.AuthorizerConfiguration != nil {
		in, out := &in.AuthorizerConfiguration, &out.AuthorizerConfiguration
		*out = new(AuthorizerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = new(NetworkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolConfiguration != nil {
		in, out := &in.ProtocolConfiguration, &out.ProtocolConfiguration
		*out = new(ProtocolConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHeaderConfiguration != nil {
		in, out := &in.RequestHeaderConfiguration, &out.RequestHeaderConfiguration
		*out = new(RequestHeaderConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeSpec.
func (in *AgentRuntimeSpec) DeepCopy() *AgentRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeStatus) DeepCopyInto(out *AgentRuntimeStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AgentRuntimeID != nil {
		in, out := &in.AgentRuntimeID, &out.AgentRuntimeID
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeVersion != nil {
		in, out := &in.AgentRuntimeVersion, &out.AgentRuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.WorkloadIdentityDetails != nil {
		in, out := &in.WorkloadIdentityDetails, &out.WorkloadIdentityDetails
		*out = new(WorkloadIdentityDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeStatus.
func (in *AgentRuntimeStatus) DeepCopy() *AgentRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntime_SDK) DeepCopyInto(out *AgentRuntime_SDK) {
	*out = *in
	if in.AgentRuntimeARN != nil {
		in, out := &in.AgentRuntimeARN, &out.AgentRuntimeARN
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeID != nil {
		in, out := &in.AgentRuntimeID, &out.AgentRuntimeID
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeName != nil {
		in, out := &in.AgentRuntimeName, &out.AgentRuntimeName
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeVersion != nil {
		in, out := &in.AgentRuntimeVersion, &out.AgentRuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntime_SDK.
func (in *AgentRuntime_SDK) DeepCopy() *AgentRuntime_SDK {
	if in == nil {
		return nil
	}
	out := new(AgentRuntime_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizerConfiguration) DeepCopyInto(out *AuthorizerConfiguration) {
	*out = *in
	if in.CustomJWTAuthorizer != nil {
		in, out := &in.CustomJWTAuthorizer, &out.CustomJWTAuthorizer
		*out = new(CustomJWTAuthorizerConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizerConfiguration.
func (in *AuthorizerConfiguration) DeepCopy() *AuthorizerConfiguration {
	if in == nil {
		return nil
	}
	out := new(AuthorizerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserNetworkConfiguration) DeepCopyInto(out *BrowserNetworkConfiguration) {
	*out = *in
	if in.VPCConfig != nil {
		in, out := &in.VPCConfig, &out.VPCConfig
		*out = new(VPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserNetworkConfiguration.
func (in *BrowserNetworkConfiguration) DeepCopy() *BrowserNetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(BrowserNetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserSummary) DeepCopyInto(out *BrowserSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserSummary.
func (in *BrowserSummary) DeepCopy() *BrowserSummary {
	if in == nil {
		return nil
	}
	out := new(BrowserSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeInterpreterNetworkConfiguration) DeepCopyInto(out *CodeInterpreterNetworkConfiguration) {
	*out = *in
	if in.VPCConfig != nil {
		in, out := &in.VPCConfig, &out.VPCConfig
		*out = new(VPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeInterpreterNetworkConfiguration.
func (in *CodeInterpreterNetworkConfiguration) DeepCopy() *CodeInterpreterNetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(CodeInterpreterNetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeInterpreterSummary) DeepCopyInto(out *CodeInterpreterSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeInterpreterSummary.
func (in *CodeInterpreterSummary) DeepCopy() *CodeInterpreterSummary {
	if in == nil {
		return nil
	}
	out := new(CodeInterpreterSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfiguration) DeepCopyInto(out *ContainerConfiguration) {
	*out = *in
	if in.ContainerURI != nil {
		in, out := &in.ContainerURI, &out.ContainerURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfiguration.
func (in *ContainerConfiguration) DeepCopy() *ContainerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ContainerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomJWTAuthorizerConfiguration) DeepCopyInto(out *CustomJWTAuthorizerConfiguration) {
	*out = *in
	if in.AllowedAudience != nil {
		in, out := &in.AllowedAudience, &out.AllowedAudience
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedClients != nil {
		in, out := &in.AllowedClients, &out.AllowedClients
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DiscoveryURL != nil {
		in, out := &in.DiscoveryURL, &out.DiscoveryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomJWTAuthorizerConfiguration.
func (in *CustomJWTAuthorizerConfiguration) DeepCopy() *CustomJWTAuthorizerConfiguration {
	if in == nil {
		return nil
	}
	out := new(CustomJWTAuthorizerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomMemoryStrategyInput) DeepCopyInto(out *CustomMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomMemoryStrategyInput.
func (in *CustomMemoryStrategyInput) DeepCopy() *CustomMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(CustomMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySummary) DeepCopyInto(out *GatewaySummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySummary.
func (in *GatewaySummary) DeepCopy() *GatewaySummary {
	if in == nil {
		return nil
	}
	out := new(GatewaySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Memory) DeepCopyInto(out *Memory) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Memory.
func (in *Memory) DeepCopy() *Memory {
	if in == nil {
		return nil
	}
	out := new(Memory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStrategy) DeepCopyInto(out *MemoryStrategy) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStrategy.
func (in *MemoryStrategy) DeepCopy() *MemoryStrategy {
	if in == nil {
		return nil
	}
	out := new(MemoryStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyMemoryStrategyInput) DeepCopyInto(out *ModifyMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyMemoryStrategyInput.
func (in *ModifyMemoryStrategyInput) DeepCopy() *ModifyMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(ModifyMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfiguration) DeepCopyInto(out *NetworkConfiguration) {
	*out = *in
	if in.NetworkMode != nil {
		in, out := &in.NetworkMode, &out.NetworkMode
		*out = new(string)
		**out = **in
	}
	if in.NetworkModeConfig != nil {
		in, out := &in.NetworkModeConfig, &out.NetworkModeConfig
		*out = new(VPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfiguration.
func (in *NetworkConfiguration) DeepCopy() *NetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(NetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolConfiguration) DeepCopyInto(out *ProtocolConfiguration) {
	*out = *in
	if in.ServerProtocol != nil {
		in, out := &in.ServerProtocol, &out.ServerProtocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolConfiguration.
func (in *ProtocolConfiguration) DeepCopy() *ProtocolConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProtocolConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestHeaderConfiguration) DeepCopyInto(out *RequestHeaderConfiguration) {
	*out = *in
	if in.RequestHeaderAllowlist != nil {
		in, out := &in.RequestHeaderAllowlist, &out.RequestHeaderAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestHeaderConfiguration.
func (in *RequestHeaderConfiguration) DeepCopy() *RequestHeaderConfiguration {
	if in == nil {
		return nil
	}
	out := new(RequestHeaderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticMemoryStrategyInput) DeepCopyInto(out *SemanticMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticMemoryStrategyInput.
func (in *SemanticMemoryStrategyInput) DeepCopy() *SemanticMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(SemanticMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SummaryMemoryStrategyInput) DeepCopyInto(out *SummaryMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SummaryMemoryStrategyInput.
func (in *SummaryMemoryStrategyInput) DeepCopy() *SummaryMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(SummaryMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSummary) DeepCopyInto(out *TargetSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSummary.
func (in *TargetSummary) DeepCopy() *TargetSummary {
	if in == nil {
		return nil
	}
	out := new(TargetSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPreferenceMemoryStrategyInput) DeepCopyInto(out *UserPreferenceMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPreferenceMemoryStrategyInput.
func (in *UserPreferenceMemoryStrategyInput) DeepCopy() *UserPreferenceMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(UserPreferenceMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCConfig) DeepCopyInto(out *VPCConfig) {
	*out = *in
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCConfig.
func (in *VPCConfig) DeepCopy() *VPCConfig {
	if in == nil {
		return nil
	}
	out := new(VPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityDetails) DeepCopyInto(out *WorkloadIdentityDetails) {
	*out = *in
	if in.WorkloadIdentityARN != nil {
		in, out := &in.WorkloadIdentityARN, &out.WorkloadIdentityARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityDetails.
func (in *WorkloadIdentityDetails) DeepCopy() *WorkloadIdentityDetails {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityDetails)
	in.DeepCopyInto(out)
	return out
}
