// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package code_interpreter

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.Certificates) != len(b.ko.Spec.Certificates) {
		delta.Add("Spec.Certificates", a.ko.Spec.Certificates, b.ko.Spec.Certificates)
	} else if len(a.ko.Spec.Certificates) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Certificates, b.ko.Spec.Certificates) {
			delta.Add("Spec.Certificates", a.ko.Spec.Certificates, b.ko.Spec.Certificates)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN) {
		delta.Add("Spec.ExecutionRoleARN", a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN)
	} else if a.ko.Spec.ExecutionRoleARN != nil && b.ko.Spec.ExecutionRoleARN != nil {
		if *a.ko.Spec.ExecutionRoleARN != *b.ko.Spec.ExecutionRoleARN {
			delta.Add("Spec.ExecutionRoleARN", a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ExecutionRoleRef, b.ko.Spec.ExecutionRoleRef) {
		delta.Add("Spec.ExecutionRoleRef", a.ko.Spec.ExecutionRoleRef, b.ko.Spec.ExecutionRoleRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration) {
		delta.Add("Spec.NetworkConfiguration", a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration)
	} else if a.ko.Spec.NetworkConfiguration != nil && b.ko.Spec.NetworkConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfiguration.NetworkMode, b.ko.Spec.NetworkConfiguration.NetworkMode) {
			delta.Add("Spec.NetworkConfiguration.NetworkMode", a.ko.Spec.NetworkConfiguration.NetworkMode, b.ko.Spec.NetworkConfiguration.NetworkMode)
		} else if a.ko.Spec.NetworkConfiguration.NetworkMode != nil && b.ko.Spec.NetworkConfiguration.NetworkMode != nil {
			if *a.ko.Spec.NetworkConfiguration.NetworkMode != *b.ko.Spec.NetworkConfiguration.NetworkMode {
				delta.Add("Spec.NetworkConfiguration.NetworkMode", a.ko.Spec.NetworkConfiguration.NetworkMode, b.ko.Spec.NetworkConfiguration.NetworkMode)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfiguration.VPCConfig, b.ko.Spec.NetworkConfiguration.VPCConfig) {
			delta.Add("Spec.NetworkConfiguration.VPCConfig", a.ko.Spec.NetworkConfiguration.VPCConfig, b.ko.Spec.NetworkConfiguration.VPCConfig)
		} else if a.ko.Spec.NetworkConfiguration.VPCConfig != nil && b.ko.Spec.NetworkConfiguration.VPCConfig != nil {
			if len(a.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups) != len(b.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups) {
				delta.Add("Spec.NetworkConfiguration.VPCConfig.SecurityGroups", a.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups, b.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups)
			} else if len(a.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups, b.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups) {
					delta.Add("Spec.NetworkConfiguration.VPCConfig.SecurityGroups", a.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups, b.ko.Spec.NetworkConfiguration.VPCConfig.SecurityGroups)
				}
			}
			if len(a.ko.Spec.NetworkConfiguration.VPCConfig.Subnets) != len(b.ko.Spec.NetworkConfiguration.VPCConfig.Subnets) {
				delta.Add("Spec.NetworkConfiguration.VPCConfig.Subnets", a.ko.Spec.NetworkConfiguration.VPCConfig.Subnets, b.ko.Spec.NetworkConfiguration.VPCConfig.Subnets)
			} else if len(a.ko.Spec.NetworkConfiguration.VPCConfig.Subnets) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.VPCConfig.Subnets, b.ko.Spec.NetworkConfiguration.VPCConfig.Subnets) {
					delta.Add("Spec.NetworkConfiguration.VPCConfig.Subnets", a.ko.Spec.NetworkConfiguration.VPCConfig.Subnets, b.ko.Spec.NetworkConfiguration.VPCConfig.Subnets)
				}
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
